# 排版校对

<!-- chapter morality  -->

\mytext

## 学生品德与社会化行为指数

良好的品德是个人成长、终身发展的基础，更是学生成为社会有用之才的重要条件。社会化则反映了学生对社会规则和价值的内化程度，具体表现为学生按照社会规范妥善行事。学生品德和社会化行为指标主要包括行为规范、亲社会行为、国家认同、国际视野这四个二级指标。

学生品德与社会化行为指数分为 9 级，指数越高，表示学生具有较好的品德行为素养。


\mylist

- 9级：表示90%以上的学生品德行为素养较高\footnote{我们将得分超过本维度总分50\%界定为品德行为素养较高。
}（含90%）
- 8级：表示80%-90%的学生品德行为素养较高（含80%）
- 7级：表示70%-80%的学生品德行为素养较高（含70%）
- 6级：表示60%-70%的学生品德行为素养较高（含60%）
- 5级：表示50%-60%的学生品德行为素养较高（含50%）
- 4级：表示40%-50%的学生品德行为素养较高（含40%）
- 3级：表示30%-40%的学生品德行为素养较高（含30%）
- 2级：表示20%-30%的学生品德行为素养较高（含20%）
- 1级：表示20%以下的学生品德行为素养较高

\mytext

plot.bar.school.index.morality


### 行为规范

\mytext

学生阶段是人的成长发展阶段，也是行为习惯养成的关键时期，良好的行为规范和习惯养成对学生个性形成与品德发展，具有极其深远的意义。

行为规范教育是校园常见的教育行为，意在从学生，行为规范出发，最终指向学生道德水平的提升。对于行为规范教育，研究者提出：学校管理层应平衡行为规范教育要求与教师的考核的关系，教师应充分理解学校的行为规范教育细则（徐冰清，2019）。

本项目中的行为规范主要指学生遵纪守法、遵守中小学生行为规范，能够维持正常适宜的学校和社会生活。具体来说，测评主要考察学生法律法规的遵守情况、学生学校行为规范的遵守情况、学生社会公共礼仪行为等方面。


行为规范指数是通过采集学生问卷数据，进行数据分析得到的结果。

学生行为规范指数分为 9 级，指数越高，表示学生具有较好的行为规范。

\mylist
- 9 级：表示 90% 以上的学生行为规范素养较高（含 90%）
- 8 级：表示 80%-90% 的学生行为规范素养较高（含 80%）
- 7 级：表示 70%-80% 的学生行为规范素养较高（含 70%）
- 6 级：表示 60%-70% 的学生行为规范素养较高（含 60%）
- 5 级：表示 50%-60% 的学生行为规范素养较高（含 50%）
- 4 级：表示 40%-50% 的学生行为规范素养较高（含 40%）
- 3 级：表示 30%-40% 的学生行为规范素养较高（含 30%）
- 2 级：表示 20%-30% 的学生行为规范素养较高（含 20%）
- 1 级：表示 20% 以下的学生行为规范素养较高
\mytext

plot.bar.school.index.conduct


### 亲社会行为

\mytext

亲社会行为指在社会交往的情境中有意识地做出帮助他人的行为或做有益于他人的事的倾向，主要体现在友爱宽容、乐于助人、善于合作、尊重他人等行为上。

研究发现，亲社会行为对行为实施者有自我提升的积极作用，实施亲社会行为能给个体带来意义感和效能感（Sonnentag ＆ Grant，2012），有利于个体应对焦虑、孤独等负性情绪（Storch，Brassard＆Masia-Warner，2003），还可以提高个体幸福感水平（Dunn，Gilbert，＆ Wilson，2011）。

亲社会行为测量主要有以他人利益为重的利他性维度、反映遵守社会或组织规范的遵规－公益性维度、反映社会交往双方人际和谐的关系性维度，以及反映自我提升动机的特质性四个维度。遵规-公益维度在行为规范测量中已有提及，因此本项目中亲社会行为测评重点关注利他性维度与关系性维度。

亲社会行为指数是通过采集学生问卷数据，进行数据分析得到的结果。

亲社会行为指数分为 9 级，指数越高，表示学生具有较好的亲社会行为。

\mylist
- 9 级：表示 90% 以上的学生亲社会行为素养较高（含 90%）
- 8 级：表示 80%-90% 的学生亲社会行为素养较高（含 80%）
- 7 级：表示 70%-80% 的学生亲社会行为素养较高（含 70%）
- 6 级：表示 60%-70% 的学生亲社会行为素养较高（含 60%）
- 5 级：表示 50%-60% 的学生亲社会行为素养较高（含 50%）
- 4 级：表示 40%-50% 的学生亲社会行为素养较高（含 40%）
- 3 级：表示 30%-40% 的学生亲社会行为素养较高（含 30%）
- 2 级：表示 20%-30% 的学生亲社会行为素养较高（含 20%）
- 1 级：表示 20% 以下的学生亲社会行为素养较高
\mytext

plot.bar.school.index.prosocial

### 国家认同

\mytext

随着全球化、信息化的发展，跨文化交流日益增加，青少年的国家认同感不仅关乎国家的统一与稳定，而且对社会的和谐与进步意义重大，也是建立富强民主国家之基础。

本项目的“国家认同”是指人对于国家或民族的归属感、认同感和责任感，通常以一个国家或民族独特的传统、文化、语言和政治作为代表。

研究发现，国家认同与一般国家自豪感和具体领域国家自豪感均具有显著正相关，青少年的国家认同越高则具有越强的国家自豪感（张莹瑞，2007）。针对11-19岁青少年，有学者提出国家认同的维度以及影响因素，认为国家认同有积极情感评价、公共集体自尊、互依信念、消极情感、自我归类和自我概念重要性六个维度；年龄、学校、家庭、民族身份等因素对国家认同有影响；国家认同度与自我认同度呈中低程度的相关（陈晶，2004）。

本项目中国家认同的测评主要调查学生在热爱祖国、认可中华优秀传统文化、民族平等与团结、勇于承担责任等社会主义核心价值观方面的表现。

国家认同指数是通过采集学生问卷数据，进行数据分析得到的结果。

国家认同指数分为 9 级，指数越高，表示学生具有较高的国家认同。

\mylist
- 9 级：表示 90% 以上的学生国家认同较高（含 90%）
- 8 级：表示 80%-90% 的学生国家认同较高（含 80%）
- 7 级：表示 70%-80% 的学生国家认同较高（含 70%）
- 6 级：表示 60%-70% 的学生国家认同较高（含 60%）
- 5 级：表示 50%-60% 的学生国家认同较高（含 50%）
- 4 级：表示 40%-50% 的学生国家认同较高（含 40%）
- 3 级：表示 30%-40% 的学生国家认同较高（含 30%）
- 2 级：表示 20%-30% 的学生国家认同较高（含 20%）
- 1 级：表示 20% 以下的学生国家认同较高
\mytext

plot.bar.school.index.country.identity

### 国际视野

\mytext

全球化发展对新生代提出新的要求，需要有理解不同文化、与不同文化背景人合作的能力。培养学生的国际视野，理解本国及他国文化，欣赏不同价值观，建立信任和跨越差异的合作关系，是未来青年理解与建构人类命运共同体的基石。

国际视野指能将世界看成一个自然、社会、历史的综合体，立足于人类命运共同体的建设，理解不同国家与民族的文化差异，认识、分析和思考世界历史和社会问题，并在互相尊重的基础上，能与不同文化背景的人开放、合适、有效地沟通。

研究显示，拥有良好国际视野的人，更容易与其他国籍人士交流、沟通与接纳其他文化。（沈旭晖、陈伟信、冯智政、曾家洛，2016）；Verena等人在2011年研究结果表明，具备良好国际视野和丰富跨国经历的学生，在解决社会或个人问题方面的能力更强。（Verena等，2011）

本项目中国际视野指标测评主要调查学生的全球意识（如自觉且敏锐地了解世界、尊重文化差异）、国际知识（对全球议题、国际规则、文化礼俗等的了解程度）、国际行为能力（如多国语言技能，分析、判断、解释国际问题和社会问题的能力）等方面。


国际视野指数是通过采集学生问卷数据，进行数据分析得到的结果。

国际视野指数分为 9 级，指数越高，表示学生具有较高的国际视野。

\mylist
- 9 级：表示 90% 以上的学生国际视野较高（含 90%）
- 8 级：表示 80%-90% 的学生国际视野较高（含 80%）
- 7 级：表示 70%-80% 的学生国际视野较高（含 70%）
- 6 级：表示 60%-70% 的学生国际视野较高（含 60%）
- 5 级：表示 50%-60% 的学生国际视野较高（含 50%）
- 4 级：表示 40%-50% 的学生国际视野较高（含 40%）
- 3 级：表示 30%-40% 的学生国际视野较高（含 30%）
- 2 级：表示 20%-30% 的学生国际视野较高（含 20%）
- 1 级：表示 20% 以下的学生国际视野较高
\mytext

plot.bar.school.index.global.view

<!-- end of chapter morality  -->
