
<!-- chapter 1 project summary -->

\mytext

# 学业质量绿色指标测试的实施概况

根据本市中小学教育质量综合评价改革的要求，上海市教育委员会组织成立了上海市中小学学业质量绿色指标综合评价项目组（以下简称“项目组”），按照《上海市教育委员会关于做好2018年度上海市中小学学业质量绿色指标综合评价工作的通知》(沪教委基[2018]65号)的文件要求，组织了2018年度初中学生学业质量绿色指标测试，测试对象为在上海市普通中小学校就读的九年级学生\footnote{由于测试的时间是10月份，本报告中九年级学生实际上是刚刚进入九年级就读。}，采用学科测试和问卷调查收集数据。项目组在评价队伍的建设、测试工具的研发、考务的组织与实施、评分标准的研制和阅卷、学业水平标准设定等方面开展了相关工作，以下是项目实施的概况。

## 测试概况

### 测试对象

2018年，全市16个区均抽样参加了“绿色指标”测试。除了体育运动学校和特殊教育学校外，所有的公、民办初中全部参加本次调查。每一所参加调查的学校是根据其学校规模按照随机等距抽样的方式抽取一定数量的样本学生。

本次共有645所初中62591名九年级学生参加了学科测试和问卷调查,其中每名学生参加类型1（语文、数学）或类型2（英语、科学）或类型3（艺术）的学科测试。12152位教师、1140位校长、58587位学生家长分别参加了教师问卷、校长问卷及家长问卷的调查。


### 学科测试内容

`r tab_name <- "初中学业质量测试科目及测试框架"`
本次九年级测试涉及语文、数学、英语、科学、艺术五门学科。各学科测试的内容不仅包括学生在基础知识、基本技能方面所达到的水平，而且还包括时代发展所要求的中小学生所必备的搜集处理信息、自主获取知识、分析与解决问题、交流与合作、创新精神与实践能力等核心素养。本次测试的测试框架见表\ref{tab: `r tab_name`}。

\begin{itshape}

\begin{longtable}{|p{1.5cm}|p{1.5cm}|l|p{2cm}|p{6cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\  \hline

 & \multicolumn{2}{c|}{\mytablehead{内容}} &  \multicolumn{2}{c|}{\mytablehead{能力\footnote{本表格中的科学学科为考查的维度。}}} \\  \hline

\multirow{5}{*}{\mytablehead{语文}}  & \multicolumn{2}{l|}{\makecell{积累与运用}} & \multicolumn{2}{l|}{\makecell[l]{读准字音\\认清字形\\理解词义\\积累和运用常见古诗文\\阅读名著}}  \\  \cline{2-5}
 & \multirow{3}{*}{阅读} & 获取信息 & \multicolumn{2}{l|}{\multirow{2}{*}{\makecell[l]{整体感知\\提取信息\\形成解释\\做出评价}}}  \\ \cline{3-3}
& & 获得文学体验 & \multicolumn{2}{l|}{}  \\ \cline{3-3}
& & 完成任务 & \multicolumn{2}{l|}{}   \\  \cline{2-5}
& \multicolumn{2}{l|}{写作} & \multicolumn{2}{l|}{\makecell[l]{能根据表达的需要，选取恰当的作文材料\\能有条理地安排文章的结构\\能具体明确、文从字顺地表达自己的意思}} \\  \hline

\multirow{2}{*}{\mytablehead{数学}} & \multicolumn{2}{l|}{\multirow{2}{*}{\makecell[l]{数与代数\\图形与几何\\函数与概率统计初步}}} & 过程分量 & \makecell[l]{辨识\\调用\\反思\\聚合} \\  \cline{4-5}
&  \multicolumn{2}{l|}{}  & 方法分量 & \makecell[l]{运算求解\\
推理论证\\空间想象\\数学表达\\数据处理\\数学建模} \\ \hline

英语 & \multicolumn{2}{l|}{\makecell[l]{语音\\词汇\\语法\\话题\\语言功能}} & \multicolumn{2}{l|}{\makecell[l]{听力\\阅读\\写作}} \\ \hline


科学 & \multicolumn{2}{l|}{\makecell[l]{地球宇宙\\物质科学\\生命科学\\科学探究}} & \multicolumn{2}{l|}{\makecell[l]{科学知识\\科学能力\\科学态度}} \\ \hline

艺术 & \multicolumn{2}{l|}{\makecell[l]{艺术形式\\艺术内容\\艺术风格\\艺术体验\\艺术创作}} & \multicolumn{2}{l|}{\makecell[l]{感受与鉴赏\\合作与分享\\表现与创作}} \\ \hline

\end{longtable}
\end{itshape}


### 问卷调查内容

本项目使用学生、教师、校长、家长问卷了解学生学习、教师专业发展、学校发展状况、家长对学校教育的感受状况及影响学生学业水平的相关因素。

学生问卷调查的内容包括学生基本情况、国际视野、品德行为、对学校的归属感、师生关系、同学关系、学习压力、学习动机和学习自信心等。

教师问卷调查的内容包括教师基本情况如学历、任职经历、职称、工作感受情况、教师对学校教学管理的评价、教学观念、学业评价能力和教师专业发展需求与困难等。

校长问卷调查的内容包括校长及学校基本情况、校长课程领导力、办学自主权、国家课程开设情况和对教师的专业支持等。

家长问卷调查的内容包括亲子关系、对孩子学业的支持以及对学校教育的感受等。


## 工作流程

### 测试工具开发

以绿色指标测试的学科（包括背景问卷）为单位，组织了一支由市、区教研员、一线优秀教师组成的命题队伍。项目组负责把握命题的方向与总体框架，对命题过程进行管理与监督，保证测试工具的质量。

根据本次测试的目标和任务，确定了以下命题原则：

第一，命题基于课程标准，体现课程标准的基本要求和理念。试题注重考查学生对学科核心知识、技能的理解和掌握，尤其是学生综合运用所学知识解决实际问题的能力、收集与分析信息的能力以及对重要学科思想方法的理解与掌握。

第二，命题严格控制试卷的总体难度，组卷以体现课程标准对学生基本要求的题目为主，有难度的题目主要考查学生的高层次认知能力。

第三，试题形式为客观性试题和主观性试题相结合。试题多使用真实的情境和任务，注重通过客观性试题考察学生高层次认知能力。


`r tab_name <- "学科测试工具的研发过程" `
本项目采用规范、严谨的程序开展试题编制工作，以下是2018年度命题工作的过程及时间安排（见表\ref{tab: `r tab_name`}）。

\begin{itshape}

\begin{longtable}{m{13cm}r}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

\multicolumn{1}{c}{\multirow{2}{*}{\mytablehead{测试工具的研发}}} & \mytablehead{时间节点} \\
  & \mytablehead{(2018年)} \\ \hline

绿色指标总项目组正式启动测试工具的研发工作 & 3月16日 \\
各学科命题组研讨各学科测试框架，依据往年测试情况对测试框架进行修订完善  & 3月17-25日 \\
外请专家对各学科命题组提交的学科测试框架进行审议 & 3月26日 \\
各学科命题组依据测试框架研制出用于预测试的三套试卷 & 3月-5月  \\
试题审查专家对三套试卷进行审查并向学科反馈试题审议结果 & 5月21日 \\
学科命题组对试题进行修订  & 5月-6月 \\
项目组赴外省开展100人预测试工作 & 6月29日 \\
各学科命题组组织不少于6名学生参加试题访谈，依据学生反馈意见对试题进行调整与修改 & 7月1-5日 \\
数据分析组根据预测试数据对试题进行分析并撰写分析报告 & 7月-8月 \\
学科命题组依据预测试数据分析结果，对试题进行修订和筛选，组成两套试卷  & 8月27-29日 \\
召开专家审议会议，对各学科测试卷和背景问卷进行评审，各学科命题组根据评审意见对试题进行修订及优化  & 9月25日 \\
各学科命题组依据评审结果对试题进行优化及适应性调整，最终确定正式卷和备用卷 & 9月26-27日 \\

\hline 
\end{longtable}
\end{itshape}

### 施测

项目组编制了《2018年上海市初中学业质量绿色指标测试考务实施手册》。上海市教委教研室、市教育督导部门等根据考务工作细则组织开展相关工作，包括编制培训手册，逐级对考务人员及管理人员进行培训，编制考生名册，制定详细的考务手册，组织具体的考务管理工作等。整个测试过程按照标准的考试进行管理，包括培训、考场设置、监考等环节。其中，所有参加测试学生名单在测试当天公布，参测学校负责人签订测试责任书。

### 评分标准研制

本次测试的非选择题均由人工批阅，因此评分标准的准确、全面和可操作性极其重要。在项目组的统一安排下，评分标准的研制由各学科命题组承担。在正式阅卷开始之前，各学科分别随机抽取适量份数，采取网上阅卷的方式，依据初步的评分标准对抽取到的学生作答进行评分。学科组经过反复讨论，修订、细化评分标准，最终形成评分手册。

### 阅卷

组建了由学科命题组成员、各区学科教研员及一线优秀教师组成的阅卷队伍。各学科命题组长担任阅卷组长，负责对阅卷人员进行培训和管理。整体阅卷工作原则上参照高考的相应要求组织实施，开放性试卷的评阅严格遵循国际上大型测试项目评卷标准进行，阅卷人员必须有较强的责任心，有丰富的教学经验或具有相应的职称水平，或有过中考等大型测试阅卷工作经验。

阅卷组长对阅卷人员进行的培训分为两部分，一是对新研制的评分手册进行培训，让阅卷员准确掌握自己需要评阅题目的评分标准；二是针对如何使用网络阅卷程序进行技术培训。

阅卷中采取的质量控制方式包括以下举措：

- 在计算机阅卷系统中预设各题目的给分范围，由计算机自动判断评分是否超出范围，及时给予提醒，极大地降低了出错的可能性。
- 控制工作时间和工作进度，避免阅卷员由于阅卷速度过快或疲劳降低评分准确性。
- 阅卷组长对评分过程中出现的分歧组织讨论、统一认识和做法并对最终结果进行认定。
- 部分主观题采取多人共评、个体独立阅卷的方式，多人评分的平均值作为最终得分；当评分差值超过预先设定的阈值由阅卷组长根据答卷情况对结果进行调整和确认。
- 各学科阅卷组设质量监督员，全程关注由计算机生成的评分信息，包括评分一致性、阅卷工作进度、重评率等，发现异常现象及时通知相关阅卷人员。


### 测试数据的录入、整理

背景问卷是采用网络方式直接采集做大数据，学科测试均采取填涂答题纸的方式，其录入由机器扫描完成。扫描答题纸时，计算机会根据预设条件对数据进行自动检测和判断，在这个过程中由专人进行全程监督，发现异常现象或错误数据立即进行纠正。

数据分析组根据一定的准则对数据进行清理，剔除空白卷、缺考卷、无考号卷的作答信息。若某份试卷的客观题作答信息全部为空或者主观题全部没有作答，并且经核查不是漏扫或漏评的，则该试卷视为无效作答。


### 学业水平标准设定

项目组邀请国际知名专家香港中文大学原副校长侯杰泰教授和美国ETS（美国教育考试服务中心）测量专家钱家和博士主持开展“学业水平标准设定”工作。各学科的专家评委由课程标准编制者、教材主编、区教研员、不同区域不同教龄的一线教师、学生家长等16人组成，采用Angoff和Bookmark的方法共同研讨和确定了上海地区相关学科的及格、良好和优秀的标准。

本次阅卷结束后，数据分析组对测试结果进行了整理和分析，研讨了数据处理与等值方案。测试的各门学科根据两年度间（2015年与2018年）平均得分率的差异，将划界分数点进行平移的等值方法上进行等值处理，划定了2018年度上海市初中五门学科的学业水平。学业水平的划分结果采用A、B、C、D四个水平进行表述，其中A水平为最高等级，D水平为最低等级。


### 数据分析与报告撰写

本项目在测试数据分析的过程中，将经典测量理论与项目反应理论等先进测量技术相结合，对数据进行充分的分析，保证了测试结果分析的科学性。在此基础上，本次测试中所有的学科测试结果都采用量尺分数。量尺分数是根据学生的作答情况，采用项目反应理论模型将学生能力分数转换成的测验得分数，它具有不受测验题目差异和测验难度影响的特点，同时能与本项目前几年的测试结果进行比较。初中各学科整体上的平均分在500分左右，标准差在100左右，在各学科的各个维度上的平均分在300分左右，标准差在50左右。

经过绿色指标项目组的充分研讨，确定了反馈报告的整体撰写框架，各学科命题组长分别对各学科测试的结果进行了分析并对学生在典型试题上的表现进行了评价。问卷部分呈现了学生、教师、校长及家长的基本情况并分析了学生学业成绩与有关背景变量的关系。


### 系列报告构成

`r tab_name <- "测试报告的构成" `
本次系列报告主要由三种层次8个类别共计15种报告构成。报告充分考虑到不同使用者对于报告内容要求不同的问题，依此将报告划分为综合报告和学科报告，具体见表\ref{tab: `r tab_name`}。

\begin{table}[H]
\centering

\caption{`r tab_name`} \label{tab: `r tab_name`}
\itshape

\begin{tabularx}{\textwidth}{|r|c|c|c|X|}

\hline
 \multicolumn{1}{|c|}{\multirow{2}{*}{\mytablehead{名称}}}  &  \multicolumn{3}{c|}{\mytablehead{报告层次}} &  \multicolumn{1}{c|}{\multirow{2}{*}{\mytablehead{对象}}}\\  \cline{2-4}
     &   \mytablehead{市级}  & \mytablehead{区级} & \mytablehead{学校} &  \\      \hline

绿色指标基础数据报告 & √  & √ & & \multirow{2}{*}{教育决策者、教科研人员等} \\ \cline{1-4}
绿色指标指数报告 & √  & √ & &  \\ \hline
绿色指标学校报告 &   &  & √ & 校长、教师等 \\ \hline
初中语文学科报告 & √  & √ & & \multirow{5}{*}{学科教研员、校长、教师等} \\ \cline{1-4}
初中数学学科报告 & √  & √ & &  \\  \cline{1-4}
初中英语学科报告 & √  & √ & &  \\  \cline{1-4}
初中科学学科报告 & √  & √ & &  \\  \cline{1-4}
初中艺术学科报告 & √  & √ & &  \\  \hline

\end{tabularx}
\end{table}

<!-- end of chapter 1 project summary -->
