<!-- chapter dimention -->

\mytext

# 学生在各内容领域和考查维度上的表现情况

## 全体学生在各内容领域和考查维度上的表现

### 全体学生在各内容领域上的表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.sc.content.rank")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.district.sc.content.quantile")`}分别给出了本区学生在科学学科各内容领域各水平上的人数比例和得分分布。

plot.bar.district.sc.content.rank
plot.box.district.sc.content.quantile


### 全体学生在各考查维度上的表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.sc.dimention.rank")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.district.sc.dimention.quantile")`}分别给出了本区学生在科学学科各考查维度各水平上的人数比例和得分分布。

plot.bar.district.sc.dimention.rank
plot.box.district.sc.dimention.quantile


## 学生在各内容领域的表现

### 地球宇宙

#### 不同群体学生的表现

plot.bar.district.sc.earth.rank.perspective
plot.box.district.sc.earth.quantile.perspective

#### 不同学校学生的表现

multiplot.bar.district.sc.earth.rank.school
multiplot.box.district.sc.earth.quantile.school

### 生命科学

#### 不同群体学生的表现

plot.bar.district.sc.life.rank.perspective
plot.box.district.sc.life.quantile.perspective


#### 不同学校学生的表现

multiplot.bar.district.sc.life.rank.school
multiplot.box.district.sc.life.quantile.school

### 物质科学

#### 不同群体学生的表现

plot.bar.district.sc.physics.rank.perspective
plot.box.district.sc.physics.quantile.perspective

#### 不同学校学生的表现

multiplot.bar.district.sc.physics.rank.school
multiplot.box.district.sc.physics.quantile.school

### 科学探究

#### 不同群体学生的表现

plot.bar.district.sc.explore.rank.perspective
plot.box.district.sc.explore.quantile.perspective

#### 不同学校学生的表现

multiplot.bar.district.sc.explore.rank.school
multiplot.box.district.sc.explore.quantile.school

## 学生在各考查维度的表现

### 科学知识

#### 不同群体学生的表现

plot.bar.district.sc.knowledge.rank.perspective
plot.box.district.sc.knowledge.quantile.perspective

#### 不同学校学生的表现

multiplot.bar.district.sc.knowledge.rank.school
multiplot.box.district.sc.knowledge.quantile.school

### 科学能力

#### 不同群体学生的表现

plot.bar.district.sc.skill.rank.perspective
plot.box.district.sc.skill.quantile.perspective

#### 不同学校学生的表现

multiplot.bar.district.sc.skill.rank.school
multiplot.box.district.sc.skill.quantile.school

### 科学态度

#### 不同群体学生的表现

plot.bar.district.sc.attitude.rank.perspective
plot.box.district.sc.attitude.quantile.perspective


#### 不同学校学生的表现

multiplot.bar.district.sc.attitude.rank.school
multiplot.box.district.sc.attitude.quantile.school

<!-- end of chapter dimention -->
