<!--  chapter -->

\mytext

# 教师背景问卷调查结果分析

query.data.city.base.teacher.survey

教师背景问卷包含教师的基本情况、教师的教学方法、教师对学校教学管理的评价、教师的教学观念和教师的专业发展五个方面。本章对九年级教师在这五个方面的回答进行了分析，得到如下主要结论：

- 九年级教师中男老师占`r gio.R$AttSamKey(query.data, "性别", "总体", c("男"), 1)`%，女老师占`r gio.R$AttSamKey(query.data, "性别", "总体", c("女"), 1)`%。
- 九年级教师教龄在5年及以下的占`r gio.R$AttSamKey(query.data, "教龄", "总体", c("5年及以下"), 1)`%，在20年以上的占`r gio.R$AttSamKey(query.data, "教龄", "总体", c("20年以上"), 1)`%，在6-20年的占`r gio.R$AttSamKey(query.data, "教龄", "总体", c("6-10年", "11-15年", "16-20年"), 1)`%。
- 九年级教师中，有`r gio.R$AttSamKey(query.data, "职称", "总体", c("中学高级","中学一级"), 1)`%的教师具有中学一级或高级职称。
- 九年级`r gio.R$AttSamKey(query.data, "学历", "总体", c("本科", "硕士", "博士"), 1)`%的教师是本科及以上学历，`r gio.R$AttSamKey(query.data, "学历", "总体", c("大专", "中师"), 1)`%的教师是大专及以下学历。
- 九年级教师就职前接受过师范教育的比例为`r gio.R$AttSamKey(query.data, "师范教育", "总体", c("是"), 1)`%，所教学科与所学专业一致的比例为`r gio.R$AttSamKey(query.data, "专业对口", "总体", c("一致"), 1)`%。
- 九年级教师每周上课节数在11-15节的占`r gio.R$AttSamKey(query.data, "周上课节数", "总体", c("11-15节"), 1)`%，在6节以下的占`r gio.R$AttSamKey(query.data, "周上课节数", "总体", c("6节以下"), 1)`%，在21节以上的占`r gio.R$AttSamKey(query.data, "周上课节数", "总体", c("21节及以上"), 1)`%。
- 九年级教师每天的工作时间在8-11小时的占`r gio.R$AttSamKey(query.data, "日工作时间", "总体", c("8-9小时(含9小时)", "9-11小时(含11小时)"), 1)`％，8小时及以下的占`r gio.R$AttSamKey(query.data, "日工作时间", "总体", c("8小时及以下"), 1)`%，11小时以上的占`r gio.R$AttSamKey(query.data, "日工作时间", "总体", c("11-13小时(含13小时)", "13小时以上"), 1)`%。
- 九年级教师有`r gio.R$AttSamKey(query.data, "喜欢教师工作", "总体", c("比较喜欢", "非常喜欢"), 1)`％喜欢教师职业。

- 九年级教师中有`r gio.R$SamTopKey(query.data, "总体", "作为教师,我的角色就是引导学生自行探究", c("比较同意", "非常同意"), 1)`%认同教师的角色是引导学生自行探究；有`r gio.R$SamTopKey(query.data, "总体", "在课堂上应尽可能多创造机会让学生向教师提问", c("比较同意", "非常同意"), 1)`%认同在课堂上应尽可能多创造机会让学生向教师提问；`r gio.R$SamTopKey(query.data, "总体", "思考和推理过程比具体的课程内容更重要", c("比较同意", "非常同意"), 1)`%认为思考和推理过程比具体的课程内容更重要。

- 九年级教师专业发展的途径主要是与同事分享经验、讨论问题，观摩他人的课并在课后进行研讨以及参加学校或教研部门组织的教研活动；教师专业发展的需求主要集中在对个性化教学的方法，教学技能，所教学科领域知识及学生评价和测量方法；教师专业发展遇到的困难主要是缺乏专业活动的资金，时间的冲突及缺乏参加相关活动的机会。


- 九年级教师有`r gio.R$SamTopKey(query.data, "总体", "学校的课程建设思路与方案具有本校特色", c("比较符合", "非常符合"), 1)`％认为学校的课程建设思路与方案具有本校特色。


## 教师基本情况


### 教师性别

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.gender.perspective")`}给出了九年级教师性别的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.gender.perspective


### 教师教龄

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.years.perspective")`}给出了九年级教师教龄的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.years.perspective


### 教师职称

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.rank.perspective")`}给出了九年级教师职称的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.rank.perspective


### 教师学历

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.education.perspective")`}给出了九年级教师学历的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.education.perspective


### 教师师范教育情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.normaledu.perspective")`}给出了九年级教师接受师范教育的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.normaledu.perspective


### 教师专业对口情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.match.perspective")`}给出了九年级教师专业对口的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.match.perspective


### 教师每周上课节数

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.work.weekly.perspective")`}给出了九年级教师每周上课节数的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.work.weekly.perspective


### 教师每日工作时间

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.work.daily.perspective")`}给出了九年级教师每日工作时间的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.work.daily.perspective


## 教师的职业感受


### 教师职业喜爱程度

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.career.love.perspective")`}给出了九年级教师对教师职业喜爱程度的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.career.love.perspective


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.career.jump.perspective")`}给出了九年级教师离职倾向的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.career.jump.perspective


### 教师工作满意度

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.career.satisfaction")`}给出了九年级教师工作满意度的总体情况及不同群体之间的比较。

plot.bar.city.base.teacher.career.satisfaction


## 教师的课程领导力

### 教师教学理念

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.opinion")`}给出了九年级教师教学理念的总体情况。

plot.bar.city.base.teaching.opinion

### 教师学业评价能力

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.evaluation.firststep")`}给出了九年级教师对“命制一套学科测试卷时，最先做的一步”的反馈总体情况。

plot.bar.city.base.teaching.evaluation.firststep

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.evaluation.twowayspec")`}给出了九年级教师对“命制一份测试卷时，使用双向细目表的主要优点”的反馈总体情况。

plot.bar.city.base.teaching.evaluation.twowayspec

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.evaluation.solution")`}给出了九年级教师对“评价学生对她所教的解题策略的掌握情况。以下哪种评价方法最有效？”的反馈总体情况。

plot.bar.city.base.teaching.evaluation.solution

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.evaluation.thinking")`}给出了九年级教师对“想评价学生的高层次思维，而不是仅仅描述事实的能力。应该用以下哪些词来编制作文题，以达到这个目标”的反馈总体情况。

plot.bar.city.base.teaching.evaluation.thinking

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.evaluation.exam")`}给出了九年级教师对“采用何种方式才是最有效地利用了考试的结果？”的反馈总体情况。

plot.bar.city.base.teaching.evaluation.exam

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.evaluation.unit")`}给出了九年级教师对“哪一项信息对设计一个单元的课堂教学最有帮助？”的反馈总体情况。

plot.bar.city.base.teaching.evaluation.unit

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teaching.evaluation.principal")`}给出了九年级教师对“校长评估老师的教学表现，想了解老师在课堂中是否鼓励了学生进行高层次思维，哪个文本材料有助于校长做出最有效的决策？”的反馈总体情况。

plot.bar.city.base.teaching.evaluation.principal


## 教师专业发展


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.develop.action")`}给出了九年级教师参与专业发展相关活动的总体情况。

plot.bar.city.base.teacher.develop.action


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.develop.requirement")`}给出了九年级教师专业发展需求的总体情况。

plot.bar.city.base.teacher.develop.requirement


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.develop.difficulty")`}给出了九年级教师专业发展困难的总体情况。

plot.bar.city.base.teacher.develop.difficulty


## 教师对学校课程领导力的感知

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.course.plan")`}给出了九年级教师对学校课程规划的感知的总体情况。

plot.bar.city.base.teacher.course.plan


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.course.excute")`}给出了九年级教师对学校课程实施的感知的总体情况。

plot.bar.city.base.teacher.course.excute


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.teacher.course.evaluation")`}给出了九年级教师对学校课程评价的感知的总体情况。

plot.bar.city.base.teacher.course.evaluation

\clearpage

<!--  end of chapter -->
