<!--  chapter -->

\mytext

# 家长背景问卷调查结果分析

query.data.city.base.parent.survey

家长问卷包括从家长的角度了解孩子的相关情况，如孩子睡眠时间、上床时间等，对孩子学业的预期，亲子关系以及对学校的满意度。本章对家长问卷的结果进行分析。以下是主要的分析结果：

- 八年级学生家长中每周主动询问孩子在校情况五次以上的约`r gio.R$AttSamKey(query.data, "亲子交流频率", "总体", c("每周五次及以上"), 1)`%，约`r gio.R$AttSamKey(query.data, "亲子交流频率", "总体", c("基本不交流"), 1)`%的学生家长基本不询问；
- 八年级学生家长报告孩子总是参与家庭事务讨论的约`r gio.R$AttSamKey(query.data, "家庭讨论频率", "总体", c("总是"), 1)`%，约`r gio.R$AttSamKey(query.data, "家庭讨论频率", "总体", c("从不"), 1)`%的孩子从不参与讨论；
- 家长反应八年级孩子平均每天在家做家务一小时以上的仅%，劳动时间在30分钟到1小时间的约%，有%的孩子在家从来不做家务；
- 调查表明八年级学生家长每周陪伴孩子共同活动（不含书面作业）时长在4小时以上的约`r gio.R$AttSamKey(query.data, "亲子活动时间", "总体", c("4小时及以上"), 1)`%，`r gio.R$AttSamKey(query.data, "亲子活动时间", "总体", c("1小时以内"), 1)`%的家长表示陪伴时间不超过1小时；
- 八年级学生家庭中家长与孩子每天都要吵架的比例约占%，有%的家长反应与孩子几乎不吵架或从不吵架；
- 八年级学生家长对孩子的教育期望普遍较高，`r gio.R$AttSamKey(query.data, "教育期望", "总体", c("大学科", "硕士", "博士"), 1)`%以上的家长希望孩子读到大学本科以上，`r gio.R$AttSamKey(query.data, "教育期望", "总体", c("博士"), 1)`%的家长希望孩子能读完博士；
- 学生家长心目中理想的学校最重要的特征中，%的家长希望师资力量比较强，%的家长希望办学理念比较好，%的家长希望有较多的特色课程。


## 家庭结构

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.type")`}给出了学生的家庭结构\footnote{其中核心家庭指的是孩子平时和父亲、母亲或父母双方以及兄弟姐妹生活在一起的家庭。主干家庭指的是孩子平时和除了父亲、母亲、兄弟姐妹以外还有（外）祖父母一起生活的家庭。扩大家庭指的是孩子平时除父母、兄弟姐妹、（外）祖父母以外还有其他人一起生活的家庭。}的总体情况及各群体之间的比较。

plot.bar.city.base.family.type


## 亲子关系

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.communication")`}给出了学生家庭亲子交流的总体情况及各群体之间的比较。

plot.bar.city.base.family.communication

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.discuss")`}给出了学生家庭事务讨论的总体情况及各群体之间的比较。

plot.bar.city.base.family.discuss

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.accompany")`}给出了学生家庭亲子陪伴的总体情况及各群体之间的比较。

plot.bar.city.base.family.accompany


## 教育期望

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.expection")`}给出了学生家长对子女教育期望的总体情况及各群体之间的比较。

plot.bar.city.base.family.expection


## 家庭辅导

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.incharge")`}给出了学生家庭对子女教育分工的总体情况及各群体之间的比较。

plot.bar.city.base.family.incharge

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.tutor")`}给出了学生家庭辅导的总体情况及各群体之间的比较。

plot.bar.city.base.family.tutor


## 家长教育观念

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.incharge")`}给出了学生家长教育观念的总体情况。

plot.bar.city.base.family.opinion

## 家长对学校满意度

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.family.satisfaction")`}给出了学生家长对学校满意度的总体情况。

plot.bar.city.base.family.satisfaction

\clearpage

<!--  end of chapter  -->
