<!--  chapter  -->

\mytext

# 校长背景问卷调查结果分析

query.data.district.base.principal.survey

校长问卷包括校长基本情况、校长日常工作、学校发展、学校办学成效、校长对学校满意度等方面。本章对校长问卷上的回答进行分析。以下是分析得到的主要结果：

- 初中校长男性比例为`r gio.R$AttSamKey(query.data, "性别", "总体", c("男"), 1)`%，女性比例为`r gio.R$AttSamKey(query.data, "性别", "总体", c("女"), 1)`%。
`r key <- gio.R$AttSamMaxKey(query.data, "年龄", "总体", 1)`
- 初中校长年龄主要分布在`r key`，占`r gio.R$AttSamKey(query.data, "年龄", "总体", c(key), 1)`%。
`r key <- gio.R$AttSamMaxKey(query.data, "任职年限", "总体", 1)`
- 初中校长任职年限多为`r key`，占`r gio.R$AttSamKey(query.data, "任职年限", "总体", c(key), 1)`%。
- 初中校长的学历主要是本科，比例为`r gio.R$AttSamKey(query.data, "学历", "总体", c("本科"), 1)`%，研究生学历的初中校长比例为`r gio.R$AttSamKey(query.data, "学历", "总体", c("硕士", "博士"), 1)`%。
- 初中校长的职级是二级及以上的比例为`r gio.R$AttSamKey(query.data, "职级", "总体", c("二级", "一级", "特级"), 1)`%。
- 初中校龄在 45 年以上的占`r gio.R$AttSamKey(query.data, "学校历史", "总体", c("46-60年", "60年以上"), 1)`%，在 15 年以下的占 `r gio.R$AttSamKey(query.data, "学校历史", "总体", c("15年以下"), 1)`%。
- 初中校长的日常工作中，参加会议的时间比例为 `r gio.R$AttSamKey(query.data, "参加会议", "总体", c("数值平均"), 1)`%，给学生上课的时间比例为`r gio.R$AttSamKey(query.data, "给学生上课", "总体", c("数值平均"), 1)`%，参加听课、评课及教研活动的时间比例为`r gio.R$AttSamKey(query.data, "教研活动", "总体", c("数值平均"), 1)`%，与教师交流、听取教师意 见的时间比例为`r gio.R$AttSamKey(query.data, "与师生交流", "总体", c("数值平均"), 1)`%，应对上级行政部门的检查和评估所占的时间比例为`r gio.R$AttSamKey(query.data, "应对检查评估", "总体", c("数值平均"), 1)`%， 在科研、教学、资金使用方面的规划与审批所占的时间比例为`r gio.R$AttSamKey(query.data, "规划与审批", "总体", c("数值平均"), 1)`%。
- 近三年学校印刷学科交流与经验分享的成果集的数量在2本及以上的学校的比例分 别为`r gio.R$AttSamKey(query.data, "成果出版", "总体", c("2本", "3本", "4本及以上"), 1)`%。;近三年学校根据学生学习需要，开设校本课程的数量11门以上占`r gio.R$AttSamKey(query.data, "校本课程", "总体", c("11-20门", "20门以上"), 1)`%; `r 100 - gio.R$AttSamKey(query.data, "学生社团", "总体", c("没有"), 1)`%的学校建设了学生社团、兴趣小组和俱乐部。
- 初中校长对学校教育各方面感受的评价普遍较高。


\clearpage

## 校长基本情况

校长基本情况包括校长的性别、年龄、担任校长年限、学历、职称和职级。

### 校长性别

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.gender.perspective")`}给出了校长性别的总体情况及不同群体之间的比较。

plot.bar.district.base.principal.gender.perspective

### 校长年龄

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.age.perspective")`}给出了校长年龄的总体情况及不同群体之间的比较。

plot.bar.district.base.principal.age.perspective

\clearpage

### 校长任职年限

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.years.perspective")`}给出了校长任职年限的总体情况及不同群体之间的比较。

plot.bar.district.base.principal.years.perspective


### 校长学历

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.edu.perspective")`}给出了校长学历的总体情况及不同群体之间的比较。

plot.bar.district.base.principal.edu.perspective

\clearpage

### 校长职级

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.rank.perspective")`}给出了校长职级的总体情况及不同群体之间的比较。

plot.bar.district.base.principal.rank.perspective

### 学校校龄

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.school.history.perspective")`}给出了学校校龄的分布情况。

plot.bar.district.base.school.history.perspective


\clearpage

## 校长日常工作

### 校长参加会议

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.meeting.perspective")`}给出了校长参加各种会议时间占比的总体情况及各群体之间的比较。

plot.bar.district.base.principal.meeting.perspective

### 校长给学生上课

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.teaching.perspective")`}给出了校长给学生上课时间占比总体情况及各群体之间的比较。

plot.bar.district.base.principal.teaching.perspective


\clearpage

### 校长参加听课、评课及教研活动

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.researching.perspective")`}给出了校长参加听课、评课及教研活动时间占比总体情况及各群体之间的比较。

plot.bar.district.base.principal.researching.perspective

### 校长应对上级行政部门的检查、评估

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.audited.perspective")`}给出了校长应对上级行政部门的检查、评估时间占比总体情况及各群体之间的比较。

plot.bar.district.base.principal.audited.perspective

\clearpage

### 校长科研、教学、资金使用等方面的规划与审批

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.planning.perspective")`}给出了校长科研、教学、资金使用等方面的规划与审批时间占比总体情况及各群体之间的比较。

plot.bar.district.base.principal.planning.perspective

### 校长和教师、学生交流，听取他们的意见和想法

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.communicating.perspective")`}给出了校长和教师、学生交流，听取他们的意见和想法时间占比总体情况及各群体之间的比较。

plot.bar.district.base.principal.communicating.perspective


\clearpage

## 与学校发展有关问题的调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.communicating.perspective")`}描述了校长对学校发展遇到的困难情况的反馈。

plot.bar.district.base.principal.challenge

\clearpage

## 与学校办学成效有关问题的调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.school.publishing.perspective")`}描述了学校近三年正式出版专门的学科交流与经验分享的成果集的数量及与各 群体之间的比较。

plot.bar.district.base.school.publishing.perspective

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.school.course.perspective")`}描述了学校根据学生学习需要，开设校本课程的数量及与各群体之间的比较。

plot.bar.district.base.school.course.perspective

\clearpage

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.school.community.perspective")`}描述了学校建设学生社团、兴趣小组和俱乐部的数量及与各群体之间的比较。

plot.bar.district.base.school.community.perspective

\clearpage

## 与校长对学校感受有关情况的调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.feeling")`}给出了校长对学校感受的情况。

plot.bar.district.base.principal.feeling

\clearpage


## 与校长的教学理念相关问题的调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.principal.thinking")`}给出了校长教学理念的总体情况。

plot.bar.district.base.principal.thinking

\clearpage

<!--  end of chapter -->
