<!-- chapter description -->
\mytext

# 学科测试说明

## 九年级语文学科测试简介


2018 年度上海市初中学业质量绿色指标语文学科测试依据学科测试框架，从“积累”“阅读”“写作”三个维度来考查学生语文方面的学业水平。主要检测学生在基础知识积累、阅读能力、写作能力及语文综合运用能力等几方面的实际发展水平，以此来刻画学生的语文素养水平。

### 积累
积累包括识字写字能力和语言材料的储备。识字与写字能力是阅读和写作的基础，是语文素养最基本的组成部分。识字能力的高低，体现在学生对已经学过的常用汉字音形义的掌握程度上，与学生是否具有独立识字的能力密切相关。语言材料的积累主要包括常用词汇、成语、文言诗文、文学名著等。因此，该部分包括以下几点：

- 读准常用字的字音
- 认清常用字的字形
- 理解常用字词的字义、词义
- 积累教材中的古诗词
- 积累教材中的文言文
- 积累所涉及到的文学、文化常识
- 完成课程标准规定的课外阅读量

### 阅读

阅读是搜集处理信息、认识世界、发展思维、获得审美体验的重要途径。因此本部分关注学生通过阅读形成理解、解决问题的能力。
在阅读的考查中，九年级不仅关注学生的现代文阅读能力，还关注学生浅易文言文的阅读能力。
现代文阅读能力主要考查学生对文本的领会与感受、评价与运用。具体包括：

- 提取文本信息
- 感知文本内容
- 分析与解释文本内容与形式
- 评价文本内容与形式

文言诗文阅读主要考查学生对浅易文言文的理解，包括对文言词语、句子和篇章的理解，感受文言诗文的语言形式特点。

阅读部分在考查学生阅读能力的过程中，还注重对学生在阅读基础上运用语文知识和技能完成任务能力的考查，重点考查学生利用文本信息完成日常生活情境中真实任务的能力。要求九年级学生有效利用文本信息、深入理解文本、评价文本，完成比较复杂的任务。

### 写作

写作是运用语言文字进行表达和交流的重要方式，是语文素养的综合体现。本测试中，本部分不仅考查学生写作的基本能力，也考查学生写字能力。
写作测试关注学生根据题意的要求，文从字顺地表达自己的思想的能力。具体包括：

- 根据写作要求选材立意
- 根据表达的需要合理安排文章结构
- 文从字顺地表达自己的意思
- 正确、规范、端正地书写汉字


## 九年级语文学业水平描述
语文测试主要从“积累”“阅读”和“写作”三个方面考查学生的语文学业水平。

`r tab_name <- "语文学科学业水平描述" `
表\ref{tab: `r tab_name`}对九年级学生在语文学科不同考查能力上的表现分水平进行了学业水平描述。

\clearpage

\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\

\hline
 \multicolumn{1}{|c}{\mytablehead{考查能力}} &  \multicolumn{1}{|c|}{\mytablehead{水平}} &  \multicolumn{1}{c|}{\mytablehead{水平描述}} \\
\hline
   \multirow{6}{*}{积累}  & \multirow{6}{*}{A}  & $\star$ 能读准常用字中同年级学生易错字字音，并能分辨相近字音间的区别；   \\  
   & &  $\star$ 能认清常用字中同年级学生易错字字形，并能分辨相近字形间的区别； \\    
   & &  $\star$	能理解常用词语、成语的准确意思，分辨词义间的细微差别，并在较复杂的语境中恰当运用； \\    
   & &  $\star$	能根据复杂语境的需要恰当使用关联词； \\  
   & &  $\star$	能准确理解课程标准规定的文言诗文的基本内容； \\    
   & &  $\star$	阅读名著，熟悉相关的文学文化常识、主要内容。 \\    
\cline{2-3}      

   &   \multirow{5}{*}{B}  &  $\star$	能读准常用字中同年级学生易错字字音；  \\  
   & &  $\star$	能认清常用字中同年级学生易错字字形； \\  
   & &  $\star$	能理解常用词语、成语的基本意思，分辨词义间的细微差别，并在较简单语境中恰当运用； \\    
   & &  $\star$	能理解课程标准规定的文言诗文的基本意思； \\    
   & &  $\star$	阅读名著，了解相关的文学文化常识、主要情节。 \\    
\cline{2-3}

   &   \multirow{5}{*}{C}  & $\star$ 能读准所学过的大部分常用字字音； \\  
   & &  $\star$	能认清所学过的大部分常用字字形； \\  
   & &  $\star$	能理解常用词语、成语的基本意思，分辨词义间的明显差别，并在较简单语境中恰当运用； \\    
   & &  $\star$	能根据上下句的提示记忆所学过的课程标准规定的文言诗文； \\
   & &  $\star$	阅读名著，能了解主要情节。 \\
\cline{2-3}

  &   \multirow{5}{*}{D}  & $\star$	不能读准常用字字音，或只能根据提示读准部分常用字字音； \\  
  & &  $\star$	不能认清常用字字形，或只能根据提示认清部分常用字字形；  \\  
  & &  $\star$	能分辨词语、成语基本意思间明显的差别，但不能在语境中运用所学过的词语或成语； \\    
  & &  $\star$	不能记忆课程标准规定的文言诗文，或只能根据提示记忆所学过的部分文言诗文；  \\
  & &  $\star$	不能了解名著的主要情节，或只能根据提示了解名著的部分情节。 \\
\hline

   \multirow{20}{*}{阅读}  &   \multirow{5}{*}{A}  & $\star$	能根据要求从文本中提取出隐含的信息； \\
   & &  $\star$	能形成对文本的整体感知，完整、简练地概括出文本的主要内容； \\  
   & &  $\star$	能在综合考虑整篇文本的基础上，联系自身已有经验，对相关问题做出充分、合理的解释； \\  
   & &  $\star$	能结合文本信息和个人已有知识经验从多个角度对文章内容、语言作出评价，理由充分合理； \\  
   & &  $\star$	能通过对信息的加工较好地完成指定的任务。 \\     
\cline{2-3}      

   &   \multirow{5}{*}{B}  &  $\star$	能根据要求从文本中提取出完整的信息； \\  
   & &  $\star$	能形成对文本的整体感知，但概括不全面； \\  
   & &  $\star$	能运用文本信息，尝试从多个角度对相关问题做出合理的解释； \\    
   & &  $\star$	能利用文本信息从多个角度对文章内容、语言作出评价，但利用信息不充分； \\  
   & &  $\star$	能通过对信息的加工完成指定的任务，但利用信息不充分。 \\  
\cline{2-3}

   &   \multirow{5}{*}{C}  & $\star$	能根据要求提取文本中的多处信息，但信息提取得不全面； \\  
   & &  $\star$	能形成对文本的感知，只能概括出部分文本内容； \\
   & &  $\star$	能从一个角度，充分运用文本信息，对相关问题做出解释，或能尝试从两个角度，对相关问题做出初步解释； \\  
   & &  $\star$	能利用文本信息对文章内容、语言作出评价，但仅能从一个角度支持自己的观点，利用信息不充分； \\  
   & &  $\star$	能通过对信息的加工完成部分指定的任务，但利用信息不充分。 \\  
\cline{2-3}

   &   \multirow{5}{*}{D}  & $\star$	不能根据要求提取文本中的信息，或只能提取文本中明显的、直接陈述的单一信息； \\  
   & &  $\star$	不能形成对文本的感知，或错误概括文本内容；  \\
   & &  $\star$	不能运用文本信息对相关问题做出解释，或只能初步运用文本信息从单一角度对相关问题做出解释； \\  
   & &  $\star$	不能做出评价，或只能做出评价，但不能利用信息说明自己的观点； \\  
   & &  $\star$	不能完成指定的任务，或只能根据任务选择相关的信息。 \\  
\hline

   \multirow{12}{*}{写作}  & \multirow{3}{*}{A}  & $\star$	能表达自己的真情实感，选材新颖，立意鲜明；  \\  
   & &  $\star$	语言流畅，简洁得体，富有表现力； \\    
   & &  $\star$	构思巧妙，能根据表达的需要恰当地安排详略。 \\    
\cline{2-3}      

   &   \multirow{3}{*}{B}  &  $\star$	能根据题目要求恰当选择材料，内容具体，中心明确； \\  
   & & $\star$ 语句通顺； \\  
   & & $\star$ 文章结构完整，能注意详略安排。 \\    
\cline{2-3}

   &   \multirow{3}{*}{C}  &  $\star$	能根据题目的要求选择材料，内容不够充实，中心基本明确； \\  
   & &  $\star$	语句基本通顺；  \\  
   & &  $\star$	结构基本完整，但缺少详略安排。 \\
\cline{2-3}

   &   \multirow{3}{*}{D}  & $\star$	不能根据题目的要求选择材料；或内容过于简单；或中心不够明确 \\  
   & &  $\star$	语句不通顺，错别字较多，标点符号使用不规范； \\  
   & &  $\star$	文章结构不完整；或结构混乱，没有条理。 \\
\hline

\end{longtable}
\end{itshape}


<!-- end of chapter description -->
