<!-- chapter total -->

\mytext

# 学生总体表现

## 本区全体学生的总体表现


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.cn.score.segment")`}九年级学生语文学科得分分布。

plot.bar.district.cn.score.segment

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.cn.rank.total.region")`}九年级学生在语文学科各水平上的人数比例。

plot.bar.district.cn.rank.total.region


## 不同群体学生的总体表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.cn.rank.total.perspective")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.district.cn.quantile.perspective")`}分别给出了不同群体学生在语文学科各水平上的人数比例和得分分布。

plot.bar.district.cn.rank.total.perspective
plot.box.district.cn.quantile.perspective

\mylist
注：盒须图——5\%学生得分小于等于须下限分数；25\%学生得分小于等于盒底分数；50\%学生得分大于等于盒中横线分数；25\%学生得分大于等于盒顶分数；5\%学生得分大于等于须上限分数；盒高度一定程度上反映了得分分布的离散程度；红点为平均分。
\mytext

## 不同学校学生的总体表现

图\ref{fig: `r gio.R$GetPlotTitle("multiplot.bar.district.cn.score.rank.school")`}和图\ref{fig: `r gio.R$GetPlotTitle("multiplot.box.district.cn.score.quantile.school")`}分别给出了不同学校学生在语文学科各水平上的人数比例和得分分布。

multiplot.bar.district.cn.score.rank.school
multiplot.box.district.cn.score.quantile.school



<!-- end of chapter total -->
