<!-- chapter dimention -->

\mytext

# 学生在各能力维度上的表现情况

## 全体学生在各能力维度上的表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.cn.dimention.rank")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.district.cn.dimention.quantile")`}分别给出了学生在语文学科各能力维度各水平上的人数比例和得分分布。

plot.bar.district.cn.dimention.rank
plot.box.district.cn.dimention.quantile


## 学生在各能力维度上的表现

### 积累

#### 不同群体学生的表现

plot.bar.district.cn.jilei.rank.perspective
plot.box.district.cn.jilei.quantile.perspective

#### 各学校学生的表现

multiplot.bar.district.cn.jilei.rank.school
multiplot.box.district.cn.jilei.quantile.school

### 阅读

#### 不同群体学生的表现

plot.bar.district.cn.reading.rank.perspective
plot.box.district.cn.reading.quantile.perspective


#### 各学校学生的表现


multiplot.bar.district.cn.reading.rank.school
multiplot.box.district.cn.reading.quantile.school

###  写作

#### 不同群体学生的表现

plot.bar.district.cn.writing.rank.perspective
plot.box.district.cn.writing.quantile.perspective

#### 各学校学生的表现

multiplot.bar.district.cn.writing.rank.school
multiplot.box.district.cn.writing.quantile.school


<!-- end of chapter dimention -->
