---
documentclass: book
fontsize: 10pt
geometry: margin=1in
output:
  pdf_document:
    fig_caption: yes
    template: pdf_template.tex
    includes:
      in_header: header_base.tex
    latex_engine: xelatex
    number_sections: yes
    keep_tex: no
params:
  report: 2015
  dummy.fig: "reports.jpg"
  
---
<!-- global setting -->

\graphicspath{ {`r report$plot.out`} }

<!-- cover page -->

\pagenumbering{gobble}
&nbsp;

\vspace{40mm}
\mytitle{`r report$year``r report$scope``r report$project`}
\mytitle{`r report$report`}
\mysubtitle{`r report$subject`}

\vfill
\myproducer{`r report$producer`}
\myproducer{`r report$producer1`}
\myproducer{`r report$date`}

\vspace{8mm}
\mycopyright{`r report$copyright`}

\clearpage

<!-- end of cover page -->

\pagenumbering{arabic}
\pagestyle{fancy}\fancyhf{}
\fancyhead[LE,RO]{\footnotesize `r report$header`}
\fancyfoot[C]{\footnotesize \thepage}

<!-- interface -->

\myprefacetitle{前~言}
\myprefacetext

教育质量是衡量一个国家、地区基础教育发展水平最重要的指标，学生学业质量是教育质量的重要组成部分。以学生学业质量的评价为切入口，全面关注学生的健康成长，引导建立正确的质量观，建立教育质量的保障体系，对于促进基础教育的均衡发展，实现教育公平有着重大作用。教育质量的形成涉及诸多关键环节，除外部的支持保障条件外，提升质量首先应关注教学过程。但是，长期存在的以片面追求升学率为导向的教学、考试，偏离了课程改革的方向和课程标准的基本要求，考试命题过多依赖个人经验，缺乏对教育测量学的深入研究；考试结果用于排名、甄别和选拔，加剧了竞争。在此压力下，中小学生很难有发自内心的求知欲，很难有对学校的归属感。过重的学习压力，不仅使学生的睡眠时间得不到保证，近视率不断增长，而且导致学生产生焦虑，严重地影响体质健康。正如欧盟《学生学业成绩分析报告》中所指出的“尽管较强的竞争性可能会在学习成绩上带来收益，但在学生的动机和心理健康方面却会付出代价。这些代价从长远来看会有一些不可预见的负面影响，如对学生的终身学习”。

2010年，上海市教育委员会承担了国家教育体制改革试点项目《改革义务教育教学质量综合评价办法》。2011年，上海市教育委员会在与教育部基础教育课程教材发展中心进行前期合作的基础上，共同研究、提炼出了一系列影响学生学业质量的关键因素，如学习动力、师生关系、学习负担等，构建了以关注学生健康成长为核心价值追求的上海市中小学学业质量绿色指标（以下简称“绿色指标”）。“绿色指标”分为学生学业水平指数、学生学习动力指数、学生学业负担指数、师生关系指数、教师教学方式指数、校长课程领导力指数、学生社会经济背景与学业成绩相关指数、学生品德行为指数、学生体质健康指数、跨年度进步指数等。2011年、2012年，依据“绿色指标”，上海组织了两轮学业质量综合评价，产生了积极广泛的影响，成为上海基础教育转型发展的一个亮点，并被教育部向全国推广。2014年，上海的“绿色指标”综合评价工作进入了全面自主化的新阶段，建立了“指标确立—工具研发—数据分析—报告撰写—反馈改进”的评价操作路径；形成了“检测依靠技术、结论源自证据、分析产生转变”教学实证研究模式。“绿色指标”综合评价改革是一个不断完善的行动改进实践过程，近年来，上海各区、校通过评价指标解读、综合评价实施、评价报告发布、基于评价结果进行教育教学改进等工作，同时，也进一步探索和完善了“绿色指标”综合评价。2017年7月，在吸收和总结多年来“绿色指标”评价实践经验和理论研究成果的基础上，上海市教委教研室正在探索与修订“绿色指标”2.0版本，旨在通过更加合事实、合逻辑、合规范、合目的评价将基于评价结果的改进落实到学校、学生、教师行为改进上，推进“为了评价的教学”走向“为了教学的评价”。学业质量的“绿色指标”，并不是全面衡量教育质量的完整指标体系，而是针对当前时弊提出的，直接指向学生健康成长的关键因素，该指标在使用过程中将不断地得到发展和完善。“绿色指标”体系的推行将为各级教育行政部门、教研部门和学校了解学生学业质量的基本状况和重要影响因素，提供实证的依据；为教育决策提供重要参考；为提升学生学业质量提供诊断和改进建议；从而引导全社会树立正确的质量观，促进学生的健康成长！

\clearpage

<!-- end of interface -->

<!-- table of cntents -->

\centering\normalsize\setcounter{tocdepth}{2}\tableofcontents 
\raggedright\large\setlength{\parindent}{2em}
\clearpage

<!--  end of toc -->

<!-- document body -->

# 学业质量绿色指标测试的实施概况


根据本市中小学教育质量综合评价改革的要求，上海市教育委员会组织成立了上海市中小学学业质量绿色指标综合评价项目组（以下简称“项目组”），按照《上海市教育委员会关于做好2016年度上海市中小学学业质量绿色指标综合评价工作的通知》(沪教委基[2016]61号)的文件要求，组织了2016年度小学学业质量绿色指标测试，测试对象为在上海市普通中小学校就读的四年级学生，采用学科测试和问卷调查收集数据。项目组在评价队伍的建设、测试工具的研发、考务的组织与实施、评分标准的研制和阅卷、学业水平标准设定等方面开展了相关工作，以下是项目实施的概况。


## 测试概况


### 测试对象


2016年，全市16个区均抽样参加了“绿色指标”测试。普通民办学校自愿参加，所有公办小学全部参加本次调查。每一所参加调查的学校是根据其学校规模按照随机等距抽样的方式抽取一定数量的样本学生。

本次共有904所小学68022名四年级学生参加了学科测试和问卷调查,其中每名学生参加语文和数学两门学科的测试。6240位教师、1593位校长（含分管教学的副校长）、66347位学生家长分别参加了教师问卷、校长问卷及家长问卷的调查。


### 学科测试内容

`r tab_name <- "中小学生学业质量测试科目及测试框架"`

本次四年级测试涉及语文、数学两门学科。各学科测试的内容不仅包括学生在基础知识、基本技能方面所达到的水平，而且还包括时代发展所要求的小学生需具备的搜集处理信息、自主获取知识、分析与解决问题、交流与合作、创新精神与实践能力等核心素养。本次测试的学科测试框架见表\ref{tab: `r tab_name`}。

\begin{table}[h!]
\centering
\caption{`r tab_name`} \label{tab: `r tab_name`} 
\itshape
\footnotesize
\begin{tabularx}{\textwidth}{|c|l|X|}

\hline

  & \makecell[c]{\normalsize 内容} & \makecell[c]{\normalsize 能力} \\
\hline

 \multirow{9}{3cm}{\makecell[cc]{语文}} & \multirow{3}{3cm}{积累} & 掌握已学过的常用汉字 \\
 & & 具有独立识字的能力 \\
 & & 积累古诗 \\
\cline{2-3}

 & \multirow{2}{3cm}{阅读} & 初步具有现代文阅读能力 \\
 & & 具备基本的语文积累和综合运用能力 \\
\cline{2-3}

 & \multirow{3}{3cm}{\makecell[cl]{习作}} & 能根据写作要求选材立意 \\
 & & 能根据表达的需要合理安排文章结构 \\
 & & 能文从字顺地表达自己的意思 \\
 & & 能正确、规范、端正地书写汉字 \\

\hline
\multirow{4}{3cm}{\makecell[cc]{数学}} & \multirow{4}{3cm}{\makecell[cl]{数与运算\\ 图形与几何\\ 统计与概率}} & 知识技能 \\
 & & 数学理解 \\
 & & 运用规则 \\
 & & 问题解决 \\
\hline

\end{tabularx}
\end{table}



### 问卷调查内容


本项目使用学生、教师、校长、家长问卷了解学生学习、教师专业发展、学校发展状况、家长对学校教育的感受状况及影响学生学业水平的相关因素。学生问卷调查的内容包括学生基本情况、学校环境、学习压力、师生关系、学习动机、自信心和学习方式等。


教师问卷调查的内容包括教师基本情况如学历、任职经历、职称、工作感受情况、教师对学校教学管理的评价、教学观念和教师专业发展需求与困难等。校长问卷调查的内容包括校长及学校基本情况、校长课程领导力、办学自主权、国家课程开设情况和对教师的专业支持等。家长问卷调查的内容包括亲子关系、对学校教育的感受等。


## 工作流程


### 测试工具开发


以绿色指标测试的学科（包括背景问卷）为单位，组织了一支由市、区教研员、一线优秀教师组成的命题队伍。项目组负责把握命题的方向与总体框架，对命题过程进行管理与监督，保证试题的质量。

根据本次测试的目标和任务，确定了以下命题原则：第一，命题基于课程标准，体现课程标准的基本要求和理念。试题注重考查学生对学科核心知识、技能的理解和掌握，尤其是学生综合运用所学知识解决实际问题的能力、收集与分析信息的能力以及对重要学科思想方法的理解与掌握。第二，命题严格控制试卷的总体难度，组卷以体现课程标准对学生基本要求的题目为主，有难度的题目主要考查学生的高层次思维能力。第三，试题形式为客观性试题和主观性试题相结合。试题多使用真实的情境和任务，注重通过客观性试题考察学生高层次思维能力。`r tab_name <- "学科测试工具的研发过程" `

本项目采用规范、严谨的程序开展试题编制工作，以下是2016年度命题工作的过程及时间安排（见表\ref{tab: `r tab_name`}）。




\begin{itshape}
\begin{longtable}{m{12cm}m{3cm}}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\

\hline

\multicolumn{1}{c}{\multirow{2}{*}{\large 测试工具的研发}} & \large 时间节点 \\
  & \large (2016年) \\
  
\hline

绿色指标总项目组正式启动测试工具的研发工作 & 5月30日 \\各学科命题组学习、研讨各学科测试框架，依据往年测试情况和2016年度工作需要开展命题和组卷工作   & 6月1-30日 \\各学科命题组依据测试框架研制出四套试卷 & 6月30日前 \\召开第一次专家审议会议，依据预测试数据分析结果及专家评审意见，对试卷进行审核和筛选，组成三套试卷 & 7月3-4日 \\召开第二次专家审议会议，各学科命题组对试题试卷进行调整及修订 & 8月8-10日 \\召开第三次专家审议会议，对各学科测试卷和背景问卷进行评审，各学科命题组根据评审意见对试题进行修订及优化 & 9月2-3日 \\召开第四次专家审议会议，各学科命题组依据评审结果对试题进行优化及适应性调整，最终确定正式卷和备用卷，制作答题卡 & 10月7-10日 \\

\hline

\end{longtable}
\end{itshape}



### 施测


项目组编制了《2016年上海市中小学学业质量绿色指标综合评价实施手册》。上海市教委教研室、市教育督导部门等根据考务工作细则组织开展相关工作，包括编制培训手册，逐级对考务人员及管理人员进行培训，编制考生名册，制定详细的考务手册，组织具体的考务管理工作等。整个测试过程按照标准的考试进行管理，包括培训、考场设置、监考等环节。其中，所有参加测试学生名单在测试当天公布，参测学校负责人签订测试责任书。


### 评分标准研制


本次测试的非选择题均由人工批阅，因此评分标准的准确、全面和可操作性极其重要。在项目组的统一安排下，评分标准的研制由各学科命题组承担。在正式阅卷开始之前，各学科分别随机抽取适量份数，采取网上阅卷的方式，依据初步的评分标准对抽取到的学生作答进行评分。学科组经过反复讨论，修订、细化评分标准，最终形成评分标准。


### 阅卷


组建了由学科命题组成员、各区学科教研员及一线优秀教师组成的阅卷队伍。各学科命题组长担任阅卷组长，负责对阅卷人员进行培训和管理。整体阅卷工作原则上参照高考的相应要求组织实施，开放性试卷的评阅严格遵循国际上大型测试项目评卷标准进行，阅卷人员由具有较强责任心，丰富教学经验，相应职称水平，有大型测试阅卷工作经验的人员组成。阅卷组长对阅卷人员进行的培训分为两部分，一是对新研制的评分标准进行培训，让阅卷员准确掌握自己需要评阅题目的评分要求；二是针对如何使用网络阅卷程序进行技术培训。阅卷中采取的质量控制方式包括以下举措：- 在计算机阅卷系统中预设各题目的给分范围，由计算机自动判断评分是否超出范围，及时给予提醒，极大地降低了出错的可能性。- 控制工作时间和工作进度，避免阅卷员由于阅卷速度过快或疲劳降低评分准确性。- 阅卷组长对评分过程中出现的分歧组织讨论、统一认识和做法并对最终结果进行认定。- 部分主观题采取多人共评，个体独立阅卷的方式，多人评分的平均值作为最终得分；当评分差值超过预先设定的阈值，由阅卷组长根据答卷情况对结果进行仲裁。- 各学科阅卷组设质量监督员，全程关注由计算机生成的评分信息，包括评分一致性、阅卷工作进度、重评率等，发现异常现象及时通知相关阅卷人员。发现异常现象及时通知相关阅卷人员。


### 测试数据的录入、整理


学科测试卷采取填涂答题卡的方式，其录入由机器扫描完成。扫描答题卡时，计算机会根据预设条件对数据进行自动检测和判断，在这个过程中由专人进行全程监督，发现异常现象或错误数据立即进行纠正。

数据分析组根据一定的准则对数据进行清理，剔除空白卷、缺考卷、无考号卷的作答信息。若某份试卷的客观题作答信息全部为空或者主观题全部没有作答，并且经核查不是漏扫或漏评的视为无效作答。


本次背景问卷的信息反馈采用网络作答形式，学生、教师、校长及家长可用电脑或手机，在规定时间段内登录相应网址进行填写，提高了问卷调查的便捷性和数据采集的准确性。


### 学业水平标准设定


项目组邀请国际知名专家香港中文大学原副校长侯杰泰教授和美国ETS（美国教育考试服务中心）测量专家钱家和博士主持开展“学业水平标准设定”工作。各学科的专家评委由课程标准编制者、教材主编、区教研员、不同区域不同教龄的一线教师、学生家长等16人组成，采用Angoff和Bookmark的方法共同研讨和确定了上海地区相关学科的及格、良好和优秀的标准。

数据分析组对本次“绿色指标”测试结果进行了整理和分析，研讨了数据处理与等值方案，划定了2016年度上海市小学两门学科的学业水平。学业水平的划分结果采用A、B、C三个水平进行表述，其中A水平为最高等级，C水平为最低等级。


### 数据分析与报告撰写


本项目在测试数据分析的过程中，将经典测量理论与项目反应理论等先进测量技术相结合，对数据进行充分的分析，保证了测试结果分析的科学性。在此基础上，本次测试中所有的学科测试结果都采用量尺分数。量尺分数是根据学生的作答情况，采用项目反应理论模型将学生能力分数转换成的测验标准分数，它具有不受测验题目差异和测验难度影响的特点，同时能与本项目前几年的测试结果进行比较。小学各学科整体上的平均分在500分左右，标准差在100左右，在各学科的各个维度上的平均分在300分左右，标准差在50左右。

经过绿色指标项目组的充分研讨，确定了反馈报告的整体撰写框架，各学科命题组长分别对各学科测试的结果进行了分析并对学生在典型试题上的表现进行了评价。问卷部分呈现了学生、教师、校长及家长的基本情况并分析了学生学业成绩与有关背景变量的关系。


### 系列报告构成

`r tab_name <- "测试报告的构成" `


本次系列报告主要由三种层次共计5种报告9个类型构成。报告充分考虑到不同使用者对于报告内容要求不同的问题，依此将报告划分综合报告和学科报告，具体见表\ref{tab: `r tab_name`}。


\begin{table}[H]
\centering
\caption{`r tab_name`} \label{tab: `r tab_name`} 

\itshape

\begin{tabularx}{\textwidth}{|r|c|c|c|X|}

\hline
 \multicolumn{1}{|c|}{\multirow{2}{*}{\large 名称}}  &  \multicolumn{3}{c|}{\large 报告层次} &  \multicolumn{1}{c|}{\multirow{2}{*}{\large 对象}}\\ 
\cline{2-4}
               &   市级  & 区县 & 学校 &  \\             
\hline 
绿色指标基础数据报告 & √  & √ & & \multirow{2}{*}{教育决策者、教科研人员等} \\
\cline{1-4}
绿色指标指数报告 & √  & √ & &  \\ 
\hline 
绿色指标学校报告 &   &  & √ & 校长、教师等 \\ 
\hline 
小学语文学科报告 & √  & √ & & \multirow{2}{*}{学科教研员、教师等} \\
\cline{1-4}
小学数学学科报告 & √  & √ & &  \\
\hline 
\end{tabularx}
\end{table}

\clearpage

<!--  end of section 1. -->

# 学科测试说明## 四年级语文学科测试简介2016年度上海市中小学学业质量绿色指标语文学科测试依据学科测试框架在内容领域和考查维度两方面来考查学生语文方面的学业水平。

语文学科测试在内容领域上分为积累、阅读和习作三个维度。其中在积累这一内容领域里，主要从学生读准字音、认清字形、理解词义、积累和运用常见古诗文等四个方面的能力维度，测评和分析学生的学业表现。阅读主要考察学生提取信息、形成解释、整体感知和解决问题等四个方面。习作主要从选择材料、组织材料、语言表达和书写及标点等四个方面对学生的习作水平进行具体分析。语文学科测试的考查维度则依据《上海市中小学语文课程标准》、国际同类测试的惯例和国内课程实施现状，从知识和能力、过程和方法、情感态度和价值观三个维度全面考查学生的语文素养。对这三个维度的考查，可以反映出学生对语文基础知识和基本技能的掌握情，以及语言文字的综合运用能力，同时关注学生在语文学习过程中的感悟、体验和审美活动，体现语文学科工具性和人文性统一的基本特性。## 四年级语文学业水平描述四年级语文测试主要从“积累”、“阅读”和“习作”三个方面考查学生的语文学业水平。

表1-1对八年级学生在语文学科不同考查能力上的表现分水平进行了学业水平描述。表1-1 四年级学生语文学科学业水平描述考查能力水水平水 平 描 述                积累AA★	能够理解常用词语、成语的基本意思，并分辨词义间的细微差别；★	能够借助语感在较复杂的语境中恰当运用词语、成语。不B★	能够读准常用字中同年级学生易错字字音；★	能够识记常用字中同年级学生易错字字形；★	能正确理解常用词语的基本意思，并在语境中恰当运用；★	能正确记忆和理解学过的教材中的古诗。才C★	不能正确分辨易错字字音；或只能利用汉语拼音读出所学过的部分常用字字音；★	不能分辨易错字字形；或只能认清所学过的部分常用字字形；★	不能在语境中恰当运用词语、成语；或只能理解所学过的部分常用词语、成语的基本意思；★	不能正确理解古诗文的内容，不能根据上下句的提示准确记忆学过的教材中的古诗。阅读啊A★	能够综合利用文本的信息并联系个人经验从多个角度对问题做出合理的解释。不B★	能够根据要求从文本中提取出相关信息并进行简单的比较或概括；★	能够通过对相关信息的简单加工对问题做出解释；★	能够完整感知文本的主要内容。才C★	不能对所提取的信息做出加工；或只能从一个文段中提取直接陈述的信息,利用直接提取的信息进行解释；★	不能完整感知文本的主要内容。习作啊A★	能够根据给定的情境叙述一件事情或介绍一种事物，想象有新意，内容丰满；★	能够合理、巧妙安排故事内容；★	语句通顺，描写生动，标点正确。不B★	能够根据给定的情境叙述一件事情或介绍一种事物，结构基本完整；★	能较清楚地表达自己的意思，语言较为通顺；★	有个别错别字，标点符号使用基本正确。才C★	不能够根据给定的情境作文；或能够根据给定的情境作文，但结构不完整；或内容过于简单；★	不能清楚地表达自己的意思；★	错别字较多，标点符号使用不规范。# 学生总体表现## 全体学生的总体表现图 3-1 和图 3-2 分别给出了上海市全体学生及不同区域学生在语文学科各水平上的人数比例和得分分布。图3-1 全体学生在语文学科各水平上的人数比例图3-2全体学生在语文学科上的得分分布## 不同群体学生的总体表现图3-3和图3-4分别给出了上海市不同群体学生在语文学科各水平上的人数比例和得分分布。 图3-3 不同群体学生在语文学科各水平上的人数比例图3-4 不同群体学生在语文学科上的得分分布不同区学生的总体表现图3-5和图3-6分别给出了上海市不同区（县）学生在语文学科各水平上的人数比例和得分分布。图3-5 不同区学生在语文学科各水平上的人数比例图3-6 不同区学生在语文学科上的得分分布# 学生在各能力维度上的表现情况## 全体学生在各能力维度上的表现图4-1和图4-2分别给出了上海市学生在语文学科各能力维度各水平上的人数比例和得分分布。图4-1 学生在语文学科各能力维度各水平上的人数比例图4-2 学生在语文学科各能力维度上的得分分布二、学生在各能力维度上的表现### 积累#### 不同群体学生的表现图4-3 不同群体学生在“积累”各水平上的人数比例图4-4 不同群体学生在“积累”上的得分分布
#### 不同区学生的表现图4-5 不同区学生在“积累”各水平上的人数比例图4-6 不同区学生在“积累”上的得分分布### 阅读
#### 不同群体学生的表现图4-7 不同群体学生在“阅读”各水平上的人数比例图4-8 不同群体学生在“阅读”上的得分分布#### 不同区学生的表现图4-9不同区学生在“阅读”各水平上的人数比例图4-10 不同区学生在“阅读”上的得分分布### 习作
#### 不同群体学生的表现图4-11 不同群体学生在“习作”各水平上的人数比例图4-12 不同群体学生在“习作”上的得分分布
#### 不同区学生的表现图4-13 不同区学生在“习作”各水平上的人数比例图4-14不同区学生在“习作”上的得分分布