<!-- chapter pressure  -->
\mytext

##  学生学业负担与压力指数

学业负担和压力指数从主观和客观两个方面对学生学业压力进行评估，包括学业负担和学业压力两个二级指数。

### 学业负担指数

学业负担指学生为完成课内和课外学习任务所付出的代价。该指标主要通过调查学生睡眠时间、做作业时间和补课时间等方面来反映学生所承受的学业负担的状况和程度。

已有的研究发现，学生做作业的时间越长，课外学习的时间越长，睡眠时间越短，学业负担感越重（王绯烨、刘方，2018；赵阳、薛海平，2018）  。父母受教育程度越高，家庭经济社会越好，学校质量越好，学生的睡眠时间状况越不理想，且两端学生的睡眠时间均低于中等水平的学生（赵阳、薛海平，2018 ）。

有关课外学习对学生的学习成绩会产生何种影响，已有的研究发现并不一致。一些研究发现课外学习对学习成绩有影响，另一些则发现课外学习没有对学习成绩产生显著影响。一些研究发现课外学习会正向预测学习成绩，而另一些则发现课外学习会负向影响学习成绩（薛海平, 宋海生，2018） 。此外，不同学科的课外学习之间也会有相互影响。数学学科的补习对数学成绩有正向影响作用，数学和科学学科的补习会产生“叠加效应”，而语言类的补习则会和数学补习产生“挤出效应”（胡咏梅等人，2015） 。

学生课外学学习时间的多少受家庭、学校、社会等多方面因素的影响。过多的课外学习会对教师的课堂教学带来难度，并加剧教育不公平（王晓磊，2017） 。一些研究者因此建议学校提供必要的，平等的课外辅导（胡咏梅等人，2015） ，并通过提高教学效能，避免学生将过多的时间和精力花费在校外学习上（王绯烨、刘方，2018）。
 本项目通过调查学生的作业时间、睡眠时间、考试学科相关校外补课时间了解学生的学业负担，通过问卷收集数据，并对数据进行统计分析得到的结果。

学生学业负担指数分为9级，指数越高，表示该群体学生学业负担越轻。

\mylist

- 9级：表示学业负担适中与较轻\footnote{我们将以下三个条件满足两个的学生界定为学业负担适中与较轻的学生：1、睡眠时间在7小时以上；2、做作业时间在2小时以下；3、每周参加与考试学科的补课在4小时以下。
}的学生所占比例在90%以上（含90%）
- 8级：表示学业负担适中与较轻的学生所占比例在80%-90%之间（含80%）
- 7级：表示学业负担适中与较轻的学生所占比例在70%-80%之间（含70%）
- 6级：表示学业负担适中与较轻的学生所占比例在60%-70%之间（含60%）
- 5级：表示学业负担适中与较轻的学生所占比例在50%-60%之间（含50%）
- 4级：表示学业负担适中与较轻的学生所占比例在40%-50%之间（含40%）
- 3级：表示学业负担适中与较轻的学生所占比例在30%-40%之间（含30%）
- 2级：表示学业负担适中与较轻的学生所占比例在20%-30%之间（含20%）
- 1级：表示学业负担适中与较轻的学生所占比例在20%以下

\mytext

plot.bar.school.index.burden


### 学业负担分项指标

#### 睡眠指数

参照相关政策文件，以九年级每天睡眠时间保证8 小时以上为参照，将睡眠指数划分为9 级，指数越高，表示睡眠时间得到保障的学生比例越高。

\mylist

- 9级：表示90%以上的学生睡眠时间得到基本保障（含90%）
- 8级：表示80%-90%的学生睡眠时间得到基本保障（含80%）
- 7级：表示70%-80%的学生睡眠时间得到基本保障（含70%）
- 6级：表示60%-70%的学生睡眠时间得到基本保障（含60%）
- 5级：表示50%-60%的学生睡眠时间得到基本保障（含50%）
- 4级：表示40%-50%的学生睡眠时间得到基本保障（含40%）
- 3级：表示30%-40%的学生睡眠时间得到基本保障（含30%）
- 2级：表示20%-30%的学生睡眠时间得到基本保障（含20%）
- 1级：表示20%以下的学生睡眠时间得到基本保障

\mytext

plot.bar.school.index.sleep


#### 作业指数

参照有关文件和相关研究成果，九年级学生每天做作业时间2 小时以下为宜。以此为参照，将作业时间指数划分为9 级，指数越高，表示作业量适宜的学生比例越高。

\mylist

- 9级：表示90%以上的学生作业量适宜（含90%）
- 8级：表示80%-90%的学生作业量适宜（含80%）
- 7级：表示70%-80%的学生作业量适宜（含70%）
- 6级：表示60%-70%的学生作业量适宜（含60%）
- 5级：表示50%-60%的学生作业量适宜（含50%）
- 4级：表示40%-50%的学生作业量适宜（含40%）
- 3级：表示30%-40%的学生作业量适宜（含30%）
- 2级：表示20%-30%的学生作业量适宜（含20%）
- 1级：表示20%以下的学生作业量适宜

\mytext

plot.bar.school.index.homework


#### 补课指数（校外）

校外补课指数分为9 级，指数越高，表示每周参加与考试学科相关的校外补课2小时以下的学生比例越高。

\mylist

- 9级：表示90%以上的学生每周参加与考试学科相关的校外补课2小时以下（含90%）
- 8级：表示80%-90%的学生每周参加与考试学科相关的校外补课2小时以下（含80%）
- 7级：表示70%-80%的学生每周参加与考试学科相关的校外补课2小时以下（含70%）
- 6级：表示60%-70%的学生每周参加与考试学科相关的校外补课2小时以下（含60%）
- 5级：表示50%-60%的学生每周参加与考试学科相关的校外补课2小时以下（含50%）
- 4级：表示40%-50%的学生每周参加与考试学科相关的校外补课2小时以下（含40%）
- 3级：表示30%-40%的学生每周参加与考试学科相关的校外补课2小时以下（含30%）
- 2级：表示20%-30%的学生每周参加与考试学科相关的校外补课2小时以下（含20%）
- 1级：表示20%以下的学生每周参加与考试学科相关的校外补课2小时以下

\mytext

plot.bar.school.index.buke


### 学习压力指数

学业压力指当环境要求超出学生自身应对能力时学生的主观感受。主要调查学生在学习过程中产生的心理负担、焦虑等消极的情绪体验，通过询问学生在做作业、考试、课堂提问、成果反馈等情境中的心理状态进行考察。

已有的研究认为，适度的压力水平有利于学生成绩的提高，而过重或过轻的压力水平都不利于学生成长（野晓航， 2003；杨亚威等人，2017）  。学习压力过大,可能会导致学生注意力分散、缺乏毅力与恒心、耐挫性低，甚至引起学生心理和生理上的不良反应（郑林科等人，2001） 。

研究者认为，升学考试、父母期望等、社会环境、学习内容都可能会增加学生的学习压力，而课堂效率不高则是深层次的原因（龙安邦等人，2013；路海东，2008）。研究表明，良好的教学效能（教学环境、教学认知）可以较大程度地减轻学生的学习压力。这表明良好的师生关系、师师关系和生生关系对减轻学生的学习压力有显著效果。相比政治、英语、语文学科，生物、数学、物理学科能更大地调节教学效能对学习压力的影响（刘姣，朱娅梅，2018）。

本项目通过调查学生对待考试、成绩的反应等问题了解学生的学习压力，通过问卷收集数据，并对数据进行统计分析得到的结果。


学习压力指数分为9级，指数越高，表示该群体学生学习压力越小。

\mylist

- 9级：表示学习压力较小\footnote{我们将得分超过本维度总分60\%界定为学习压力较小。}的学生所占比例在90%以上（含90%）
- 8级：表示学习压力较小的学生所占比例在80%-90%之间（含80%）
- 7级：表示学习压力较小的学生所占比例在70%-80%之间（含70%）
- 6级：表示学习压力较小的学生所占比例在60%-70%之间（含60%）
- 5级：表示学习压力较小的学生所占比例在50%-60%之间（含50%）
- 4级：表示学习压力较小的学生所占比例在40%-50%之间（含40%）
- 3级：表示学习压力较小的学生所占比例在30%-40%之间（含30%）
- 2级：表示学习压力较小的学生所占比例在20%-30%之间（含20%）
- 1级：表示学习压力较小的学生所占比例在20%以下

\mytext

plot.bar.school.index.pressure


<!-- end of chapter pressure  -->
