<!-- chapter description -->
\mytext

## 科学学业水平描述


科学知识维度具体包括:知道基本的科学知识（包括事实、概念、原理和观念）；知道基础实践的操作步骤、现象和基本方法；初步运用科学基础知识（解释身边一些常见的自然现象）。

科学能力维度具体包括：问题与假设：能依据给定的问题、或能提出问题、或能界定问题；制订方案：针对问题，确定若干科学实践活动要素，并顺序化对方案作解释与评价；从文字、图、表等中读取有效信息；处理和描述信息；将获取的信息和已有知识建立关联；对现象或事实进行分析和判断；用科学专用术语或图、表准确表达思维过程。

科学态度维度具体包括：有探索科学的兴趣，认同科学、文明、健康的生活方式；关注节约资源和保护环境、关注STS；对想的、或做的、或决策进行评价。


`r tab_name <- "科学学科学业水平描述" `

\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\  

\hline
考查维度 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{12}{*}{科学知识} & \multirow{3}{*}{A} & $\star$ 能对常见的科学事实、现象、科学过程做出描述；  \\  
 & & $\star$ 能在新情境中，正确辨认其中所含的基本科学事实和观念,寻找、发现和使用科学概念和原理； \\  
 & & $\star$ 能把握知识的内在逻辑关系，并在问题情境中简单地运用。 \\  \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 能说出常见的科学事实、术语或概念；\\
 & & $\star$ 能在熟悉的情境中，正确辨认其中所含的基本科学事实和观念，使用科学概念和原理； \\
 & & $\star$ 能把握知识之间的联系。 \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能回忆和再认基本的科学知识；\\
 & & $\star$ 能识别常见的科学现象，能辨认事实或证据； \\
 & & $\star$ 能描述常见的科学现象的基本特征。 \\ \cline{2-3}

 & \multirow{3}{*}{D} & $\star$ 不能回忆和再认基本的科学知识； \\
 & & $\star$ 不能识别常见的科学现象，不能辨认事实或证据； \\
 & & $\star$ 不能描述常见的科学现象的基本特征。\\ \hline

& \multirow{3}{*}{A} & $\star$ 能界定问题，确定若干科学实践活动具体方法的关键因素，或对上述具体方法进行总结和修正； \\
 & & $\star$ 能运用仪器的组合获取证据，或有针对地筛选所给情境中的相关信息；能进行系统的观察、比较和测量，数据准确；能综合运用不同的表达方式，清晰有效地得出结论、提出建议或作出决策； \\
 & & $\star$ 能在新情境中获取多种证据支持假设；能运用证据说明科学结论或解释生活和社会中的问题。 \\ \cline{2-3}

\multirow{9}{*}{科学能力}  & \multirow{3}{*}{B} & $\star$ 能提出问题，确定科学实践活动各要素的具体方法及上述要素和方法的顺序； \\
 & & $\star$ 能运用简单的仪器获取证据，或有选择地在所给情境中获取有关信息、检查观察是否客观；能运用文字、图表等进行表达；\\
 & & $\star$ 能用某一个适当的证据支持假设；能运用证据形成（归纳或猜测）科学结论。 \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能依据问题，确定若干科学实践活动的要素及其顺序; \\
 & & $\star$ 能运用感官及工具获取证据；能在所给情境中获取相关信息；能完成对实验现象的观察和比较；能运用文字进行表达；\\
 & & $\star$ 能辨别证据是否支持假设；能运用证据描述科学现象或概念。 \\  \cline{2-3}

 & \multirow{3}{*}{D} & $\star$ 不能从所给情境中发现问题，或无法正确依据问题确定常见的科学实践活动的要素，或错误判断要素； \\
 & & $\star$ 不能在所给资料中选择正确的证据，或证据关联度不大；不能在间接证据中获取或记录有效信息；不能清晰表达和交流； \\
 & & $\star$ 证据与假设之间的关联不明确，无法正确判断或描述科学概念。 \\ \hline

\multirow{12}{*}{\makecell[c]{科学态度}} & \multirow{3}{*}{A} & $\star$ 在解决问题的过程中，表现出求实求真的精神； \\
 & & $\star$ 有实践科学文明的生活方式的行动习惯，有参与保护自然资源和环境的习惯； \\
 & & $\star$ 乐于参与社会有关的科学决策，并表现出创新意识。 \\ \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 有参与求实求真实践的意愿； \\
 & & $\star$ 有实践科学文明的生活方式的意愿，有参与保护自然资源和环境的意愿； \\
 & & $\star$ 有参与社会有关的科学决策的意愿。 \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 认同求实求真的做法；\\
 & & $\star$ 赞同科学文明的生活方式，有保护自然资源和环境的意识； \\
 & & $\star$ 对与社会有关的科学决策表示出关心。\\ \cline{2-3}

 & \multirow{3}{*}{D} & $\star$ 不愿意参与科学实践活动，不在乎求实求真的做法； \\
 & & $\star$ 对科学文明的生活方式表现出无所谓，缺乏保护自然资源和环境意识； \\
 & & $\star$ 对与社会有关的科学决策不关心。 \\ \hline

\end{longtable}
\end{itshape}


<!-- end of chapter description -->
