<!-- chapter teacher  -->

\mytext

## 教师课程领导力指数

教师课程领导力指教师将课程意识与教学实践相融合，有效开展课堂教学活动的素质，主要包括教师教学理念、教师教学方式和教师学业评价能力三个二级指数。

plot.bar.school.index.teacher.leadership


### 教师教学理念指数

教学理念是一种关于教学实践的基本认识，一种主观信念，一种教学行为的驱动力量，是教学观念与教学理想的一种融合（彭钢，2002）。教师教学理念代表着教师对教学的观点和看法，以及在此基础上形成的相对稳定的思想和观念体系，反映了教师对教学实践的价值追求。教师教学理念主要包括知识观、教学观、学生观等方面。

实证研究表明，不同教学理念的教师，在多个相关指标中均存在显著差异（杨帆,许庆豫，2015）。有学者认为，教学理念一旦内化为教师的信念，便可以为教学行为的转化提供理论导向和动力支持（段作章，2013）。教学理念影响着教师如何看待教学目标、选择教学方法，影响着教师的教学行为和专业发展，影响着教师与学生的相处模式。所以，教师教学理念的转变和提高是提升教育质量的重要任务之一。

本监测中对教师教学理念的测量，主要是通过问卷调查的方式，了解教师对教学方式、学习过程、教师角色、课堂互动等方面的认知。通过采集教师问卷数据，进行数据分析得到结果。


教师教学理念指数分为9级，指数越高，表示学生对教师教学方式的评价越高。

\mylist

- 9级：表示90%以上的教师教学理念指数较好\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的教师教学理念指数较好（含80%）
- 7级：表示70%-80%的教师教学理念指数较好（含70%）
- 6级：表示60%-70%的教师教学理念指数较好（含60%）
- 5级：表示50%-60%的教师教学理念指数较好（含50%）
- 4级：表示40%-50%的教师教学理念指数较好（含40%）
- 3级：表示30%-40%的教师教学理念指数较好（含30%）
- 2级：表示20%-30%的教师教学理念指数较好（含20%）
- 1级：表示20%以下的教师教学理念指数较好

\mytext


plot.bar.school.index.teaching.opinion

### 教师教学方式指数

教师的教学方式指教师为达到课程教学目标，在课堂教学过程中采取的途径、步骤、手段。教师教学方式既包括外显的行为，也包括内隐的思维方式（温恒福，2002），既包括观念性的方式，也包括观念性与物质性结合的方式，是教学方法、形式、手段等的综合（赵茜,王佳，2012）。

有学者认为，教师的教学方式对学生能力发展的影响结果可能产生正向平衡和不平衡与负向平衡和不平衡四种状态（郝文武，2007 思维方式（温恒福，2002 ），既包括观念性的方式，也包括观念性与物质性结合的方式，是教学方法、形式、手段等的综合（赵茜,王佳，2012）。选择合适的教学方式对学生能力和素养的发展是十分重要的。学生核心素养的培养离不开教师教学方式的转变，而教师教学方式的转变不仅是外在行为的改变，而且是思维方式、思想观念的转变（张云丽,段兆兵，2017）。只有对教师的教学方式进行调研，依据学生的切实需要找出教学方式转变的切入点，才能为教师素质的提高和学生的发展提供支持。

本监测中对教师教学方式的测量，主要考察教师在课堂上运用自主、合作、探究等方式进行教学的频率、程度，以及学生对教师教学方式的满意度。通过采集学生、教师问卷数据进行统计分析，得到结果。

教师教学方式指数分为9级，指数越高，表示学生对教师教学方式的评价越高。

\mylist

- 9级：表示90%以上的学生对教师教学方式评价较高\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的学生对教师教学方式评价较高（含80%）
- 7级：表示70%-80%的学生对教师教学方式评价较高（含70%）
- 6级：表示60%-70%的学生对教师教学方式评价较高（含60%）
- 5级：表示50%-60%的学生对教师教学方式评价较高（含50%）
- 4级：表示40%-50%的学生对教师教学方式评价较高（含40%）
- 3级：表示30%-40%的学生对教师教学方式评价较高（含30%）
- 2级：表示20%-30%的学生对教师教学方式评价较高（含20%）
- 1级：表示20%以下的学生对教师教学方式评价较高

\mytext

plot.bar.school.index.teaching.method


### 教师学业评价能力指数

教师的学业评价能力是指教师运用测评知识和技能对学生进行施测，并能够分析测评结果，制定教学计划，作出行之有效的反馈，进一步引导学生学习的能力（张露露，2018）。教师的学业评价能力作为教师专业发展重要的组成部分而备受关注。

实证研究表明，教师评价影响学生的学业自我概念（academic self-concept）、学生的未来学业成就、成功期望（expectancy for success）和抱负水平（level of aspiration）。与知觉到的积极教师对待相比，知觉到的消极教师对待对学生的学业成果有更加广泛的中介效应（朱明婧，2015）。也有学者认为，教师在学业评级方面知识的欠缺将导致教育质量的削弱（Popham and James W，2009）。教师评价素养的缺乏甚至会直接影响到课程改革的成败，影响到国家基础教育的质量（崔允漷，2018）。在这样的背景下，教师的评价素养成为了亟须培育的内容，也是当今世界各国的教师专业标准的重要组成部分。

本项目中对教师的学业评价能力的测量，主要考察教师确定评价目标、设计评价工具、分析评价结果等方面的表现。通过对教师的命题步骤、对评价方式的理解、对评价结果的有效利用等方面进行调研，进行统计分析，得到分析结果。


教师学业评价能力指数分为9级，指数越高，表示教师学业评价能力越强。

\mylist

- 9级：表示90%以上教师学业评价能力较强\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的教师学业评价能力较强（含80%）
- 7级：表示70%-80%的教师学业评价能力较强（含70%）
- 6级：表示60%-70%的教师学业评价能力较强（含60%）
- 5级：表示50%-60%的教师学业评价能力较强（含50%）
- 4级：表示40%-50%的教师学业评价能力较强（含40%）
- 3级：表示30%-40%的教师学业评价能力较强（含30%）
- 2级：表示20%-30%的教师学业评价能力较强（含20%）
- 1级：表示20%以下的教师学业评价能力较强

\mytext

plot.bar.school.index.teaching.evaluation

<!-- end of chapter teacher  -->
