<!-- chapter identity  -->

## 学生对学校的认同度指数

学生对学校认同指的是学生对学校的认可与接纳，是学生对所在学校的价值观、学校精神及文化传统的承认和接受，主要包括师生关系、同伴关系、学校归属感三个二级指数。

学生对学校的认同度指数分为 9 级，指数越高，表示学生对学校的认同度越高。


\mylist

- 9级：表示对学校的认同度较高\footnote{我们将得分超过本维度总分60\%界定为对学校的认同度较高。}的学生所占比例在90%以上（含90%）
- 8级：表示对学校的认同度较高的学生所占比例在80%-90%之间（含80%）
- 7级：表示对学校的认同度较高的学生所占比例在70%-80%之间（含70%）
- 6级：表示对学校的认同度较高的学生所占比例在60%-70%之间（含60%）
- 5级：表示对学校的认同度较高的学生所占比例在50%-60%之间（含50%）
- 4级：表示对学校的认同度较高的学生所占比例在40%-50%之间（含40%）
- 3级：表示对学校的认同度较高的学生所占比例在30%-40%之间（含30%）
- 2级：表示对学校的认同度较高的学生所占比例在20%-30%之间（含20%）
- 1级：表示对学校的认同度较高的学生所占比例在20%以下

\mytext

plot.bar.school.index.school.identity

### 师生关系指数

师生关系指教师和学生在教育教学过程中结成的相互关系，包括彼此所处的地位、作用和相互对待的态度。师生关系主要体现在教师对于学生的尊重，能公正、平等地对待学生，信任学生等方面。
    
已有的研究发现，积极的师生关系能够促进学生的学校适应性、学校参与度和学校归属感（邹弘等人，2007；Valle等人，2018 \cite{cite_065}；Uslu等人，2017 \cite{cite_065} ），能够显著预测学生的学业成就（王默、董洋，2017 \cite{cite_069}；李佳丽、胡咏梅，2017 \cite{cite_071}）   ，并对学生创造性思维、创新效能感有显著的正向预测作用（师保国等人，2016 \cite{cite_072} ） 。
    
研究还发现，不同年级的学生对师生关系的评价存在一定的差异。低年级的学生因认知发展尚未成熟，更倾向于做出极端赞许性的评价。高年级的学生因自我意识的增强、学习压力等原因，对师生关系的评价可能会低于低年级学生（王晓华、王耘，2006 \cite{cite_073} ） 。此外，女生的师生关系通常比男生更积极，学业表现好的学生通常有更积极的师生关系（王耘、王晓华，2002 \cite{cite_074} ） 。
    
师生关系涉及到学生和教师双方。教师和学生因认知能力、评价标准、角色地位、敏感程度的不同，对师生关系的评价可能会出现差异。因此，相关的研究和实践需要重视双方对师生关系的感受（王晓华、王耘，2006 \cite{cite_073} ）。

师生关系指数分为 9 级，指数越高，表示师生关系越好。


\mylist

- 9级：表示师生关系指数较好\footnote{我们将得分超过本维度总分60\%界定为师生关系较好。}的学生所占比例在90%以上（含90%）
- 8级：表示师生关系指数较好的学生所占比例在80%-90%之间（含80%）
- 7级：表示师生关系指数较好的学生所占比例在70%-80%之间（含70%）
- 6级：表示师生关系指数较好的学生所占比例在60%-70%之间（含60%）
- 5级：表示师生关系指数较好的学生所占比例在50%-60%之间（含50%）
- 4级：表示师生关系指数较好的学生所占比例在40%-50%之间（含40%）
- 3级：表示师生关系指数较好的学生所占比例在30%-40%之间（含30%）
- 2级：表示师生关系指数较好的学生所占比例在20%-30%之间（含20%）
- 1级：表示师生关系指数较好的学生所占比例在20%以下

\mytext

plot.bar.school.index.teacher.relation


### 同伴关系指数

同伴关系指年龄相同或相近的儿童或青少年之间的一种共同活动并相互协作的关系。学校中的同伴关系主要体现在一个班集体中的学生之间是否彼此接纳与包容，是否协作与交流，是否相互理解与尊重。

已有的研究发现，良好的同伴关系对学生亲社会行为有积极的影响，能够减轻学生的抑郁、焦虑和孤独感，提高学生的自我概念水平，并对学生的学业产生一定的影响（李婧怡，2010 \cite{cite_075}；周宗奎等人，2015 \cite{cite_076}）  。
    
学生的性别、性格、气质、心理素质、自尊，和同伴的交往方式等因素都会影响同伴关系。随着年龄的增长，这样因素对同伴关系的影响也会有所变化（邹泓，1998 \cite{cite_077}；周宗奎等人，2015 \cite{cite_076}；刘广增等人，2016 \cite{cite_078}）  。此外，父母的关心与教育期望也会对孩子的同伴关系产生影响，尤其会影响孩子对同伴关系的评价，以及孩子在同伴中所处的位置。而家庭社会经济背景可能会对学生的同伴关系产生影响（杨钋, 朱琼，2013 \cite{cite_078}）。

同伴关系指数分为 9 级，指数越高，表示同伴关系越好。


\mylist

- 9级：表示同伴关系较好\footnote{我们将得分超过本维度总分60\%界定为同伴关系较好。}的学生所占比例在90%以上（含90%）
- 8级：表示同伴关系较好的学生所占比例在80%-90%之间（含80%）
- 7级：表示同伴关系较好的学生所占比例在70%-80%之间（含70%）
- 6级：表示同伴关系较好的学生所占比例在60%-70%之间（含60%）
- 5级：表示同伴关系较好的学生所占比例在50%-60%之间（含50%）
- 4级：表示同伴关系较好的学生所占比例在40%-50%之间（含40%）
- 3级：表示同伴关系较好的学生所占比例在30%-40%之间（含30%）
- 2级：表示同伴关系较好的学生所占比例在20%-30%之间（含20%）
- 1级：表示同伴关系较好的学生所占比例在20%以下

\mytext

plot.bar.school.index.classmate.relation


### 学校归属感指数

学校归属感指学生对自己所就读的学校在思想、感情和心理上的认可和投入，愿意承担作为学校一员的各项责任和义务以及乐于参与学校集体活动。主要体现在学生是否认同学校的理念、是否积极参加学校集体活动等方面。

已有的研究发现，学校归属感与正面情感（如乐观）、学业成就、自我概念有显著的正相关，与负面情感（如抑郁、被排斥感等）呈显著负相关（Roeser 等人，1996 \cite{cite_081}；Anderman，2002 \cite{cite_080}；庞海波，2009 \cite{cite_082}）   。学生的学校归属感越强，不良行为（如吸烟、暴力行为等）产生的几率也越低（McNeely and Falci，2004） 。相比重点学校，非重点学校的学生的学校归属通常感更弱（包克冰、徐琴美，2006 \cite{cite_085}） 。

良好的学校和班级环境、教师的支持和关心、友好的同伴关系、积极的自我概念，丰富的课外活动等都有助于学生产生对学校的归属感（Brown and Evans，2002 \cite{cite_086}；包克冰、徐琴美，2006 \cite{cite_085}；Slaten等人，2016 \cite{cite_087}）  。此外，学校归属感的水平也可能随着学生在学校就读时间的增长而减弱。低年级学生由于进入校园不久，课业负担较轻，活动较多而产生更强的学校归属感。高年级则可能受到考试和升学压力的影响，课外活动时间有所压缩，师生和生生活动更聚焦于学业，因此减弱了对学校的归属感（包克冰、徐琴美，2006 \cite{cite_085} ）。

本项目主要通过学生对学校的情感、学生参与学校各项活动等问题调查学生的学校归属感，通过问卷收集数据，并对数据进行统计分析得到的结果。

学校归属感指数分为 9 级，指数越高，表示学校归属感越强。

\mylist

- 9级：表示学校归属感较强\footnote{我们将得分超过本维度总分60\%界定为学校归属感较强。}的学生所占比例在90%以上（含90%）
- 8级：表示学校归属感较强的学生所占比例在80%-90%之间（含80%）
- 7级：表示学校归属感较强的学生所占比例在70%-80%之间（含70%）
- 6级：表示学校归属感较强的学生所占比例在60%-70%之间（含60%）
- 5级：表示学校归属感较强的学生所占比例在50%-60%之间（含50%）
- 4级：表示学校归属感较强的学生所占比例在40%-50%之间（含40%）
- 3级：表示学校归属感较强的学生所占比例在30%-40%之间（含30%）
- 2级：表示学校归属感较强的学生所占比例在20%-30%之间（含20%）
- 1级：表示学校归属感较强的学生所占比例在20%以下

\mytext

plot.bar.school.index.school.sense

<!-- end of chapter identity  -->
