<!-- chapter description -->
\mytext

## 英语学业水平描述

九年级学生英语综合运用能力包括：能在设定的情景中进行问答；能就熟悉的话题同他人进行简单交流；能阅读基本无生词的短文，理解大意，获取关键信息；能书写一般文体的短文，进行简单描述和表达个人喜好，拼写和标点正确。英语学科测试框架将各层次学生英语综合运用能力水平描述从高到低分成A、B、C、D四个等级。


`r tab_name <- "九年级英语学科学业水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

考查能力 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{11}{*}{听} & \multirow{2}{*}{A} & $\star$ 能在熟悉的情境中准确地理解说话人的意图和态度，并进行适当的判断；  \\
 &  & $\star$ 能准确地归纳和掌握所听内容的主旨和重要细节。  \\ \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 能听懂发生在熟悉的情境中的对话和独白，并进行适当的判断；  \\
 &  & $\star$ 能听懂听力材料的主旨和重要细节；  \\
 &  & $\star$ 能借助文字、图表等听懂完成任务所需要的关键信息。 \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能听懂课堂用语和考试指令； \\
 &  & $\star$ 能听懂句子或简短对话中的关键信息，回答事实性问题；  \\
 &  & $\star$ 能借助文字、图表等大致听懂完成任务所需要的关键信息。  \\ \cline{2-3}

 & \multirow{3}{*}{D} & $\star$ 最多能听懂部分简单的课堂或考试指示语；  \\
 &  & $\star$ 最多能听懂所熟悉的话题语境中的有限信息； \\
 &  & $\star$ 在图片帮助下，最多能听懂所熟悉的话题语境中的部分语汇。 \\ \hline

\multirow{5}{*}{读} & \multirow{3}{*}{A} & $\star$ 能读懂所熟悉话题内容的简单读物； \\
 &  & $\star$ 能理解事件发生的原因、顺序和结果, 并能在一定程度上对有关信息进行推测或概括； \\
 &  & $\star$ 能根据上下文句子关系或运用英语构词基本知识猜测生词含义。 \\ \cline{2-3}

 & \multirow{2}{*}{B} & $\star$ 能读懂简短故事、个人信件或涉及日常生活等的语言材料； \\
 &  & $\star$ 能理解事件发生的原因、顺序和结果； \\
 &  & $\star$ 能在一定程度上对有关信息进行概括；  \\
 &  & $\star$ 能根据上下文猜测语言材料中部分生词含义。 \\ \cline{2-3}

 & \multirow{4}{*}{C} & $\star$ 能借助图片读懂英语句子； \\
 &  & $\star$ 能读懂简短故事、个人信件、简短的通知和广告等语言材料； \\
 &  & $\star$ 能从所读材料中找出相关信息； \\
 &  & $\star$ 能基本理解事件发生的原因、顺序和结果。 \\ \cline{2-3}

 & \multirow{2}{*}{D} & $\star$ 最多能读懂基本的指令性语言；  \\
 &  & $\star$ 最多能读懂英语简单句子的含义，但不能理解语篇的含义。 \\ \hline

\multirow{13}{*}{写} & \multirow{3}{*}{A} & $\star$ 能准确运用句法知识，写出结构、意义完整的句子； \\
 &  & $\star$ 能根据任务要求、文字或图片提示，写短文、便条、日记等，内容贴切、语义连贯、语言表达流畅； \\
 &  & $\star$ 能正确使用字母大、小写和标点符号。 \\ \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 能基本运用句法知识，写出结构基本完整的句子； \\
 &  & $\star$ 能根据任务要求、文字或图片提示，写短文、便条、日记等，内容基本贴切、语义基本连贯、语言表达大致流畅； \\
 &  & $\star$ 能基本正确使用字母大、小写和标点符号。 \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能尝试运用句法知识，写出句子的主要结构； \\
 &  & $\star$ 能根据任务要求、文字或图片提示，写短文、便条、日记等，部分内容贴切、语言表达欠流畅； \\
 &  & $\star$ 能注意到使用字母大、小写和标点符号，但使用欠准确。 \\ \cline{2-3}

 & \multirow{2}{*}{D} & $\star$ 最多能写出一些单词，但看不出句子结构，无法表达意义； \\
 &  & $\star$ 最多能注意到字母大、小写和标点符号。 \\ \hline

\end{longtable}
\end{itshape}

<!-- end of chapter description -->
