<!-- chapter description -->
\mytext


## 艺术学业水平描述

`r tab_name <- "艺术学科学业水平描述" `

艺术学业水平描述是指被试学生在艺术领域的“感受与鉴赏”“合作与分享”“表现与创作”的表现情况界定，其针对学生水平的描述从高到低分成A、B、C、D四个等级。表\ref{tab: `r tab_name`}具体呈现不同水平的可能表现（或观测点）。

\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\  

\hline
能力维度	& 水平 &	\makecell[c]{水平描述} \\ \hline
\multirow{23}{*}{\makecell{感受与鉴赏}} &	\multirow{8}{*}{A}	 & $\star$	能准确感受并体会音乐、舞蹈、戏剧等表演艺术的表现形式 \\ \cline{3-3}
 & & $\star$	能准确感受并体会绘画、雕塑、设计等造型艺术的表现形式 \\ \cline{3-3}
 & & $\star$  能感受并分析作品中艺术要素的表现意义 \\ \cline{3-3}
 & & $\star$ 能知道并说明音乐的种类和体裁，如声乐、器乐及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 能知道并说明美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 能准确感受舞蹈、戏曲表达的人物情感 \\ \cline{3-3}
 & & $\star$ 能准确体会不同时期音乐、美术作品的艺术特色，并了解作品中蕴含的时代发展特点 \\ \cline{3-3}
 & & $\star$ 能知道并了解不同门类具有代表性的艺术家及其艺术经历 \\ \cline{2-3}
 &	\multirow{8}{*}{B} & $\star$	能感受并适当体会音乐、舞蹈、戏剧等表演艺术的表现形式 \\ \cline{3-3}
 & & $\star$ 能感受并适当体会绘画、雕塑、设计等造型艺术的表现形式  \\ \cline{3-3}
 & & $\star$ 能感受作并适当分析品中艺术要素的表现意义  \\ \cline{3-3}
 & & $\star$ 能知道并适当说明音乐的种类和体裁，如声乐、器乐及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能知道并适当说明美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能感受舞蹈、戏曲表达的人物情感  \\ \cline{3-3}
 & & $\star$ 能较为准确地体会不同时期音乐、美术作品的艺术特色，并了解作品中蕴含的时代发展特点  \\ \cline{3-3}
 & & $\star$ 能知道不同门类具有代表性的艺术家及其艺术经历  \\ \cline{2-3}
 &	\multirow{8}{*}{C} & $\star$	能知道音乐、舞蹈、戏剧等表演艺术的表现形式  \\ \cline{3-3}
 & & $\star$ 能知道体会绘画、雕塑、设计等造型艺术的表现形式  \\ \cline{3-3}
 & & $\star$ 能了解艺术要素的表现意义  \\ \cline{3-3}
 & & $\star$ 能知道音乐的种类和体裁，如声乐、知道器乐及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能知道美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能初步感受舞蹈、戏曲表达的人物情感  \\ \cline{3-3}
 & & $\star$ 能基本知道不同时期音乐、美术作品的艺术特色  \\ \cline{3-3}
 & & $\star$ 基本了解不同门类具有代表性的艺术家及其艺术经历。  \\ \cline{2-3}
 &	\multirow{4}{*}{D} & $\star$	不知道音乐、舞蹈、戏剧等表演艺术的表现形式 \\ \cline{3-3}
 & & $\star$ 不知道体会绘画、雕塑、设计等造型艺术的表现形式 \\ \cline{3-3}
 & & $\star$ 不能了解艺术要素的表现意义 \\ \cline{3-3}
 & & $\star$ 不知道音乐的种类和体裁，如声乐、知道器乐及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 不知道美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 不能初步感受舞蹈、戏曲表达的人物情感 \\ \cline{3-3}
 & & $\star$ 不知道不同时期音乐、美术作品的艺术特色 \\ \cline{1-3}

\multirow{12}{*}{合作与分享}	& \multirow{3}{*}{A}	& $\star$	能准确评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 能主动并准确模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 能主动并准确用各种形式表达对音乐、美术及其相关艺术作品的感受 \\ \cline{2-3}
 & \multirow{3}{*}{B}	& $\star$	能较准确评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 能主动并较好模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 能主动并较为准确用各种形式表达对音乐、美术及其相关艺术作品的感受 \\ \cline{2-3}
 & \multirow{3}{*}{C}	& $\star$	能评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 能模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 能基本准确用各种形式表现对音乐、美术及其相关艺术作品的感受 \\ \cline{2-3}
 & \multirow{3}{*}{D}	& $\star$	不能准确评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 不能模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 不能用各种形式表现对音乐、美术及其相关艺术作品的感受 \\ \cline{1-3}

\multirow{8}{*}{表现与创作}	& A	& $\star$ 能主动收集、筛选、提炼创作素材，并准确运用相关内容表现 \\ \cline{3-3}
 & & $\star$ 能积极主动借鉴艺术家的创意,进行艺术构思 \\ \cline{2-3}
 & B & $\star$	能主动收集、筛选、提炼创作素材，并运用相关内容表现 \\ \cline{3-3}
 & & $\star$ 能借鉴艺术家的创意,进行艺术构思 \\ \cline{2-3}
 & C & $\star$ 能运用所给素材，进行内容表现 \\ \cline{3-3}
 & & $\star$ 能尝试借鉴艺术家的创意,进行艺术构思 \\ \cline{2-3}
 & D & $\star$ 不能收集、筛选、提炼创作素材，并表现 \\ \cline{3-3}
 & & $\star$ 不能借鉴艺术家的创意,进行艺术构思 \\ \cline{1-3}

\end{longtable}
\end{itshape}

<!-- end of chapter description -->
