<!-- chapter morality  -->

\mytext

# 学生品德行为指数

良好的品德是个人成长、终生发展的基础，更是其成为社会有用之才的重要条件。良好的品德行为包括热爱祖国、自尊自爱、尊重他人、有诚信和责任心、遵守公德以及拥有关怀之心和公正之心。品德行为指数是通过采集学生问卷数据，进行数据分析得到的结果。

学生品德行为指数分为 9 级，指数越高，表示学生具有较好的品德行为素养。


\mylist

- 9级：表示90%以上的学生品德行为素养较高\footnote{我们将得分超过本维度总分50\%界定为品德行为素养较高。
}（含90%）
- 8级：表示80%-90%的学生品德行为素养较高（含80%）
- 7级：表示70%-80%的学生品德行为素养较高（含70%）
- 6级：表示60%-70%的学生品德行为素养较高（含60%）
- 5级：表示50%-60%的学生品德行为素养较高（含50%）
- 4级：表示40%-50%的学生品德行为素养较高（含40%）
- 3级：表示30%-40%的学生品德行为素养较高（含30%）
- 2级：表示20%-30%的学生品德行为素养较高（含20%）
- 1级：表示20%以下的学生品德行为素养较高

\mytext

plot.bar.district.index.morality.perspective
multiplot.bar.district.index.morality.school


良好的品德是个人成长、终身发展的基础，更是学生成为社会有用之才的重要条件。社会化则反映了学生对社会规则和价值的内化程度，具体表现为学生按照社会规范妥善行事。学生品德和社会化行为指标主要包括行为规范、亲社会行为、国家认同、国际视野这四个二级指标。


## 行为规范

著名教育家苏霍姆林斯基曾经说过：“请别忽视——学生良好行为习惯的养成与否，这关系到教育者的教育目的的成败。”学生的完整品德是在学校中遵守明确的道德要求、准则和行为规范而形成的，道德习惯的养成在个性形成与品德发展中具有极其深远的意义。

行为培养习惯，习惯决定品质，品质改变命运。学生阶段是人的成长发展阶段，也是行为习惯养成的关键时期，学校有责任进行行为规范的养成教育，帮助学生形成好的行为习惯，为未来发展奠定基础。从日常行为规范入手树立道德观念、养成文明行为，避免思想政治的空洞说教，使内化教育具有可操性。

本项目中的行为规范主要指学生遵纪守法、遵守中小学生行为规范，能够维持正常适宜的学校和社会生活。具体来说，测评主要考察学生法律法规的遵守情况、学生学校行为规范的遵守情况、学生社会公共礼仪行为等方面。

行为规范指数是通过采集学生问卷数据，进行数据分析得到的结果。

学生行为规范指数分为 9 级，指数越高，表示学生具有较好的行为规范。

\mylist
- 9 级：表示 90% 以上的学生行为规范素养较高\cite{cite_00}（含 90%）
- 8 级：表示 80%-90% 的学生行为规范素养较高（含 80%）
- 7 级：表示 70%-80% 的学生行为规范素养较高（含 70%）
- 6 级：表示 60%-70% 的学生行为规范素养较高（含 60%）
- 5 级：表示 50%-60% 的学生行为规范素养较高（含 50%）
- 4 级：表示 40%-50% 的学生行为规范素养较高（含 40%）
- 3 级：表示 30%-40% 的学生行为规范素养较高（含 30%）
- 2 级：表示 20%-30% 的学生行为规范素养较高（含 20%）
- 1 级：表示 20% 以下的学生行为规范素养较高
\mytext

plot.bar.district.index.conduct.perspective
multiplot.bar.district.index.conduct.school


## 亲社会行为

亲社会行为指学生在社会交往的情境中有意识地做出帮助他人的行为或做有益于他人的事的倾向，主要体现在友爱宽容、乐于助人、善于合作、尊重他人等行为上。

研究发现，亲社会行为能给个体带来意义感和效能感，有利于个体应对焦虑、孤独等负性情绪，提高个体的幸福感水平。 青少年期是个体人生发展中的一个重要时期，青少年的道德价值观、情绪社会性发展也正处于关键时段。亲社会行为的表达与维持是德育教育的有效途径，德育工作者日益关注亲社会行为与青少年健康发展的关系、以及亲社会行为的培养和干预。

亲社会行为测量主要有以他人利益为重的利他性维度、反映遵守社会或组织规范的遵规－公益性维度、反映社会交往双方人际和谐的关系性维度，以及反映自我提升动机的特质性四个维度。遵规-公益维度在行为规范测量中已有提及，因此本项目亲社会行为测评重点关注利他性维度与关系性维度。

亲社会行为指数是通过采集学生问卷数据，进行数据分析得到的结果。

亲社会行为指数分为 9 级，指数越高，表示学生具有较好的亲社会行为。

\mylist
- 9 级：表示 90% 以上的学生亲社会行为素养较高（含 90%）
- 8 级：表示 80%-90% 的学生亲社会行为素养较高（含 80%）
- 7 级：表示 70%-80% 的学生亲社会行为素养较高（含 70%）
- 6 级：表示 60%-70% 的学生亲社会行为素养较高（含 60%）
- 5 级：表示 50%-60% 的学生亲社会行为素养较高（含 50%）
- 4 级：表示 40%-50% 的学生亲社会行为素养较高（含 40%）
- 3 级：表示 30%-40% 的学生亲社会行为素养较高（含 30%）
- 2 级：表示 20%-30% 的学生亲社会行为素养较高（含 20%）
- 1 级：表示 20% 以下的学生亲社会行为素养较高
\mytext

plot.bar.district.index.prosocial.perspective
multiplot.bar.district.index.prosocial.school


## 国家认同

随着全球化、信息化的发展，跨文化交流日益增加，公民吸收外来文化变得方便快捷，国家间边界变得相对模糊，公民的国家认同感削弱，各国不同程度地面临国家认同的挑战。

青少年的国家认同感关乎国家的统一与稳定、民族的团结与发展、以及社会的和谐与进步，是建立富强民主国家之基础。

本项目的“国家认同”是指人对于国家或民族的归属感、认同感和责任感，通常以一个国家或民族独特的传统、文化、语言和政治作为代表。国家认同的测评维度主要调查学生在热爱祖国、认可中华优秀传统文化、民族平等与团结、勇于承担责任等社会主义核心价值观方面的表现。

国家认同指数是通过采集学生问卷数据，进行数据分析得到的结果。

国家认同指数分为 9 级，指数越高，表示学生具有较高的国家认同。

\mylist
- 9 级：表示 90% 以上的学生国家认同较高（含 90%）
- 8 级：表示 80%-90% 的学生国家认同较高（含 80%）
- 7 级：表示 70%-80% 的学生国家认同较高（含 70%）
- 6 级：表示 60%-70% 的学生国家认同较高（含 60%）
- 5 级：表示 50%-60% 的学生国家认同较高（含 50%）
- 4 级：表示 40%-50% 的学生国家认同较高（含 40%）
- 3 级：表示 30%-40% 的学生国家认同较高（含 30%）
- 2 级：表示 20%-30% 的学生国家认同较高（含 20%）
- 1 级：表示 20% 以下的学生国家认同较高
\mytext

plot.bar.district.index.country.identity.perspective
multiplot.bar.district.index.country.identity.school


## 国际视野

全球化带来了创新，同时带来了经济不平等和社会分裂。面对前所未有的挑战和机遇，新生代需要有识别与理解不同文化和偏见，与不同背景文化人合作解决问题的能力。学校教育需要让学生为之做好准备，培养学生的国际视野，理解本国及他国文化，欣赏不同价值观，建立信任和跨越差异的合作关系。

国际视野指能将世界看成一个自然、社会、历史的综合体，立足于人类命运共同体的建设，理解不同国家与民族的文化差异，认识、分析和思考世界历史和社会问题，并在互相尊重的基础上，能与不同文化背景的人开放、合适、有效地沟通。

国际视野指标测评主要调查学生的全球意识（如自觉且敏锐地了解世界、尊重文化差异）、国际知识（对全球议题、国际规则、文化礼俗等的了解程度）、国际行为能力（如多国语言技能，分析、判断、解释国际问题和社会问题的能力）等方面。

国际视野指数是通过采集学生问卷数据，进行数据分析得到的结果。

国际视野指数分为 9 级，指数越高，表示学生具有较高的国际视野。

\mylist
- 9 级：表示 90% 以上的学生国际视野较高（含 90%）
- 8 级：表示 80%-90% 的学生国际视野较高（含 80%）
- 7 级：表示 70%-80% 的学生国际视野较高（含 70%）
- 6 级：表示 60%-70% 的学生国际视野较高（含 60%）
- 5 级：表示 50%-60% 的学生国际视野较高（含 50%）
- 4 级：表示 40%-50% 的学生国际视野较高（含 40%）
- 3 级：表示 30%-40% 的学生国际视野较高（含 30%）
- 2 级：表示 20%-30% 的学生国际视野较高（含 20%）
- 1 级：表示 20% 以下的学生国际视野较高
\mytext

plot.bar.district.index.global.view.perspective
multiplot.bar.district.index.global.view.school

<!-- end of chapter morality  -->
