<!-- chapter description -->
\mytext


## 数学学业水平描述

学业水平界定是指被试学生在解决数学问题“过程”中综合运用基本“方法”后对其能力水平所进行的分层描述。《上海市初中数学学科教学基本要求》指出，通过数学解题活动所能检测的“能力”，本质上是指学生在基于各类情境的问题解决过程中合理、准确、灵活地运用各种所学的数学概念原理、定理推论、方法技能和基本思想等的表现，因此，过程与方法主要用于检测学生的能力表现。数学测试框架将各层次学生在解决数学问题各类过程分量的水平描述从高到低分成A、B、C、D四个等级。

### “辨识”过程表现水平描述

`r tab_name <- "“辨识”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{12}{*}{辨识} & \multirow{3}{*}{A} & $\star$ 能根据各种情境需要正确回忆事实性结论和准确辨析及识别数学问题中所包含的数学概念、规则或方法；  \\
 &  & $\star$ 能在较为复杂的情境中准确把握问题的限制条件和假设；  \\
 &  & $\star$ 能将简单的真实情境转化为数学问题并准确加以表征或陈述。  \\ \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 能在动态的情境中回忆事实性结论和辨析及识别数学问题中所包含的数学概念、规则或方法；  \\
 &  & $\star$ 能在一般的情境中准确把握问题的限制条件和假设；  \\
 &  & $\star$ 能将简单的真实情境转化为数学问题并较为准确加以表征或陈述。  \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能在简单情境中回忆事实性结论和辨析及识别数学问题中所包含的数学概念、规则或方法； \\
 &  & $\star$ 能在较为简单的情境中把握问题的限制条件和假设；  \\
 &  & $\star$ 能将简单的真实情境转化为数学问题，但不能较为准确加以表征或陈述。  \\ \cline{2-3}


 & \multirow{3}{*}{D} & $\star$ 不能在情境中回忆事实性结论和约定及辨识数学对象，或回忆出部分、混淆简单事实性结论、对象；  \\
 &  & $\star$ 不能在较为简单的情境中把握问题的限制条件和假设；  \\
 &  & $\star$ 不能将简单的真实情境转化为数学问题，不能较为准确加以表征或陈述。  \\ \hline

\end{longtable}
\end{itshape}

### “调用”过程表现水平描述

`r tab_name <- "“调用”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{16}{*}{调用} & \multirow{4}{*}{A} & $\star$ 能根据问题需要准确调用数学概念、事实、原理、性质或方法等，有序开展操作、计算或推理，并获得准确的数学结论；  \\
 &  & $\star$ 能在复杂情境中识别解决具体问题所需要的算法，并能用相应的模型准确地解决问题；  \\
 &  & $\star$ 能从复杂的图表中准确提取数学信息，合理地进行数据的分析；  \\
 &  & $\star$ 能使用较为复杂的工具进行测量、根据给定的条件进行较为复杂的作图。  \\ \cline{2-3}

 & \multirow{4}{*}{B} & $\star$ 能根据问题需要调用数学概念、事实、原理、性质或方法等，开展操作、计算或推理，并获得数学结论；  \\
 &  & $\star$ 能在具体情境中识别解决问题所需要的算法，并通过列式计算、画出图表等解决问题；   \\
 &  & $\star$ 能从图表中准确提取数学信息，合理地进行数据的分析；   \\
 &  & $\star$ 能使用常见的工具进行测量、作图。  \\ \cline{2-3}

 & \multirow{4}{*}{C} & $\star$ 能根据问题需要调用简单的数学概念、事实、原理、性质或方法等，开展操作、计算或推理，并获得简单的数学结论； \\
 &  & $\star$ 能在简单情境中识别解决具体问题所需要的算法，并通过列式计算、画出图表等解决问题；   \\
 &  & $\star$ 能从图表中提取数学信息进行数据的分析；   \\
 &  & $\star$ 能使用简单工具进行直接测量、根据给定的条件进行简单作图。  \\ \cline{2-3}


 & \multirow{4}{*}{D} & $\star$ 不能根据问题需要准确调用数学概念、事实、原理、性质或方法等，开展操作、计算或推理，不能准确地获得数学结论；  \\
 &  & $\star$ 不能在具体情境中识别解决问题所需的算法，或计算中频繁出错；  \\
 &  & $\star$ 不能用简单工具进行最基本的测量、作图，或者测量与作图中频繁出错。   \\
 &  & $\star$ 不能从图表中提取数学信息，不能进行数据的分析或分析出错。  \\ \hline

\end{longtable}
\end{itshape}


### “反思”过程表现水平描述

`r tab_name <- "“反思”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{3}{*}{} & \multirow{1}{*}{A} & $\star$ 能对复杂的数学问题的解答和结论加以准确地检验、判定或评价；  \\
 &  & $\star$ 能将基于复杂真实情境问题的解答和结论回到问题情境中进行准确阐释，并明确其在问题情境中的实际意义。  \\
 &  & $\star$ 能对解决数学问题的过程与方法进行反思，建立知识之间的实质性联系。  \\ \cline{2-3}

\multirow{9}{*}{反思}  & \multirow{3}{*}{B} & $\star$ 能对较复杂的数学问题的解答和结论加以较为准确地检验、判定或评价； \\
 &  & $\star$ 能将基于较复杂的真实情境问题的解答和结论回到问题情境中进行阐释并明确其在问题情境中的实际意义。  \\
 &  & $\star$ 能对解决数学问题的过程与方法进行反思，建立知识之间的直接联系。  \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能对简单的数学问题的解答和结论加以检验、判定或评价； \\
 &  & $\star$ 能将基于简单真实情境问题的解答和结论回到问题情境中进行阐释或明确其在问题情境中的意义。  \\
 &  & $\star$ 能对解决一类数学问题的过程与方法进行简答总结和反思。  \\ \cline{2-3}

 & \multirow{3}{*}{D} & $\star$ 不能对数学问题解答和结论加以检验、判定或评价，或对数学问题解答和结论作出错误的检验、判定或评价。  \\
 &  & $\star$ 不能将基于真实情境问题的解答和结论回到问题情境中进行阐释或不明确其在问题情境中的实际意义。  \\
 &  & $\star$ 不能通过反思建立知识之间的直接联系，或建立联系中有明显错误。  \\ \hline

\end{longtable}
\end{itshape}


### “聚合”过程表现水平描述

`r tab_name <- "“聚合”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{16}{*}{聚合} & \multirow{4}{*}{A} & $\star$ 能在新的问题情境下提炼数学问题，构建数学模型，并合理运用数学语言表述； \\
 &  & $\star$ 能在问题情境或限制条件约束的基础上，灵活运用策略、数据、模型及相关的数学技能、思想方法，或者创新地设计或运用新方法获得结论；  \\
 &  & $\star$ 能从基本事实出发，用猜想—归纳—演绎推理的方式确认某一结论的正确性，或者能发现并运用数学方法解释结论的局限性； \\
 &  & $\star$ 能对解决问题的过程进行评价和推广，并进一步提出问题。  \\ \cline{2-3}

 & \multirow{4}{*}{B} & $\star$ 能辨识新的问题情境中数学问题，并运用数学语言表述；  \\
 &  & $\star$ 能在问题情境或限制条件约束的基础上，运用已有数学技能、思想方法，或者运用问题情境中的新方法获得结论；  \\
 &  & $\star$ 能用简单推理的方式验证获得的结果和数学结论，或能发现并尝试解释结论的局限性. \\
 &  & $\star$ 能对解决问题的过程进行简单的评价和推广，能在已有结论的基础上提出问题。 \\ \cline{2-3}

 & \multirow{4}{*}{C} & $\star$ 能读懂新问题情境中的数学信息，但不能用准确的数学语言表述； \\
 &  & $\star$ 能在问题情境或限制条件约束的基础上，运用简单的数学技能、思想方法获得一些简单的结论； \\
 &  & $\star$ 能通过举例等方式验证结果和数学结论，或发现结论的局限性； \\
 &  & $\star$ 能对解决问题的过程进行简单评价。  \\ \cline{2-3}

 & \multirow{4}{*}{D} & $\star$ 不能有效提取新的问题情境中的数学信息，或不能用数学语言表述； \\
 &  & $\star$ 不能对数学结果和结论进行简单的论证和解释，或不能发现结论中局限性；  \\
 &  & $\star$ 不能在新情境下运用数学知识与方法解决简单问题，或解决问题的基本策略与方法有明显错误； \\
 &  & $\star$ 不能对解决问题中的知识和方法进行评价和简单推广，或评价与推广中有明显错误。 \\ \hline

\end{longtable}
\end{itshape}


<!-- end of chapter description -->
