
<!-- chapter -->

\mytext

# 学生背景问卷调查结果分析

query.data.district.base.student.survey

学生问卷包括学生基本情况、师生关系、学习压力、学校认同度、学习动机、自信心和学习方法等。本章对学生问卷调查结果进行分析，以下是分析得到的主要结果：

- 本校学生是独生子女的占`r gio.R$SubAttSamKey(query.data, "学生", "独生子女", "总体", c("是"), 1)`%。
- 本校学生家庭图书量超过100本的占`r gio.R$SubAttSamKey(query.data, "家长", "藏书", "总体", c("200本以上", "101-200本之间"), 1)`%，不超过50本的占`r gio.R$SubAttSamKey(query.data, "家长", "藏书", "总体", c("20本以下", "21-50本之间"), 1)`%。
- 本校学生家庭汽车拥有量为零的占`r gio.R$SubAttSamKey(query.data, "家长", "汽车", "总体", c("暂时没有购买汽车"), 1)`%，两辆及以上的占`r gio.R$SubAttSamKey(query.data, "家长", "汽车", "总体", c("有，2辆", "有，2辆以上"), 1)`%。
- 本校学生没有出境旅游的比例为`r gio.R$SubAttSamKey(query.data, "家长", "旅游", "总体", c("目前还没有去过"), 1)`%，出境旅游过两次及以上的占`r gio.R$SubAttSamKey(query.data, "家长", "旅游", "总体", c("2次", "3次", "4次及以上"), 1)`%。
- 本校学生的父亲受教育程度为大学及以上的占`r gio.R$SubAttSamKey(query.data, "家长", "父亲教育程度", "总体", c("本科", "硕士", "博士"), 1)`%，初中及以下的占`r gio.R$SubAttSamKey(query.data, "家长", "父亲教育程度", "总体", c("初中及以下"), 1)`%。本校学生的母亲受教育程度为大学及以上的占`r gio.R$SamTopKey(query.data, "总体", "孩子母亲受教育程度大概是", c("本科", "硕士", "博士"), 1)`%，初中及以下的占`r gio.R$SamTopKey(query.data, "总体", "孩子母亲受教育程度大概是", c("初中及以下"), 1)`%。
- 本校学生每天做学校老师布置的书面作业时间超过2小时的占`r gio.R$SubAttSamKey(query.data, "学生", "作业时间", "总体", c("2-3小时（含2小时）", "3-4小时（含3小时）", "4小时及以上"), 1)`%，其中3小时以上的占`r gio.R$SubAttSamKey(query.data, "学生", "作业时间", "总体", c("3-4小时（含3小时）", "4小时及以上"), 1)`%，1小时以下的占`r gio.R$SubAttSamKey(query.data, "学生", "作业时间", "总体", c("1小时以内"), 1)`%。
- 本校学生认为学校作业难易适中的占`r gio.R$SubAttSamKey(query.data, "学生", "作业难度", "总体", c("难易适中"), 1)`%，认为非常难和非常容易的共占`r gio.R$SubAttSamKey(query.data, "学生", "作业难度", "总体", c("非常容易", "非常难"), 1)`%。
- 本校学生每周参加与考试科目相关的家教补习或课外辅导的时间在6小时以上的占`r gio.R$SubAttSamKey(query.data, "家长", "校外补习时间", "总体", c("6-8小时（含6小时）", "8小时及以上"), 1)`％。
- 本校学生每周参加校外兴趣班的时间在2小时及以上的占`r gio.R$SubAttSamKey(query.data, "家长", "校外兴趣班时间", "总体", c("2-4小时（含2小时）", "4-6小时（含4小时）", "6-8小时（含6小时）", "8小时及以上"), 1)`%，没有参加校外兴趣班的学生占`r gio.R$SubAttSamKey(query.data, "家长", "校外兴趣班时间", "总体", c("(跳过)"), 1)`%。
- 本校学生每个月参加考试和测验的频率在4次及以上的占`r gio.R$SubAttSamKey(query.data, "学生", "考试次数", "总体", c("4次", "5次", "6次", "7次", "8次及以上"), 1)`%，频率在3次及以下的占`r gio.R$SubAttSamKey(query.data, "学生", "考试次数", "总体", c("3次及以下"), 1)`%。
- 本校学生一年阅读课外读物量达到9本及以上的比例为`r gio.R$SubAttSamKey(query.data, "学生", "课外阅读", "总体", c("9-12本", "13本及以上"), 1)`%，有`r gio.R$SubAttSamKey(query.data, "学生", "课外阅读", "总体", c("1-4本", "没有"), 1)`%的学生年阅读量不足5本，有`r gio.R$SubAttSamKey(query.data, "学生", "课外阅读", "总体", c("没有"), 1)`%的学生几乎不进行课外阅读。
- 本校学生每周校外运动时间在1小时以内的占`r gio.R$SubAttSamKey(query.data, "学生", "校外运动时间", "总体", c("1小时以内"), 1)`%，在2小时及以上的占`r gio.R$SubAttSamKey(query.data, "学生", "校外运动时间", "总体", c("2-3小时（含2小时）", "3-4小时（含3小时）", "4-5小时（含4小时）", "5小时及以上"), 1)`%。
- 本校学生，`r gio.R$CoefSamDimTop(query.data, "总体", "师生关系", "二级指标", 1)`%对师生关系评价较高，具体表现在教师是否公平、平等的对待学生、是否信任学生这三个方面。
- 本校学生`r gio.R$CoefSamDimTop(query.data, "总体", "学业压力", "二级指标", 1)`%感到学习压力较轻。
- 本校学生中有`r gio.R$CoefSamDimTop(query.data, "总体", "学习动机", "二级指标", 1)`%的学生有比较强的学习动机。
- `r gio.R$CoefSamDomTop(query.data, "总体", "学生对学校认同度", "一级指标", 1)`%学生对学校认同度高，具体表现为喜欢自己的学校、老师，同学关系和睦。
- 本校学生中学习自信心较强的学生所占比例为`r gio.R$CoefSamDimTop(query.data, "总体", "学习自信心", "二级指标", 1)`%，自信心水平比较高，对自己的能力有比较恰当的评估。
- 本校学生对教师教学方式中的因材施教、互动教学、鼓励学生探究与发展这三个方面评价比较高。
- 本校学生总体心理健康水平比较高，但还有进一步培养的空间。

## 学生基本情况

### 家庭背景

#### 学生为独生子女的情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.onechild.perspective")`}给出了本校学生为独生子女的总体情况及各群体之间的比较。

plot.bar.district.base.onechild.perspective

\clearpage

#### 学生家庭的藏书量

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.book.perspective")`}给出了本校学生家庭藏书量的总体情况及各群体之间的比较。

plot.bar.district.base.book.perspective

#### 学生家庭汽车拥有量

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.car.perspective")`}给出了本校学生家庭拥有汽车的总体情况及各群体之间的比较。

plot.bar.district.base.car.perspective

#### 学生家庭出境旅游情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.trip.perspective")`}给出了本校学生家庭出境旅游的总体情况及各群体之间的比较。

plot.bar.district.base.trip.perspective

#### 学生父亲受教育情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.father.perspective")`}给出了本校学生父亲受教育的总体情况及各群体之间的比较。

plot.bar.district.base.father.perspective

#### 学生母亲受教育情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.mother.perspective")`}给出了本校学生母亲受教育的总体情况及各群体之间的比较。

plot.bar.district.base.mother.perspective


### 学生日常生活与学习

#### 学生睡眠时间

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.sleep.hours.perspective")`}给出了本校学生每天睡眠时间的总体情况及各群体之间的比较。

plot.bar.district.base.sleep.hours.perspective

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.sleep.feel.perspective")`}给出了本校学生对自己每天睡眠时间是否充足的看法。

plot.bar.district.base.sleep.feel.perspective

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.sleep.lack.reason")`}给出了本校学生睡眠不足的原因。

plot.bar.district.base.sleep.lack.reason

\clearpage

#### 学生作业时间

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.homework.hours.perspective")`}给出了本校学生每天做学校老师布置的作业时间的总体情况及各群体之间的比较。

plot.bar.district.base.homework.hours.perspective


#### 学校作业难易程度

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.homework.difficulty.perspective")`}给出了本校学生学校作业的难易程度的总体情况及各群体之间的比较。

plot.bar.district.base.homework.difficulty.perspective


#### 参加与考试科目相关的家教补习、课外辅导的情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.buke.perspective")`}给出了本校学生每周参加与考试科目相关的家教补习、课外辅导的百分比及各群体之间的比较。

plot.bar.district.base.buke.perspective

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.buke.hours.perspective")`}给出了本校学生每周参加与考试科目相关的家教补习、课外辅导的时间分布及各群体之间的比较。

plot.bar.district.base.buke.hours.perspective

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.buke.subject.perspective")`}给出了本校学生每周参加与考试科目相关的家教补习、课外辅导时间的学科分布及各群体之间的比较。

plot.bar.district.base.buke.subject.perspective


\clearpage 
图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.buke.reason")`}给出了本校学生每周参加与考试科目相关的家教补习、课外辅导的主要原因。

plot.bar.district.base.buke.reason


#### 参加校外兴趣班的情况

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.xingquban.perspective")`}给出了本校学生每周参加校外兴趣班的百分比及各群体之间的比较。

plot.bar.district.base.xingquban.perspective

\clearpage 

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.xingquban.hours.perspective")`}给出了本校学生每周参加校外兴趣班的时间分布情况及各群体之间的比较。

plot.bar.district.base.xingquban.hours.perspective


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.xingquban.subject.perspective")`}给出了本校学生每周校外兴趣班的种类情况及各群体之间的比较。

plot.bar.district.base.xingquban.subject.perspective


\clearpage 

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.xingquban.reason")`}给出了本校学生每周参加校外兴趣班的主要原因。

plot.bar.district.base.xingquban.reason



#### 考试和测验的频率

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.examination.perspective")`}给出了本校学生每月考试和测验次数的总体情况及各群体之间的比较。

plot.bar.district.base.examination.perspective



\clearpage 

#### 课外阅读数量

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.reading.perspective")`}给出了本校学生一年内阅读课外读物数量的总体情况及各群体之间的比较。

plot.bar.district.base.reading.perspective


#### 校外运动时间

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.sports.perspective")`}给出了本校学生每周校外运动时间的总体情况及各群体之间的比较。

plot.bar.district.base.sports.perspective



\clearpage 

## 学业压力相关问题调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.study.pressure")`}给出了本校学生对学业压力相关问题的看法。

plot.bar.district.base.study.pressure


\clearpage 

## 学习动机相关问题调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.study.motivation")`}给出了本校学生对学习动机相关问题的看法。

plot.bar.district.base.study.motivation


\clearpage 

## 学习自信心相关问题调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.study.confidence")`}给出了本校学生对学习自信心相关问题的看法。

plot.bar.district.base.study.confidence

\clearpage 

## 师生关系相关问题调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.teacher.relationship")`}给出了本校学生对师生关系评价的总体情况。

plot.bar.district.base.teacher.relationship

\clearpage 

## 同伴关系相关问题调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.classmate.relationship")`}给出了本校学生对同伴关系评价的总体情况。

plot.bar.district.base.classmate.relationship

## 学校归属感相关问题调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.school.identity")`}给出了本校学生对学校归属感相关问题的看法。

plot.bar.district.base.school.identity


## 教师教学方式有关问题的调查结果


本问卷对教师教学方式中的因材施教、互动教学、鼓励学生探究与发展这三个方面进行了调查，现将调查到的教师教学方式进行如下分析。

### 因材施教

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.teaching.ycsj")`}给出了本校学生对教师因材施教的评价。

plot.bar.district.base.teaching.ycsj

\clearpage

### 互动教学

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.teaching.hdjx")`}给出了本校学生对教师互动教学的评价。

plot.bar.district.base.teaching.hdjx


### 鼓励学生探究与发展

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.teaching.gltj")`}给出了本校学生对教师鼓励学生探究与发展的评价。

plot.bar.district.base.teaching.gltj


## 学习策略相关问题调查结果

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.study.method")`}给出了本校学生对学习策略相关问题的看法。

plot.bar.district.base.study.method


## 品德和社会化行为有关问题的调查结果

本问卷对学生品德和社会化行为的国家认同、国际视野、行为规范、亲社会行为几个方面进行了调查，现将调查到的学生品德和社会化行为相关问题进行如下分析。

\clearpage

### 国家认同

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.country.identity")`}给出了本校学生对国家认同相关问题的看法。

plot.bar.district.base.country.identity


### 国际视野

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.globalization.knowlage")`}给出了本校学生对国际知识相关问题的看法。

plot.bar.district.base.globalization.knowlage

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.globalization.concern")`}给出了本校学生对全球意识相关问题的看法。

plot.bar.district.base.globalization.concern

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.globalization.action")`}给出了本校学生对国际行为能力相关问题的看法。

plot.bar.district.base.globalization.action

\clearpage

### 行为规范

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.behavior.morality")`}给出了本校学生对行为规范相关问题的看法。

plot.bar.district.base.behavior.morality

### 亲社会行为

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.behavior.prosocial")`}给出了本校学生对亲社会行为相关问题的看法。

plot.bar.district.base.behavior.prosocial


## 心理健康有关问题的调查结果

本问卷对学生心理健康的情绪状态、情绪稳定性、情绪管理能力几个方面进行了调查，现将调查到的学生心理健康相关问题进行如下分析。

### 情绪状态

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.emotion.status")`}给出了本校学生对情绪状态相关问题的反馈。

plot.bar.district.base.emotion.status

\clearpage

### 情绪稳定性

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.emotion.stability")`}给出了本校学生对情绪稳定性相关问题的反馈。

plot.bar.district.base.emotion.stability

### 情绪管理能力

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.base.emotion.management")`}给出了本校学生对情绪管理能力相关问题的反馈。

plot.bar.district.base.emotion.management


\clearpage
<!-- end of chapter  -->
