<!-- chapter dimention -->

\mytext

# 学生在各内容维度和能力维度上的表现情况

## 全体学生在各内容维度和能力维度上的表现

### 全体学生在各内容维度上的表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.ma.content.dimention.rank")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.district.ma.content.dimention.quantile")`}分别给出了本区学生在数学学科各内容维度各水平上的人数比例和得分分布。

plot.bar.district.ma.content.dimention.rank
plot.box.district.ma.content.dimention.quantile


### 全体学生在各能力维度上的表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.district.ma.skill.dimention.rank")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.district.ma.skill.dimention.quantile")`}分别给出了本区学生在数学学科各能力维度各水平上的人数比例和得分分布。

plot.bar.district.ma.skill.dimention.rank
plot.box.district.ma.skill.dimention.quantile


## 学生在各内容维度的表现

### 数与代数

#### 本区不同群体学生的表现

plot.bar.district.ma.algebra.rank.perspective
plot.box.district.ma.algebra.quantile.perspective

#### 本区各学校学生的表现

multiplot.bar.district.ma.algebra.rank.school
multiplot.box.district.ma.algebra.quantile.school

### 图形与几何

#### 本区不同群体学生的表现

plot.bar.district.ma.geometric.rank.perspective
plot.box.district.ma.geometric.quantile.perspective


#### 本区各学校学生的表现

multiplot.bar.district.ma.geometric.rank.school
multiplot.box.district.ma.geometric.quantile.school

### 函数与概率统计初步

#### 本区不同群体学生的表现

plot.bar.district.ma.statistics.rank.perspective
plot.box.district.ma.statistics.quantile.perspective

#### 本区各学校学生的表现

multiplot.bar.district.ma.statistics.rank.school
multiplot.box.district.ma.statistics.quantile.school


## 学生在各能力维度的表现

### 辨识

#### 本区不同群体学生的表现

plot.bar.district.ma.formulating.rank.perspective
plot.box.district.ma.formulating.quantile.perspective


#### 本区各学校学生的表现

multiplot.bar.district.ma.formulating.rank.school
multiplot.box.district.ma.formulating.quantile.school

### 调用

#### 本区不同群体学生的表现

plot.bar.district.ma.employing.rank.perspective
plot.box.district.ma.employing.quantile.perspective

#### 本区各学校学生的表现

multiplot.bar.district.ma.employing.rank.school
multiplot.box.district.ma.employing.quantile.school

### 反思

#### 本区不同群体学生的表现

plot.bar.district.ma.reflecting.rank.perspective
plot.box.district.ma.reflecting.quantile.perspective

#### 本区各学校学生的表现

multiplot.bar.district.ma.reflecting.rank.school
multiplot.box.district.ma.reflecting.quantile.school

### 聚合

#### 本区不同群体学生的表现

plot.bar.district.ma.polymerizing.rank.perspective
plot.box.district.ma.polymerizing.quantile.perspective


#### 本区各学校学生的表现

multiplot.bar.district.ma.polymerizing.rank.school
multiplot.box.district.ma.polymerizing.quantile.school

<!-- end of chapter dimention -->
