<!-- chapter description -->
\mytext

# 学科测试说明

## 九年级数学学科测试简介

2018年上海市初中学业质量绿色指标数学学科测试，依据修订的18版数学学科测试框架，以《上海市中小学数学课程标准》和《上海市初中数学学科教学基本要求》（2017版）（以下简称《基本要求》）为指导，从内容和能力两个维度考查学生数学方面的学业水平，具体如下：

### 内容维度

`r tab_name <- "知识领域的内容分类描述" `

按照《标准》，中学数学测试的内容维度应分为“数与运算”“方程与代数”“函数与分析”“数据整理与概率统计”“图形与几何”等五个知识领域。为了更好地体现测试工具的稳定性和有效性，针对被测试的九年级学生学情，将五个知识领域整合为“数与代数”“图形与几何”“函数与概率统计初步”三个部分，构成本次测试的内容维度（见表\ref{tab: `r tab_name`}）。

\begin{itshape}
\mytable
\begin{longtable}{|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\

\hline
内容分类 & \makecell[c]{总体描述} \\  \hline

数与代数 & 了解由整数到有理数、实数的扩展思想；掌握有理数的运算法则和运算性质，懂得实数的基本运算和顺序关系；掌握简单的整式、分式和二次根式的基本运算和变形；懂得解代数方程的基本原理，会解简单的代数方程；会用方程解决简单的实际问题；了解估算的意义，会通过估算进行猜测或检验；初步形成数量观念，能从数量及其变化规律的角度认识事物。  \\  \hline

图形与几何 & 认识平面和空间的基本图形，会画简单的平面图形；掌握简单平面图形的基本性质和有关距离、长度、角度、面积的计算方法；理解基本的图形运动；认识平面直角坐标系；对向量的概念和向量的加减运算有初步的认识。 \\  \hline

函数与概率统计初步 & 理解函数的意义；理解正比例函数、反比例函数、一次函数的概念，会画它们的图像并从中得到一些基本性质；会用函数解决简单的实际问题；了解概率与统计的意义；会收集、分析数据和从统计图表中获取信息；会计算简单的等可能事件的概率。 \\  \hline

\end{longtable}
\end{itshape}


### 能力维度

`r tab_name <- "能力维度测评矩阵" `
中学数学测试框架对学生数学能力表现的测评具体建构在能力维度中。能力维度依据《课程标准》中的“过程与方法”目标，结合初中数学课程实施的现状，并参考国际相关类型数学测试的框架而设计，以体现“过程”与“方法”的矩阵结构呈现（见表\ref{tab: `r tab_name`}）。

\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{2.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

\multicolumn{2}{|c|}{\multirow{2}{*}{}} & \multicolumn{4}{c|}{过程分量（主分量）}  \\   \cline{3-6}
\multicolumn{2}{|c|}{} & \makecell[c]{辨识\\Formulating} &	\makecell[c]{调用\\Employing} &	\makecell[c]{反思\\Reflecting} &	\makecell[c]{聚合\\Polymerizing} \\ \hline

\multirow{6}{*}{方法分量} & 运算求解 & & & & \\ \cline{2-6}
 & 推理论证 & & & & \\ \cline{2-6}
 & 空间想象 & & & & \\ \cline{2-6}
 & 数学表达 & & & & \\ \cline{2-6}
 & 数据处理 & & & & \\ \cline{2-6}
 & 数学建模 & & & & \\ \hline
\end{longtable}
\end{itshape}

从上表可以看到，数学测试框架的能力维度是以“过程分量”和“方法分量”的二维形式呈现的，它对学生数学能力的测评也将以两个分量的共同作用下学生的表现来评估。

#### 过程分量的界定

`r tab_name <- "过程分量的界定" `
过程分量是能力维度评价的“主分量”，分“辨识”“调用”“反思”和“聚合”四类（见表\ref{tab: `r tab_name`}）。主要体现学生解决数学问题的整体过程或不同局部。在完成测评后，将通过分析不同过程分量的学生表现水平数据，对学生能力维度的表现做出整体评价。

\begin{itshape}
\mytable
\begin{longtable}{|c|p{13cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & \makecell[c]{总体描述} \\  \hline

辨识 & 主要是指个体准确辨析和识别数学问题中所包含的数学概念、规则或方法并合理再现；准确把握问题的限制条件和假设；将简单的真实情境转化为数学问题并准确加以表征或陈述的过程。  \\  \hline

调用 & 主要是指个体准确运用数学概念、事实、原理、性质或方法等有序开展推理或运算，形成解决常规问题的模型，并获得数学结论；能从图表中提取数学信息，进行数据的分析；用简单的工具进行测量；用直尺和圆规等工具根据给定的条件作图的过程。 \\  \hline

反思 & 主要是指个体对数学问题的解答过程和结论加以检验、判定或评价，建立知识之间的联系；将基于真实情境的问题的解答和结论回到问题情境中进行阐释或明确其在问题情境中的实际意义的过程。 \\  \hline

聚合 & 主要是指个体在解决新情境下（对被试学生而言）的问题时对以下过程的综合表现：能学习、辨识数学知识或提炼数学问题并合理运用数学语言加以表述；在问题情境或限制条件约束的基础上拟定方案，灵活运用策略、数据、模型及相关的数学技能、思想方法，或者创新地设计或运用新方法获得结论；能评判结论的正确性、合理性或解释结论的局限性。 \\  \hline

\end{longtable}
\end{itshape}

其中，对于“聚合”分量与其他三类分量的区别做以下两点补充：

（1）在“聚合”中的“新情境”是指对于被试学生总体而言较为新颖的真实情境或数学情境，可以表现为有别于常规形式化的数学问题或者较为综合的真实背景，也可以表现为对新的数学背景知识或方法的学习或运用的要求。

（2）学生在解决问题时，需要较为综合、完整地体现辨识、调用和反思三个主要过程。

#### 方法分量的界定

`r tab_name <- "方法分量的界定" `

一般来说，在解决数学问题的过程中学生所表现出的“能力”主要是指对数学的基础知识、基本技能和基本思想与方法等能否加以灵活、合理、准确地运用，既体现为若干不同类型的数学核心能力，也可以理解为对不同类型的数学“方法群（组）”的活用能力。中学数学测试框架的方法分量主要由6种数学基本“方法群（组）”组成（见表\ref{tab: `r tab_name`}），这里的“方法群（组）”也就是《基本要求》中提出的“核心能力”。

\begin{itshape}
\mytable
\begin{longtable}{|c|p{13cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

方法分量 & \makecell[c]{总体描述} \\  \hline

运算求解 & 合理运用法则、公式，依据算理进行运算求解,并能根据问题条件，寻求合理的求解途径与方法。  \\  \hline

推理论证 & 依据数学概念和原理创建或选择一系列推理方法做出有根据的数学推断或进行数学论证。 \\  \hline

空间想象 & 根据条件画出（或作出）图形；分析几何图形中的基本元素及其关系；能想象和描述图形的运动与变化，利用图形分析、揭示问题的本质。 \\  \hline

数学表达 & 合理运用数学语言（包括文字语言、图形语言和符号语言）表达思考数学对象、解决数学问题的过程，阐明自身数学观点、见解等。 \\  \hline

数据处理 & 用基本的统计量、统计图表等来反映所收集数据的若干主要特征；能结合统计数据开展分析、决策；能理解随机现象，并通过统计信息预测事件发生的可能性。 \\  \hline

数学建模 & 理解现实问题情境，抽象并结构化情境使之成为一个数学问题；运用数学模型解决数学问题并根据具体的现实情境解读并检验数学结果。 \\  \hline

\end{longtable}
\end{itshape}

## 九年级数学学业水平描述

学业水平界定是指被试学生在解决数学问题“过程”中综合运用基本“方法”后对其能力水平所进行的分层描述。《基本要求》指出，通过数学解题活动所能检测的“能力”，本质上是指学生在基于各类情境的问题解决过程中合理、准确、灵活地运用各种所学的数学概念原理、定理推论、方法技能和基本思想等的表现，因此，过程与方法主要用于检测学生的能力表现。数学测试框架将各层次学生在解决数学问题各类过程分量的水平描述从高到低分成A、B、C、D四个等级。

### “辨识”过程表现水平描述

`r tab_name <- "“辨识”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{12}{*}{辨识} & \multirow{3}{*}{A} & $\star$ 能根据各种情境需要正确回忆事实性结论和准确辨析及识别数学问题中所包含的数学概念、规则或方法；  \\
 &  & $\star$ 能在较为复杂的情境中准确把握问题的限制条件和假设；  \\
 &  & $\star$ 能将简单的真实情境转化为数学问题并准确加以表征或陈述。  \\ \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 能在动态的情境中回忆事实性结论和辨析及识别数学问题中所包含的数学概念、规则或方法；  \\
 &  & $\star$ 能在一般的情境中准确把握问题的限制条件和假设；  \\
 &  & $\star$ 能将简单的真实情境转化为数学问题并较为准确加以表征或陈述。  \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能在简单情境中回忆事实性结论和辨析及识别数学问题中所包含的数学概念、规则或方法； \\
 &  & $\star$ 能在较为简单的情境中把握问题的限制条件和假设；  \\
 &  & $\star$ 能将简单的真实情境转化为数学问题，但不能较为准确加以表征或陈述。  \\ \cline{2-3}


 & \multirow{3}{*}{D} & $\star$ 不能在情境中回忆事实性结论和约定及辨识数学对象，或回忆出部分、混淆简单事实性结论、对象；  \\
 &  & $\star$ 不能在较为简单的情境中把握问题的限制条件和假设；  \\
 &  & $\star$ 不能将简单的真实情境转化为数学问题，不能较为准确加以表征或陈述。  \\ \hline

\end{longtable}
\end{itshape}

### “调用”过程表现水平描述

`r tab_name <- "“调用”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{2}{*}{调用} & \multirow{2}{*}{A} & $\star$ 能根据问题需要准确调用数学概念、事实、原理、性质或方法等，有序开展操作、计算或推理，并获得准确的数学结论；  \\
 &  & $\star$ 能在复杂情境中识别解决具体问题所需要的算法，并能用相应的模型准确地解决问题；  \\
 &  & $\star$ 能从复杂的图表中准确提取数学信息，合理地进行数据的分析；  \\
 &  & $\star$ 能使用较为复杂的工具进行测量、根据给定的条件进行较为复杂的作图。  \\ \cline{2-3}

 & \multirow{4}{*}{B} & $\star$ 能根据问题需要调用数学概念、事实、原理、性质或方法等，开展操作、计算或推理，并获得数学结论；  \\
 &  & $\star$ 能在具体情境中识别解决问题所需要的算法，并通过列式计算、画出图表等解决问题；   \\
 &  & $\star$ 能从图表中准确提取数学信息，合理地进行数据的分析；   \\
 &  & $\star$ 能使用常见的工具进行测量、作图。  \\ \cline{2-3}

 & \multirow{4}{*}{C} & $\star$ 能根据问题需要调用简单的数学概念、事实、原理、性质或方法等，开展操作、计算或推理，并获得简单的数学结论； \\
 &  & $\star$ 能在简单情境中识别解决具体问题所需要的算法，并通过列式计算、画出图表等解决问题；   \\
 &  & $\star$ 能从图表中提取数学信息进行数据的分析；   \\
 &  & $\star$ 能使用简单工具进行直接测量、根据给定的条件进行简单作图。  \\ \cline{2-3}


 & \multirow{4}{*}{D} & $\star$ 不能根据问题需要准确调用数学概念、事实、原理、性质或方法等，开展操作、计算或推理，不能准确地获得数学结论；  \\
 &  & $\star$ 不能在具体情境中识别解决问题所需的算法，或计算中频繁出错；  \\
 &  & $\star$ 不能用简单工具进行最基本的测量、作图，或者测量与作图中频繁出错。   \\
 &  & $\star$ 不能从图表中提取数学信息，不能进行数据的分析或分析出错。  \\ \hline

\end{longtable}
\end{itshape}


### “反思”过程表现水平描述

`r tab_name <- "“反思”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{12}{*}{反思} & \multirow{3}{*}{A} & $\star$ 能对复杂的数学问题的解答和结论加以准确地检验、判定或评价；  \\
 &  & $\star$ 能将基于复杂真实情境问题的解答和结论回到问题情境中进行准确阐释，并明确其在问题情境中的实际意义。  \\
 &  & $\star$ 能对解决数学问题的过程与方法进行反思，建立知识之间的实质性联系。  \\ \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 能对较复杂的数学问题的解答和结论加以较为准确地检验、判定或评价； \\
 &  & $\star$ 能将基于较复杂的真实情境问题的解答和结论回到问题情境中进行阐释并明确其在问题情境中的实际意义。  \\
 &  & $\star$ 能对解决数学问题的过程与方法进行反思，建立知识之间的直接联系。  \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能对简单的数学问题的解答和结论加以检验、判定或评价； \\
 &  & $\star$ 能将基于简单真实情境问题的解答和结论回到问题情境中进行阐释或明确其在问题情境中的意义。  \\
 &  & $\star$ 能对解决一类数学问题的过程与方法进行简答总结和反思。  \\ \cline{2-3}

 & \multirow{3}{*}{D} & $\star$ 不能对数学问题解答和结论加以检验、判定或评价，或对数学问题解答和结论作出错误的检验、判定或评价。  \\
 &  & $\star$ 不能将基于真实情境问题的解答和结论回到问题情境中进行阐释或不明确其在问题情境中的实际意义。  \\
 &  & $\star$ 不能通过反思建立知识之间的直接联系，或建立联系中有明显错误。  \\ \hline

\end{longtable}
\end{itshape}


### “聚合”过程表现水平描述

`r tab_name <- "“聚合”过程表现水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

过程分量 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{16}{*}{聚合} & \multirow{4}{*}{A} & $\star$ 能在新的问题情境下提炼数学问题，构建数学模型，并合理运用数学语言表述； \\
 &  & $\star$ 能在问题情境或限制条件约束的基础上，灵活运用策略、数据、模型及相关的数学技能、思想方法，或者创新地设计或运用新方法获得结论；  \\
 &  & $\star$ 能从基本事实出发，用猜想—归纳—演绎推理的方式确认某一结论的正确性，或者能发现并运用数学方法解释结论的局限性； \\
 &  & $\star$ 能对解决问题的过程进行评价和推广，并进一步提出问题。  \\ \cline{2-3}

 & \multirow{4}{*}{B} & $\star$ 能辨识新的问题情境中数学问题，并运用数学语言表述；  \\
 &  & $\star$ 能在问题情境或限制条件约束的基础上，运用已有数学技能、思想方法，或者运用问题情境中的新方法获得结论；  \\
 &  & $\star$ 能用简单推理的方式验证获得的结果和数学结论，或能发现并尝试解释结论的局限性. \\
 &  & $\star$ 能对解决问题的过程进行简单的评价和推广，能在已有结论的基础上提出问题。 \\ \cline{2-3}

 & \multirow{4}{*}{C} & $\star$ 能读懂新问题情境中的数学信息，但不能用准确的数学语言表述； \\
 &  & $\star$ 能在问题情境或限制条件约束的基础上，运用简单的数学技能、思想方法获得一些简单的结论； \\
 &  & $\star$ 能通过举例等方式验证结果和数学结论，或发现结论的局限性； \\
 &  & $\star$ 能对解决问题的过程进行简单评价。  \\ \cline{2-3}

 & \multirow{4}{*}{D} & $\star$ 不能有效提取新的问题情境中的数学信息，或不能用数学语言表述； \\
 &  & $\star$ 不能对数学结果和结论进行简单的论证和解释，或不能发现结论中局限性；  \\
 &  & $\star$ 不能在新情境下运用数学知识与方法解决简单问题，或解决问题的基本策略与方法有明显错误； \\
 &  & $\star$ 不能对解决问题中的知识和方法进行评价和简单推广，或评价与推广中有明显错误。 \\ \hline

\end{longtable}
\end{itshape}



<!-- end of chapter description -->
