<!-- chapter description -->
\mytext

# 学科测试说明

## 八年级艺术学科测试简介

中学艺术学科学生学业水平测试的总目标是：考查学生对艺术作品的感知能力、正确理解和运用艺术语言进行艺术表达的能力，包括了解艺术形式、理解艺术内容、辨别艺术风格、体验艺术创作等。中学艺术课程标准中对中学艺术学科的定位是其具有综合性和关联性的特点，而艺术素养是指学生在解决与艺术相关的现实问题中所表现出来的关键能力、必备品格和正确的价值观。

2018年上海市初中学业质量绿色指标艺术素养测试，以《上海市中小学艺术课程标准》和和《上海市中学艺术学科教学基本要求》（2017版）为指导，根据《课程标准》的目标体系，参考了国际同类测试的惯例和国内外课程实施的现状，将中学艺术素养的测评内容围绕作品释读和艺术创编两个方面，进行“感受鉴赏”、“合作与分享”、“创作与表现”等能力的测评，以此刻画学生的艺术素养水平。

### 感受与鉴赏

“感受与鉴赏”主要指对艺术作品和艺术现象的感受、分析、理解、判断与评价。

感受与鉴赏是艺术学习的基础，包括对艺术作品和艺术现象的感受、分析、理解、判断与评价。学生要充分调动感官，描述对作品的感受，分层次评价作品。具体包括：

- 艺术形式——能够区分艺术的种类和题材、知道艺术作品中包含的艺术要素、辨别艺术呈现的形式特点，
- 艺术内容——能够结合艺术作品的呈现形式，分析和描述艺术作品表达的审美意图、思想情感等内容。
- 艺术风格——能识别艺术作品、艺术家、艺术流派，能结合艺术的形式和内容，辨别和描述艺术作品的时代与地域的特点

### 合作与分享

“合作与分享”指的是在艺术学习中与他人的协作、交流、分享。

合作与分享是艺术学习中很重要的情感输出与体验部分，强调艺术学习中与他人的交流，在艺术素养的评价中，通过对作品的理解形成具有开放、包容的文化理解，注重经验的分享。具体包括：

- 鉴赏艺术作品
- 联系艺术与其他领域
- 分享艺术经验与感受

### 表现与创作

“表现与创作”指的是以视、听、画、演、创进行表达与表现。表现与创作是艺术学习成果的直接体现，强调学生的模仿和改编，注重学生的构思创作、设计展演。具体包括：

- 艺术体验——多感官联动，用各种体验方式感受艺术，描述内心感受并表达情感；对艺术素材进行提炼、加工，对多种信息进行关联整合，能设计简单的艺术活动和展演。
- 艺术创作——能能够围绕主题的设计意图，运用恰当的艺术技巧和方法，进行艺术的摹仿、演绎、编辑、创作等。

此次艺术素养测试，是第一次在全市范围绿色指标测试过程中同步进行的。既有总项目组先期文献研究，尤其是对相关文件中的评价指标进行了系统梳理，也有命题团队的深入实践并研讨修订形成的测试工具，再通过市级平台全市统一开展的测评。此次指向艺术素养的考察，是本市艺术领域测评的第一次尝试探索，对艺术学科今后的发展起到了极大的推动作用。

\clearpage

## 艺术学业水平描述

`r tab_name <- "初中生艺术学科学业水平描述" `

学业水平描述是指被试学生在艺术领域的“感受与鉴赏”“合作与分享”“创作与表现”的表现情况界定，其针对学生水平的描述从高到低分成A、B、C、D四个等级。表\ref{tab: `r tab_name`}具体呈现不同水平的可能表现（或观测点）。

\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\  

\hline
能力维度	& 水平 &	水平描述 \\ \hline
\multirow{23}{*}{\makecell{感受与鉴赏}} &	\multirow{8}{*}{A}	 & $\star$	能准确感受并体会音乐、舞蹈、戏剧等表演艺术的表现形式 \\ \cline{3-3}
 & & $\star$	能准确感受并体会绘画、雕塑、设计等造型艺术的表现形式 \\ \cline{3-3}
 & & $\star$  能感受并分析作品中艺术要素的表现意义 \\ \cline{3-3}
 & & $\star$ 能知道并说明音乐的种类和体裁，如声乐、器乐及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 能知道并说明美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 能准确感受舞蹈、戏曲表达的人物情感 \\ \cline{3-3}
 & & $\star$ 能准确体会不同时期音乐、美术作品的艺术特色，并了解作品中蕴含的时代发展特点 \\ \cline{3-3}
 & & $\star$ 能知道并了解不同门类具有代表性的艺术家及其艺术经历 \\ \cline{2-3}
 &	\multirow{8}{*}{B} & $\star$	能感受并适当体会音乐、舞蹈、戏剧等表演艺术的表现形式 \\ \cline{3-3}
 & & $\star$ 能感受并适当体会绘画、雕塑、设计等造型艺术的表现形式  \\ \cline{3-3}
 & & $\star$ 能感受作并适当分析品中艺术要素的表现意义  \\ \cline{3-3}
 & & $\star$ 能知道并适当说明音乐的种类和体裁，如声乐、器乐及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能知道并适当说明美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能感受舞蹈、戏曲表达的人物情感  \\ \cline{3-3}
 & & $\star$ 能较为准确地体会不同时期音乐、美术作品的艺术特色，并了解作品中蕴含的时代发展特点  \\ \cline{3-3}
 & & $\star$ 能知道不同门类具有代表性的艺术家及其艺术经历  \\ \cline{2-3}
 &	\multirow{8}{*}{C} & $\star$	能知道音乐、舞蹈、戏剧等表演艺术的表现形式  \\ \cline{3-3}
 & & $\star$ 能知道体会绘画、雕塑、设计等造型艺术的表现形式  \\ \cline{3-3}
 & & $\star$ 能了解艺术要素的表现意义  \\ \cline{3-3}
 & & $\star$ 能知道音乐的种类和体裁，如声乐、知道器乐及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能知道美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等  \\ \cline{3-3}
 & & $\star$ 能初步感受舞蹈、戏曲表达的人物情感  \\ \cline{3-3}
 & & $\star$ 能基本知道不同时期音乐、美术作品的艺术特色  \\ \cline{3-3}
 & & $\star$ 基本了解不同门类具有代表性的艺术家及其艺术经历。  \\ \cline{2-3}
 &	\multirow{8}{*}{D} & $\star$	不知道音乐、舞蹈、戏剧等表演艺术的表现形式 \\ \cline{3-3}
 & & $\star$ 不知道体会绘画、雕塑、设计等造型艺术的表现形式 \\ \cline{3-3}
 & & $\star$ 不能了解艺术要素的表现意义 \\ \cline{3-3}
 & & $\star$ 不知道音乐的种类和体裁，如声乐、知道器乐及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 不知道美术的种类和体裁，如绘画、雕塑、建筑、书法、工艺、设计及其下属体裁等 \\ \cline{3-3}
 & & $\star$ 不能初步感受舞蹈、戏曲表达的人物情感 \\ \cline{3-3}
 & & $\star$ 不知道不同时期音乐、美术作品的艺术特色 \\ \cline{1-3}

\multirow{12}{*}{合作与分享}	& \multirow{3}{*}{A}	& $\star$	能准确评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 能主动并准确模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 能主动并准确用各种形式表达对音乐、美术及其相关艺术作品的感受 \\ \cline{2-3}
 & \multirow{3}{*}{B}	& $\star$	能较准确评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 能主动并较好模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 能主动并较为准确用各种形式表达对音乐、美术及其相关艺术作品的感受 \\ \cline{2-3}
 & \multirow{3}{*}{C}	& $\star$	能评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 能模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 能基本准确用各种形式表现对音乐、美术及其相关艺术作品的感受 \\ \cline{2-3}
 & \multirow{3}{*}{D}	& $\star$	不能准确评价音乐、美术及其相关艺术作品的情感表达 \\ \cline{3-3}
 & & $\star$ 不能模仿音乐、美术及其相关艺术的表达手法,表现喜、怒、哀、乐等情感 \\ \cline{3-3}
 & & $\star$ 不能用各种形式表现对音乐、美术及其相关艺术作品的感受 \\ \cline{1-3}

\multirow{8}{*}{表现与创作}	& A	& $\star$ 能主动收集、筛选、提炼创作素材，并准确运用相关内容表现 \\ \cline{3-3}
 & & $\star$ 能积极主动借鉴艺术家的创意,进行艺术构思 \\ \cline{2-3}
 & B & $\star$	能主动收集、筛选、提炼创作素材，并运用相关内容表现 \\ \cline{3-3}
 & & $\star$ 能借鉴艺术家的创意,进行艺术构思 \\ \cline{2-3}
 & C & $\star$ 能运用所给素材，进行内容表现 \\ \cline{3-3}
 & & $\star$ 能尝试借鉴艺术家的创意,进行艺术构思 \\ \cline{2-3}
 & D & $\star$ 不能收集、筛选、提炼创作素材，并表现 \\ \cline{3-3}
 & & $\star$ 不能借鉴艺术家的创意,进行艺术构思 \\ \cline{1-3}

\end{longtable}
\end{itshape}

<!-- end of chapter description -->
