<!-- chapter total -->

\mytext

# 学生总体表现

## 全体学生的总体表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.ar.rank.total.region")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.score.segment.ar.total")`}分别给出了上海市全体学生及不同区域学生在艺术素养各水平上的人数比例和得分分布。

plot.bar.city.ar.rank.total.region

plot.bar.city.base.score.segment.ar.total


## 不同群体学生的总体表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.ar.rank.total.perspective")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.city.ar.quantile.perspective")`}分别给出了上海市不同群体\footnote{其他：指普通初中、九年一贯制学校、完全中学之外的其他学校。}学生在艺术素养各水平上的人数比例和得分分布。

plot.bar.city.ar.rank.total.perspective

plot.box.city.ar.quantile.perspective

\mylist
注：盒须图——5\%学生得分小于等于须下端线分数；25\%学生得分小于等于盒底分数；50\%学生得分大于等于盒中横线分数；25\%学生得分大于等于盒顶分数；5\%学生得分大于等于须上端线分数；盒高度一定程度上反映了得分分布的离散程度；红点为平均分。
\mytext

## 不同区学生的总体表现

图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.base.score.rank.ar.total.district")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.city.base.score.quantile.ar.total.district")`}分别给出了上海市不同区学生在艺术素养各水平上的人数比例和得分分布。

plot.bar.city.base.score.rank.ar.total.district

plot.box.city.base.score.quantile.ar.total.district



<!-- end of chapter total -->
