<!-- chapter dimention -->

\mytext

# 学生在各考查维度上的表现情况

## 全体学生在各考查维度上的表现

本次艺术素养的测试，是从“感知与判断”“理解与分析”“运用与表现”等能力维度进行具体考查。

`r tab_name <- "艺术领域能力维度的具体分布与解释" `

表\ref{tab: `r tab_name`}为艺术领域测试框架中能力维度的具体分布与解释。

\begin{itshape}
\mytable
\begin{longtable}{|c|l|c|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline
考查维度 & \makecell[c]{具体描述} & 测试题型 \\ \hline
\multirow{2}{*}{感知与判断}	 & 在视听感受中，考察对艺术形式和内容的了解、辨认和理解等简单鉴赏能力 & 视听部分 \\ \cline{2-3}
  & 在图文信息中，考察对艺术作品的辨别和理解 & 纸笔部分 \\ \cline{1-3}
	理解与分析	& 在视听感受中，考察对艺术表现形式内容的分析、判断、释读等复杂鉴赏能力  & 视听部分 \\ \cline{1-3}
	运用与表现	& 在综合情境中考察艺术方法运用、设计构思、艺术创编的能力  & 纸笔部分 \\ \cline{1-3}
\end{longtable}
\end{itshape}


图\ref{fig: `r gio.R$GetPlotTitle("plot.bar.city.ar.dimention.rank")`}和图\ref{fig: `r gio.R$GetPlotTitle("plot.box.city.ar.dimention.quantile")`}分别给出了本市学生在艺术素养各考查维度各水平上的人数比例和得分分布。

plot.bar.city.ar.dimention.rank
plot.box.city.ar.dimention.quantile


## 学生在各考查维度的表现

### 感知与判断

视听部分：以视听的方式呈现艺术作品的欣赏，调动学生多感官体验，探索其中的主题、艺术要素、艺术门类等。

纸笔部分：主要以文字表达或视觉表达为主要途径。呈现艺术的相关信息，让学生在作品鉴赏中调动多种关联信息，进行艺术的识别、比较、判断和理解。

#### 不同群体学生的表现

plot.bar.city.ar.ganzhi.rank.perspective
plot.box.city.ar.ganzhi.quantile.perspective

#### 不同区学生的表现

plot.bar.city.ar.ganzhi.rank.district
plot.box.city.ar.ganzhi.quantile.district

\clearpage

### 理解与分析

在综合信息背景中，比较作品中的艺术元素、艺术方法，分析艺术形式的关联因素、艺术表现的内容，理解作者的思想感情，分析艺术形式与内容之间的关系，领会创作意义，评价创作形式。

#### 不同群体学生的表现

plot.bar.city.ar.lijie.rank.perspective
plot.box.city.ar.lijie.quantile.perspective

#### 不同区学生的表现

plot.bar.city.ar.lijie.rank.district
plot.box.city.ar.lijie.quantile.district

\clearpage

### 运用与表现

在综合主题情境中，能够在多种关联因素中，理解主题的含义，运用提供的素材，进行设计构思，能运用相应的艺术表现方法进行艺术的创编和表现。

结合相关性内容，本报告将选取若干试题，分别对此进行分析。

#### 不同群体学生的表现

plot.bar.city.ar.yunyong.rank.perspective
plot.box.city.ar.yunyong.quantile.perspective


#### 不同区学生的表现

plot.bar.city.ar.yunyong.rank.district
plot.box.city.ar.yunyong.quantile.district

<!-- end of chapter dimention -->
