<!-- chapter description -->
\mytext

# 学科测试说明

## 九年级英语学科测试简介

2018年上海市初中学业质量绿色指标英语学科测试，依据修订的18版英语学科测试框架，以《上海初中英语学科教学基本要求》（2017版）为指导，涵盖《英语》（“牛津”上海版）教材六至九年级所涉及的学习内容，从内容和能力两个维度选择部分观测点，考察九年级学生的语言综合运用能力，了解初中段学生英语课程的学习成效，为学校英语课程教学的改进提供反馈信息。

### 内容维度

内容维度以《教学基本要求》的七个单元为依据，包括语音、词汇、语法、语篇、功能意念和话题等方面的内容。本次绿色指标英语学科测试将“语法词汇”单列一个考查维度，将其余部分内容融入英语的听、读、写等语言技能的具体运用过程中，检测学生是否达到《教学基本要求》规定的教学内容与要求。

语音知识检测主要考查学生在听的过程中对英语发音、重音、连读、语调、节奏等的掌握，以及能否根据读音拼写单词和短语，也包括考查学生是否在语音语调发生变化时能体会说话人的意图和态度。

词汇知识的考查范围是教材六至八年级1,500个左右的核心词汇和100个左右的习惯用语。

语法知识的考查包含教材六至八年级所涉及的名词、代词、数词、形容词、副词的基本用法；动词基本时态的应用和基本句型的掌握。

语篇知识的考查与日常生活密切相关的话题相结合，通过听力、阅读和写作等形式检测语言的理解和运用能力。语篇知识的考查借助记叙文、说明文、议论文、应用文、对话等不同体裁和不同题材的文本，检测对各类文体的基本信息、关键词句、主旨大意、段落大意、隐含意义等的把握。


### 能力维度

八年级学生英语综合运用能力包括听、说、读、写四个方面。本次绿色指标英语学科测试的考查维度重点针对学生的英语听、读、写的基本技能，包括运用已学过的语言知识完成特定语言任务的能力。

听的能力主要指学生听懂句子和简单的语段并能做出相应反应的能力。如考查学生能否听懂稍慢于正常语速、熟悉话题的语段，识别主题，获取主要信息的能力；能否听懂简单故事的情节发展，理解其中主要人物和事件的能力；听懂简单、连续的指令和要求，并能使用所获得的信息完成简要记录等任务的能力。

读的能力主要是指学生对英语文本的整体感知以及提取、分析和处理信息的能力。如考查学生能否读懂简单指令，读懂常见体裁的简单阅读材料，完成相应任务的能力，或者能否找出具体信息、理解大意、根据上下文猜测生词的含义，理解事件发生顺序，理解并评价人物行为等。

写的能力是指学生实际运用英语书面传达信息和表达意思的能力，主要考查学生基本句子结构知识的掌握和基本词汇使用的情况以及根据图片、文字所提供的情境写出符合英语写作规范的简短文段的能力。

本次绿色指标英语学科测试工具的考查维度围绕《课程标准》的目标体系、符合国际同类测试的惯例和国内课程实施现状，聚焦听力、语法词汇、阅读和写作等考查重点，能较好地对学生的英语学习状况进行科学的评估。


## 八年级英语学业水平描述

八年级学生英语综合运用能力包括：能在设定的情景中进行问答；能就熟悉的话题同他人进行简单交流；能阅读基本无生词的短文，理解大意，获取关键信息；能书写一般文体的短文，进行简单描述和表达个人喜好，拼写和标点正确。英语学科测试框架将各层次学生英语综合运用能力水平描述从高到低分成A、B、C、D四个等级。

`r tab_name <- "九年级英语学科学业水平描述" `
\begin{itshape}
\mytable
\begin{longtable}{|c|c|p{12cm}|}
\caption{`r tab_name`} \label{tab: `r tab_name`} \\ \hline

考查能力 & 水平 & \makecell[c]{水平描述} \\  \hline

\multirow{2}{*}{听} & \multirow{2}{*}{A} & $\star$ 能在熟悉的情境中准确地理解说话人的意图和态度，并进行适当的判断；  \\
 &  & $\star$ 能准确地归纳和掌握所听内容的主旨和重要细节。  \\ \cline{2-3}

\multirow{9}{*}{} & \multirow{3}{*}{B} & $\star$ 能听懂发生在熟悉的情境中的对话和独白，并进行适当的判断；  \\
 &  & $\star$ 能听懂听力材料的主旨和重要细节；  \\
 &  & $\star$ 能借助文字、图表等听懂完成任务所需要的关键信息。 \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能听懂课堂用语和考试指令； \\
 &  & $\star$ 能听懂句子或简短对话中的关键信息，回答事实性问题；  \\
 &  & $\star$ 能借助文字、图表等大致听懂完成任务所需要的关键信息。  \\ \cline{2-3}

 & \multirow{3}{*}{D} & $\star$ 最多能听懂部分简单的课堂或考试指示语；  \\
 &  & $\star$ 最多能听懂所熟悉的话题语境中的有限信息； \\
 &  & $\star$ 在图片帮助下，最多能听懂所熟悉的话题语境中的部分语汇。 \\ \hline

\multirow{13}{*}{读} & \multirow{3}{*}{A} & $\star$ 能读懂所熟悉话题内容的简单读物； \\
 &  & $\star$ 能理解事件发生的原因、顺序和结果, 并能在一定程度上对有关信息进行推测或概括； \\
 &  & $\star$ 能根据上下文句子关系或运用英语构词基本知识猜测生词含义。 \\ \cline{2-3}

 & \multirow{4}{*}{B} & $\star$ 能读懂简短故事、个人信件或涉及日常生活等的语言材料； \\
 &  & $\star$ 能理解事件发生的原因、顺序和结果； \\
 &  & $\star$ 能在一定程度上对有关信息进行概括；  \\
 &  & $\star$ 能根据上下文猜测语言材料中部分生词含义。 \\ \cline{2-3}

 & \multirow{4}{*}{C} & $\star$ 能借助图片读懂英语句子； \\
 &  & $\star$ 能读懂简短故事、个人信件、简短的通知和广告等语言材料； \\
 &  & $\star$ 能从所读材料中找出相关信息； \\
 &  & $\star$ 能基本理解事件发生的原因、顺序和结果。 \\ \cline{2-3}

 & \multirow{2}{*}{D} & $\star$ 最多能读懂基本的指令性语言；  \\
 &  & $\star$ 最多能读懂英语简单句子的含义，但不能理解语篇的含义。 \\ \hline

\multirow{13}{*}{写} & \multirow{3}{*}{A} & $\star$ 能准确运用句法知识，写出结构、意义完整的句子； \\
 &  & $\star$ 能根据任务要求、文字或图片提示，写短文、便条、日记等，内容贴切、语义连贯、语言表达流畅； \\
 &  & $\star$ 能正确使用字母大、小写和标点符号。 \\ \cline{2-3}

 & \multirow{3}{*}{B} & $\star$ 能基本运用句法知识，写出结构基本完整的句子； \\
 &  & $\star$ 能根据任务要求、文字或图片提示，写短文、便条、日记等，内容基本贴切、语义基本连贯、语言表达大致流畅； \\
 &  & $\star$ 能基本正确使用字母大、小写和标点符号。 \\ \cline{2-3}

 & \multirow{3}{*}{C} & $\star$ 能尝试运用句法知识，写出句子的主要结构； \\
 &  & $\star$ 能根据任务要求、文字或图片提示，写短文、便条、日记等，部分内容贴切、语言表达欠流畅； \\
 &  & $\star$ 能注意到使用字母大、小写和标点符号，但使用欠准确。 \\ \cline{2-3}

 & \multirow{2}{*}{D} & $\star$ 最多能写出一些单词，但看不出句子结构，无法表达意义； \\
 &  & $\star$ 最多能注意到字母大、小写和标点符号。 \\ \hline

\end{longtable}
\end{itshape}

<!-- end of chapter description -->
