# -*- coding: utf-8 -*-

cfg:
  dirs:
    wd: './'
    in: 'in/'
    edited: 'edited/'
    temp: 'temp/'
    out: 'out/'
    word: 'word/'
  files:
    input: "in.docx"
    output: "out.docx"
    stage: "edited.docx"