<!-- chapter motivation  -->

# 学生学习动力指数

学习动力是学生对学习行为价值判断基础上的心理驱动总和，是引导、推动和维持学生参与学习活动的力量，主要包括学习自信心和学习动机两个二级指数。

## 学习自信心指数

学习自信心指学生对自己能否完成学习任务或达到学习目标的信念。主要体现在学生对个人学习能力的评估、对取得优异学习成绩和完成学习目标的预期等方面。

自信心和学术界的“自我效能感”概念类似。已有的研究发现，学习自我效能感能够正向预测学生的学习投入度、学业成就，并消减焦虑等负面情绪（杜宵丰、刘 坚，2017\cite{cite_01}；李维、白颖颖，2018\cite{cite_02}；何声清、綦春霞，2018\cite{cite_03}）。随着年级的上升，课业难度的增加、自我认知的日趋成熟，学生的自我效能感可能会有所降低（高 欢、陈克胜，2017\cite{cite_04}）。

学生自我效能感的来源主要有四个。过去所取得的成绩和成功能够促进学生形成较高的自我效能感。在全新的任务环境中，学生感觉到自身能力的提升（即使在任务完成上可能会失败）也有助于自我效能感的提升。通过观察与自己能力相近的同学、同伴的成功或失败的表现，能够促进或者抑制学生的自我效能感。当学生还不能对自己的能力进行很准确的判断时，他人（家长、教师、同伴的等）的支持有助于学生自我效能感的形成（Usher and Pajares，2008\cite{cite_05}） 。

研究者还指出，自我效能感具有情境性，同一个人在不同情境下的自我效能感可能会有所不同。例如一名学生可能有较高的语文学习自我效能感，但数学学习自我效能感却比较低。研究者建议，在实践和研究中，自我效能感的测量越具有情境聚焦性，其解释性越好，对教学的改进越有针对性（Usher and Pajares，2008\cite{cite_05}；Oney and Oksuzoglu-Guven，2015\cite{cite_07}）。
 

学习自信心主要通过调查学生对个人学习能力的评价、尝试解决困难问题的意愿以及对取得优异学习成绩和完成学习目标的预期等问题，采集学生问卷数据，并对数据进行统计分析得到的结果。

学习自信心指数分为 9 级，指数越高，表示该区域学生学习自信心越强。

\mylist
- 9 级：表示自信心较强\footnote{我们将得分超过维度总分 60\% 界定学生学习自信心较强。}的学生所占比例在 90% 以上（含 90%）
- 8 级：表示自信心较强的学生所占比例在 80%-90% 之间（含 80%）
- 7 级：表示自信心较强的学生所占比例在 70%-80% 之间（含 70%）
- 6 级：表示自信心较强的学生所占比例在 60%-70% 之间（含 60%）
- 5 级：表示自信心较强的学生所占比例在 50%-60% 之间（含 50%）
- 4 级：表示自信心较强的学生所占比例在 40%-50% 之间（含 40%）
- 3 级：表示自信心较强的学生所占比例在 30%-40% 之间（含 30%）
- 2 级：表示自信心较强的学生所占比例在 20%-30% 之间（含 20%）
- 1 级：表示自信心较强的学生所占比例在 20% 以下
\mytext

plot.bar.city.index.confidence.perspective.district

## 学习动机指数

学习动机指引发与维持学生学习行为，并使之指向一定学业目标的一种动力倾向。学习动机主要体现在学生对学习任务的倾向，采取的学习行为，对学习结果的期待和解释等方面。

学术界有很多关于学习动机的理论（如归因理论、成就目标理论、期望价值理论），从不同的视角对学习动机进行描述、解释、分类（石绍华等人，2002\cite{cite_08}；范春林,、张大均，2007\cite{cite_09}； Graham and Weiner，2012\cite{cite_10}）。研究发现，学习动机的类型与强弱会影响学习者使用不同的学习策略，进而取得不同的学业成就。学习动机水平高的学习者会使用更积极的学习策略，从而获得更好的学业成就（范春林,、张大均，2007\cite{cite_09}；张雪莲、高玲，2009\cite{cite_11}；郭衎，曹一鸣，2019\cite{cite_12}）  。

研究还发现，学习动机和学习自我效能感、自尊、归因方式、家庭教养风格、生活价值取向等有关（石绍华等人，2002\cite{cite_08}）。随着年龄的增加，学习者的表层的学习动机会有所下降，深层的学习动机会有所上升，因此外部的表扬等激励措施对高年级学生的适用性较低（贾小娟等人，2012\cite{cite_13}） 。以学习动机理论为框架基础，设计良好的教育教学环境（如选择情境化的内容、探究学习等）能够激发、维持学生的学习动机，（贾小娟等人，2012\cite{cite_13}；Potvin and Hasni ，2014\cite{cite_14}；Lazowsk and Hulleman，2015\cite{cite_15}）。 

历年来大规模测试的数据显示，学生学习动机与学生学业水平呈现明显的相关，学习动机能够很好的预测学业成绩。学习动机是通过采集学生问卷数据，进行数据分析得到的结果。

学习动机指数分为 9 级，指数越高，表示该区域学生学习动机越强。

\mylist
- 9 级：表示学习动机较强\footnote{我们将得分超过本维度总分 60\% 界定为学生学习动机较强。}的学生所占比例在 90% 以上（含 90%）
- 8 级：表示学习动机较强的学生所占比例在 80%-90% 之间（含 80%）
- 7 级：表示学习动机较强的学生所占比例在 70%-80% 之间（含 70%）
- 6 级：表示学习动机较强的学生所占比例在 60%-70% 之间（含 60%）
- 5 级：表示学习动机较强的学生所占比例在 50%-60% 之间（含 50%）
- 4 级：表示学习动机较强的学生所占比例在 40%-50% 之间（含 40%）
- 3 级：表示学习动机较强的学生所占比例在 30%-40% 之间（含 30%）
- 2 级：表示学习动机较强的学生所占比例在 20%-30% 之间（含 20%）
- 1 级：表示学习动机较强的学生所占比例在 20% 以下
\mytext

plot.bar.city.index.motivation.perspective.district


<!-- end of chapter motivation  -->
