<!-- chapter score  -->

\mytext

# 学生学业水平指数

学生学业水平指学生对各学科课程标准所要求内容的掌握情况，是学生终身学习和发展的基础，包含学生学业水平的标准达成度、学生高层次思维能力、学生艺术素养这三个二级指标。

## 学生学业成绩标准达成度指数

按照考试性质与解释的差异，学业水平测试一般可以分成“常模参照测验”与“标准参照测验”。“标准参照测验”是基于界定良好的行为领域标准，参照这个标准对测验分数加以解释，它通过将考生实际能力与所要求达到的能力标准比较，对考生水平做出评价，关注的是学生是否达到标准。“常模参照测验”是通过某个学生与全体学生比较，决定该学生在团体中的相对位置，着眼于对学生的相对水平进行区分，关注的是排队和择优。由于常模参照测验关注排名，可能造成的现实影响是鼓励了竞争、测验与教学联系有可能不那么紧密，而且测验分数的解释对团体并不公平。

学生学业水平是依据课程标准，在大规模测试数据基础上，运用国际上通用的研究方法，对学生在某一学科、某一阶段应该掌握的基本内容与核心能力的发展水平进行的等级标定，与通常情况下的常模参照测验有着本质上的不同。

绿色指标评价项目对学业评价定位在基于标准的学业水平评价，是对国家课程标准的落实情况考察，因此本项目采用标准参照模式来编制试卷与解释分数，具体来说，学业水平标准指依据课程标准，学生在某一学科某一阶段应该掌握的基本内容与核心能力的标准等级。学业水平的标准达成度指各学科达到合格水平以上学生人数的比例。


\mylist

- 9 级：表示学业成绩的标准达成系数\footnote{将学业成绩合格率经过标准化等一系列转化后得到的数值，转化后的数据具有可加性和可比性，用于划
分学业成绩标准达成指数的等级。}在 0.9 及以上（含 0.9）
- 8 级：表示学业成绩的标准达成系数在 0.8-0.9 之间（含 0.8）
- 7 级：表示学业成绩的标准达成系数在 0.7-0.8 之间（含 0.7）
- 6 级：表示学业成绩的标准达成系数在 0.6-0.7 之间（含 0.6）
- 5 级：表示学业成绩的标准达成系数在 0.5-0.6 之间（含 0.5）
- 4 级：表示学业成绩的标准达成系数在 0.4-0.5 之间（含 0.4）
- 3 级：表示学业成绩的标准达成系数在 0.3-0.4 之间（含 0.3）
- 2 级：表示学业成绩的标准达成系数在 0.2-0.3 之间（含 0.2）
- 1 级：表示学业成绩的标准达成系数在 0.2 以下

\mytext

plot.bar.city.index.score.pass.perspective.district

plot.bar.city.index.cn.pass.perspective.district

plot.bar.city.index.ma.pass.perspective.district

plot.bar.city.index.en.pass.perspective.district

plot.bar.city.index.sc.pass.perspective.district



## 学生高层次思维能力指数

随着全球化和信息化进程的加快，科技变革正深刻改变人类的思维方式和行为方式，要在竞争日益激烈的社会取得成功，合作沟通、深度思考和理性判断是面向未来的必备技能。国外很多教育研究者认为，高层次思维能力是人生成功的一个重要因素，不断变化和充满挑战的世界需要我们的学生具备超越构建知识的能力，即需要高层次思维能力。

高层次思维能力指在没有既定解决路径的复杂情境中，个体为找到可能的解决方案，将新的信息和记忆中储存的信息进行相互关联、重新组合和拓展的能力，是区别于记忆、信息检索等较低认知水平层次的心智活动和认知能力。创造性思维、批判性思维等都属于高层次思维，在具体生活中的问题解决、决策制定都需要高层次思维能力。

研究表明，教室环境、学生的心理和智力特征对高层次思维能力有直接影响，家庭对高层次思维的影响甚微，但可以通过心理特征对高层次思维产生间接影响（Budsankom P, Sawangboon T, Damrongpanit S, 2015）。对于学校教育如何促进学生的高层次思维发展，Weiss 认为需遵循以下标准：（1）学生应该把学习的重心由知识转变成理解；（2）教师应该为学生创造一个能够有效互动的交流环境，鼓励他们验证、质疑、批判以及评估其它因素，通过各种途径参与构建知识，并通过自我探索生成新的知识；（3）学生需要意识到，他们必须成为一名积极的学习者，积极主动学习，对自己的学习担起责任（Weiss R E. ，2003）。

本项目中高层次思维能力的测量，是以语文、数学、英语、科学学科内容为载体，从理解、应用、分析、评价和创造能力等视角来编制试题考察。

\mylist

- 9 级：表示具备高层次思维能力的学生所占比例在 90% 以上（含 90%）
- 8 级：表示具备高层次思维能力的学生所占比例在 80%-90% 之间（含 80%）
- 7 级：表示具备高层次思维能力的学生所占比例在 70%-80% 之间（含 70%）
- 6 级：表示具备高层次思维能力的学生所占比例在 60%-70% 之间（含 60%）
- 5 级：表示具备高层次思维能力的学生所占比例在 50%-60% 之间（含 50%）
- 4 级：表示具备高层次思维能力的学生所占比例在 40%-50% 之间（含 40%）
- 3 级：表示具备高层次思维能力的学生所占比例在 30%-40% 之间（含 30%）
- 2 级：表示具备高层次思维能力的学生所占比例在 20%-30% 之间（含 20%）
- 1 级：表示具备高层次思维能力的学生所占比例在 20% 以下


\mytext

plot.bar.city.index.score.thinking.perspective.district

plot.bar.city.index.cn.thinking.perspective.district

plot.bar.city.index.ma.thinking.perspective.district

plot.bar.city.index.en.thinking.perspective.district

plot.bar.city.index.sc.thinking.perspective.district


## 学生艺术素养指数

良好的艺术素养让学生获得“美”的感受、濡染、体验，提升人文情怀，培养健全人格，建构完美人性，是学生未来发展的坚实基础。艺术教育对培养具有人文精神、创新能力的现代公民，对传承民族文化，增进世界文化交流，建立和谐社会具有重要价值和作用。

艺术素养指在艺术学习中用不同艺术语言反应、表现与创造，并能迁移到其他情境中的能力。艺术素养评估主要从创造、表现和反应三个维度来测评。其中，“创造”指以原创艺术作品的方式表达思想和情感；“反应”指观察、描述、分析和评价艺术作品；“表现”指表演已有的艺术作品。

上海绿色指标测试中的艺术素养测试，主要从艺术感知力、艺术审美情趣和艺术创意表达三个维度，采用纸笔测试和表现性评价方式来考察学生的艺术素养。不同的艺术形式（如音乐、美术等）要求内容有所不同。


学生艺术素养指数分为 9 级，指数越高，表示该区域具备良好艺术素养的学生比例越高。

\mylist
-  9级：表示具备良好艺术素养的学生所占比例在90%以上（含90%）
-  8级：表示具备良好艺术素养的学生所占比例在80%-90%之间（含80%）
-  7级：表示具备良好艺术素养的学生所占比例在70%-80%之间（含70%）
-  6级：表示具备良好艺术素养的学生所占比例在60%-70%之间（含60%）
-  5级：表示具备良好艺术素养的学生所占比例在50%-60%之间（含50%）
-  4级：表示具备良好艺术素养的学生所占比例在40%-50%之间（含40%）
-  3级：表示具备良好艺术素养的学生所占比例在30%-40%之间（含30%）
-  2级：表示具备良好艺术素养的学生所占比例在20%-30%之间（含20%）
-  1级：表示具备良好艺术素养的学生所占比例在20%以下

\mytext

plot.bar.city.index.ar.pass.perspective.district
