<!-- chapter teacher  -->

# 教师课程领导力指数

教师课程领导力指教师将课程意识与教学实践相融合，有效开展课堂教学活动的素质，主要包括教师教学理念、教师教学方式和教师学业评价能力三个二级指数。

plot.bar.city.index.teacher.leadership.perspective.district

## 教师教学理念指数
教师教学理念指教师对教学的观点和看法，以及在此基础上形成的相对稳定的思想和观念体系，反映了教师对教学实践的价值追求，是影响教师从事课程相关行为的直接因素。教师教学理念主要包括知识观、教学观、学生观等方面。

教师教学理念指数分为9级，指数越高，表示该区域学生对教师教学方式的评价越高。

\mylist

- 9级：表示90%以上的教师教学理念指数较好\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的教师教学理念指数较好（含80%）
- 7级：表示70%-80%的教师教学理念指数较好（含70%）
- 6级：表示60%-70%的教师教学理念指数较好（含60%）
- 5级：表示50%-60%的教师教学理念指数较好（含50%）
- 4级：表示40%-50%的教师教学理念指数较好（含40%）
- 3级：表示30%-40%的教师教学理念指数较好（含30%）
- 2级：表示20%-30%的教师教学理念指数较好（含20%）
- 1级：表示20%以下的教师教学理念指数较好

\mytext


plot.bar.city.index.teaching.method.perspective.district


## 教师教学方式指数

教师教学方式是教师为达到课程教学目标，在课堂教学过程中采取的途径、步骤、手段。主要考察教师在课堂上运用自主、合作、探究等方式进行教学的频率与程度。

教师教学方式指数分为9级，指数越高，表示该区域学生对教师教学方式的评价越高。

\mylist

- 9级：表示90%以上的学生对教师教学方式评价较高\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的学生对教师教学方式评价较高（含80%）
- 7级：表示70%-80%的学生对教师教学方式评价较高（含70%）
- 6级：表示60%-70%的学生对教师教学方式评价较高（含60%）
- 5级：表示50%-60%的学生对教师教学方式评价较高（含50%）
- 4级：表示40%-50%的学生对教师教学方式评价较高（含40%）
- 3级：表示30%-40%的学生对教师教学方式评价较高（含30%）
- 2级：表示20%-30%的学生对教师教学方式评价较高（含20%）
- 1级：表示20%以下的学生对教师教学方式评价较高

\mytext

plot.bar.city.index.teaching.opinion.perspective.district


## 教师学业评价能力指数
教师学业评价能力是教师为了了解课程与教学实施效果，对学生学业情况进行诊断的能力。主要考察教师确定评价目标、设计评价工具、分析评价结果等方面的表现。

教师学业评价能力指数分为9级，指数越高，表示教师学业评价能力越强。

\mylist

- 9级：表示90%以上教师学业评价能力较强\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的教师学业评价能力较强（含80%）
- 7级：表示70%-80%的教师学业评价能力较强（含70%）
- 6级：表示60%-70%的教师学业评价能力较强（含60%）
- 5级：表示50%-60%的教师学业评价能力较强（含50%）
- 4级：表示40%-50%的教师学业评价能力较强（含40%）
- 3级：表示30%-40%的教师学业评价能力较强（含30%）
- 2级：表示20%-30%的教师学业评价能力较强（含20%）
- 1级：表示20%以下的教师学业评价能力较强

\mytext

plot.bar.city.index.teaching.evaluation.perspective.district


<!-- end of chapter teacher  -->
