<!-- chapter pressure  -->

# 学生学业负担与压力指数

学业负担和压力指数从主观和客观两个方面对学生学业压力进行评估，包括学业负担和学业压力两个二级指数。

## 学业负担指数

学业负担是指学生为完成课内和课外学习任务所付出的代价。该指数主要通过调查学生睡眠时间、做作业时和补课时间等方面来反映学生所承受的学业负担的状况和程度。

学生学业负担指数分为9级，指数越高，表示该群体学生学业负担越轻。

\mylist

- 9级：表示学业负担适中与较轻\footnote{我们将以下三个条件满足两个的学生界定为学业负担适中与较轻的学生：1、睡眠时间在7小时以上；2、做作业时间在2小时以下；3、每周参加与考试学科的补课在4小时以下。
}的学生所占比例在90%以上（含90%）
- 8级：表示学业负担适中与较轻的学生所占比例在80%-90%之间（含80%）
- 7级：表示学业负担适中与较轻的学生所占比例在70%-80%之间（含70%）
- 6级：表示学业负担适中与较轻的学生所占比例在60%-70%之间（含60%）
- 5级：表示学业负担适中与较轻的学生所占比例在50%-60%之间（含50%）
- 4级：表示学业负担适中与较轻的学生所占比例在40%-50%之间（含40%）
- 3级：表示学业负担适中与较轻的学生所占比例在30%-40%之间（含30%）
- 2级：表示学业负担适中与较轻的学生所占比例在20%-30%之间（含20%）
- 1级：表示学业负担适中与较轻的学生所占比例在20%以下

\mytext

plot.bar.city.index.burden.perspective.district

## 学业负担分项指标

### 睡眠指数

通过对大规模测试数据的分析，结果显示与睡眠时间较多的学生相比，睡眠时间较少的学生，其学业成绩并没有随着睡眠时间的减少而提高。


参照相关政策文件，以八年级每天睡眠时间保证8小时以上为参照，将睡眠指数划分为9级，指数越高，表示睡眠时间得到保障的学生比例越高。

\mylist

- 9级：表示90%以上的学生睡眠时间得到基本保障（含90%）
- 8级：表示80%-90%的学生睡眠时间得到基本保障（含80%）
- 7级：表示70%-80%的学生睡眠时间得到基本保障（含70%）
- 6级：表示60%-70%的学生睡眠时间得到基本保障（含60%）
- 5级：表示50%-60%的学生睡眠时间得到基本保障（含50%）
- 4级：表示40%-50%的学生睡眠时间得到基本保障（含40%）
- 3级：表示30%-40%的学生睡眠时间得到基本保障（含30%）
- 2级：表示20%-30%的学生睡眠时间得到基本保障（含20%）
- 1级：表示20%以下的学生睡眠时间得到基本保障

\mytext

plot.bar.city.index.sleep.perspective.district




### 作业指数


参照有关文件和相关研究成果，八年级学生每天做作业时间2小时以下为宜。以此为参照，将作业时间指数划分为9级，指数越高，表示作业量适宜的学生比例越高。

\mylist

- 9级：表示90%以上的学生作业量适宜（含90%）
- 8级：表示80%-90%的学生作业量适宜（含80%）
- 7级：表示70%-80%的学生作业量适宜（含70%）
- 6级：表示60%-70%的学生作业量适宜（含60%）
- 5级：表示50%-60%的学生作业量适宜（含50%）
- 4级：表示40%-50%的学生作业量适宜（含40%）
- 3级：表示30%-40%的学生作业量适宜（含30%）
- 2级：表示20%-30%的学生作业量适宜（含20%）
- 1级：表示20%以下的学生作业量适宜

\mytext

plot.bar.city.index.homework.perspective.district



### 补课指数（校外）

\mylist

- 9级：表示90%以上的学生每周参加与考试学科相关的校外补课2小时以下（含90%）
- 8级：表示80%-90%的学生每周参加与考试学科相关的校外补课2小时以下（含80%）
- 7级：表示70%-80%的学生每周参加与考试学科相关的校外补课2小时以下（含70%）
- 6级：表示60%-70%的学生每周参加与考试学科相关的校外补课2小时以下（含60%）
- 5级：表示50%-60%的学生每周参加与考试学科相关的校外补课2小时以下（含50%）
- 4级：表示40%-50%的学生每周参加与考试学科相关的校外补课2小时以下（含40%）
- 3级：表示30%-40%的学生每周参加与考试学科相关的校外补课2小时以下（含30%）
- 2级：表示20%-30%的学生每周参加与考试学科相关的校外补课2小时以下（含20%）
- 1级：表示20%以下的学生每周参加与考试学科相关的校外补课2小时以下

\mytext

plot.bar.city.index.buke.perspective.district


## 学习压力指数

学业压力是当环境要求超出学生自身应对能力时学生的主观感受。主要调查学生在学习过程中产生的心理负担、焦虑等消极的体验，通过询问学生在做作业、考试、课堂提问、成果反馈等情境中的心理状态进行考察。


学习压力指数分为9级，指数越高，表示该群体学生学习压力越小。

\mylist

- 9级：表示学习压力较小\footnote{我们将得分超过本维度总分60\%界定为学习压力较小。}的学生所占比例在90%以上（含90%）
- 8级：表示学习压力较小的学生所占比例在80%-90%之间（含80%）
- 7级：表示学习压力较小的学生所占比例在70%-80%之间（含70%）
- 6级：表示学习压力较小的学生所占比例在60%-70%之间（含60%）
- 5级：表示学习压力较小的学生所占比例在50%-60%之间（含50%）
- 4级：表示学习压力较小的学生所占比例在40%-50%之间（含40%）
- 3级：表示学习压力较小的学生所占比例在30%-40%之间（含30%）
- 2级：表示学习压力较小的学生所占比例在20%-30%之间（含20%）
- 1级：表示学习压力较小的学生所占比例在20%以下

\mytext

plot.bar.city.index.pressure.perspective.district

<!-- end of chapter pressure  -->
