<!-- chapter principal  -->



# 校长课程领导力指数

校长课程领导力是学校为实现办学目标、提升教育质量，在课程设计、开发、实施和评价等课程事务过程中，对课程活动相关人员进行引领和指导的能力，主要包含课程规划、课程实施和课程评价三个二级指数。


校长课程领导力指数分为9级，指数越高，表示教师对校长课程领导力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程领导力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程领导力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程领导力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程领导力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程领导力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程领导力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程领导力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程领导力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程领导力的评价较高

\mytext

plot.bar.city.index.principal.leadership.perspective.district

## 课程规划指数

课程规划指学校整体的课程规划与安排，主要考察学校课程理念与定位，课程体系结构，开设的课程类别与数量，社会实践性学习、社团活动、科技节艺术节的安排等方面。

课程规划指数分为9级，指数越高，表示教师对校长课程规划能力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程规划能力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程规划能力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程规划能力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程规划能力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程规划能力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程规划能力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程规划能力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程规划能力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程规划能力的评价较高

\mytext
plot.bar.city.index.principal.plan.perspective.district


## 课程实施指数

课程实施指学校根据课程计划，对整体课程进行有效落实的程度，主要包括学校课程的实际实施情况、课程实施的配套保障举措两个方面。其中，学校的课程实际实施情况包括三类课程的师资配置、校本材料的编制和使用、教研组和备课组活动的计划与开展、课堂教学对课程标准的落实程度、音体美等专用教室与场地器材的配置、校外资源的应用等。课程实施的配套保障举措包括教学常规等规章制度的建立与实施、对教师专业发展的支持、家校沟通与家校关系协调等。

课程实施指数分为9级，指数越高，表示教师对校长课程实施能力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程实施能力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程实施能力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程实施能力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程实施能力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程实施能力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程实施能力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程实施能力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程实施能力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程实施能力的评价较高

\mytext
plot.bar.city.index.principal.implement.perspective.district


## 课程评价指数
课程评价指学校为了解课程实施效果、对课程进行完善更新，对整体课程进行的监控。主要考察学校的整体课程评价框架、评价手段和方法、评价结果的分析与应用等。

课程评价指数分为9级，指数越高，表示教师对校长课程评价能力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程评价能力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程评价能力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程评价能力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程评价能力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程评价能力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程评价能力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程评价能力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程评价能力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程评价能力的评价较高

\mytext

plot.bar.city.index.principal.evaluation.perspective.district

<!-- end of chapter principal  -->
