<!-- chapter equity  -->

# 教育公平指数


## 学生学业成绩均衡指数

学生学业成绩均衡指数包括个体间均衡指数、学校间均衡指数和各区之间均衡指数三个方面。


### 学生学业成绩个体间均衡指数

学生学业成绩个体间均衡指数采用差异系数来描述，是通过对所有参测学生学业成绩的标准差和平均分进行统计分析得到的结果。


按照学生学业成绩的差异大小分为9级，指数越高，表示学生学业成绩差异越小，均衡度越高。

\mylist
-  9级：表示学生学业成绩均衡系数在0.9及以上（含0.9）
-  8级：表示学生学业成绩均衡系数在0.8-0.9之间（含0.8）
-  7级：表示学生学业成绩均衡系数在0.7-0.8之间（含0.7）
-  6级：表示学生学业成绩均衡系数在0.6-0.7之间（含0.6）
-  5级：表示学生学业成绩均衡系数在0.5-0.6之间（含0.5）
-  4级：表示学生学业成绩均衡系数在0.4-0.5之间（含0.4）
-  3级：表示学生学业成绩均衡系数在0.3-0.4之间（含0.3）
-  2级：表示学生学业成绩均衡系数在0.2-0.3之间（含0.2）
-  1级：表示学生学业成绩均衡系数在0.2以下

\mytext

plot.bar.city.index.score.balance.perspective.district
plot.bar.city.index.cn.balance.perspective.district
plot.bar.city.index.ma.balance.perspective.district
plot.bar.city.index.en.balance.perspective.district
plot.bar.city.index.sc.balance.perspective.district
plot.bar.city.index.ar.balance.perspective.district

### 学生学业成绩学校间均衡指数

学生学业成绩学校间均衡是通过各学校之间学业成绩差异的大小来反映的，是采用多层线性模型统计分析得到的结果。

学业成绩学校间均衡指数分为9级，指数越高，表示学校间学业成绩差异越小，均衡度越高。

\mylist

-  9级：表示学生学业成绩学校间的均衡系数\footnote{将学业成绩学校解释率经过标准化等一系列转化后得到的数值，转化后的数据具有可加性和可比性，用于划分学业成绩校间均衡指数的等级。}在0.9及以上（含0.9）
-  8级：表示学生学业成绩学校间的均衡系数在0.8-0.9之间（含0.8）
-  7级：表示学生学业成绩学校间的均衡系数在0.7-0.8之间（含0.7）
-  6级：表示学生学业成绩学校间的均衡系数在0.6-0.7之间（含0.6）
-  5级：表示学生学业成绩学校间的均衡系数在0.5-0.6之间（含0.5）
-  4级：表示学生学业成绩学校间的均衡系数在0.4-0.5之间（含0.4）
-  3级：表示学生学业成绩学校间的均衡系数在0.3-0.4之间（含0.3）
-  2级：表示学生学业成绩学校间的均衡系数在0.2-0.3之间（含0.2）
-  1级：表示学生学业成绩学校间的均衡系数在0.2以下

\mytext


plot.bar.city.index.score.balance.school.district
plot.bar.city.index.cn.balance.school.district
plot.bar.city.index.ma.balance.school.district
plot.bar.city.index.en.balance.school.district
plot.bar.city.index.sc.balance.school.district
plot.bar.city.index.ar.balance.school.district


### 学生学业成绩各区之间均衡指数


学生学业成绩各区之间均衡是通过各区之间学业成绩差异的大小来反映的，是采用多层线性模型统计分析得到的结果。


学业成绩各区之间均衡指数分为9级，指数越高，表示各区之间学业成绩差异越小，均衡度越高。

\mylist
-  9级：表示学生学业成绩各区之间的均衡系数在0.9及以上（含0.9）
-  8级：表示学生学业成绩各区之间的均衡系数在0.8-0.9之间（含0.8）
-  7级：表示学生学业成绩各区之间的均衡系数在0.7-0.8之间（含0.7）
-  6级：表示学生学业成绩各区之间的均衡系数在0.6-0.7之间（含0.6）
-  5级：表示学生学业成绩各区之间的均衡系数在0.5-0.6之间（含0.5）
-  4级：表示学生学业成绩各区之间的均衡系数在0.4-0.5之间（含0.4）
-  3级：表示学生学业成绩各区之间的均衡系数在0.3-0.4之间（含0.3）
-  2级：表示学生学业成绩各区之间的均衡系数在0.2-0.3之间（含0.2）
-  1级：表示学生学业成绩各区之间的均衡系数在0.2以下

\mytext

plot.bar.city.index.score.balance.district.subject


<!--  end of chapter score  -->

## 学校教育消除学生社会经济背景对学业成绩的影响指数


父母受教育程度、职业、家庭文化资源等因素合成为学生社会经济背景。将学生社会经济背景与学生学业成绩进行相关分析，描述家庭背景对学生学业成绩的影响。

学生社会经济背景对学业成绩的影响指数分为9级，指数越高，表示学业成绩受家庭背景因素的影响越小，同时意味着学校在很大程度上弥补了家庭环境不利对学生学业的负面影响。

\mylist

- 9级：表示家庭背景影响系数\footnote{将学生社会经济背景解释率经过标准化等一系列转化后得到的数值，转化后的数据具有可加性和可比性，用于划分学生社会经济背景对学业成绩的影响指数的等级。}为0
- 8级：表示家庭背景影响系数在0-0.1之间（含0.1）
- 7级：表示家庭背景影响系数在0.1-0.2之间（含0.2）
- 6级：表示家庭背景影响系数在0.2-0.3之间（含0.3）
- 5级：表示家庭背景影响系数在0.3-0.4之间（含0.4）
- 4级：表示家庭背景影响系数在0.4-0.5之间（含0.5）
- 3级：表示家庭背景影响系数在0.5-0.6之间（含0.6）
- 2级：表示家庭背景影响系数在0.6-0.7之间（含0.7）
- 1级：表示家庭背景影响系数在0.7以上

\mytext

plot.bar.city.index.score.school.effect.district
plot.bar.city.index.cn.school.effect.district
plot.bar.city.index.ma.school.effect.district
plot.bar.city.index.en.school.effect.district
plot.bar.city.index.sc.school.effect.district

\clearpage

<!-- end of chapter equity  -->
