<!-- chapter health  -->

\mytext

# 学生身心健康指数

\mytext

学生身心健康是指身体与心理两方面的健康状态。

## 学生体质健康指数

\mytext

青少年是社会发展的基础和动力，青少年身体素质健康与否，不仅关系到学生的终身健康与幸福，同时也关系到国家的社会建设。健康体育意识和生活方式是发展青少年终身体育行为和终身健康的需要（郑家鲲，2013）。

学生体质健康指学生的人体形态结构、生理功能、身体素质等方面处于良好的状态。这种良好的状态主要通过身体形态（如身高、体重）、身体机能（如肺活量）和身体素质（如力量、耐力、爆发力、柔韧性）等方面进行判断。

通过采用不同健康水平指标研究健康与学业成绩的关系发现，学生有氧运动水平与学业成绩存在正向相关（Wittberg, Richard A,Northrup, Karen L,Cottrell, Lesley A.，2012），学生的心肺功能可能是影响学业表现的关键因素（梁哲, 张羽，2016）。对于体质健康对学业成绩的影响机制，研究认为，青少年体质影响学业成绩的路径不仅有直接影响,也有通过执行功能的间接影响，学生体质健康的改善可能有助于提升其学业成绩。（温煦, 张莹, 周鲁等，2018）。

《国家学生体质健康标准》测试项目包括身体形态、生理机能、身体素质等3方面21项指标。在各区教育行政部门的统一安排下，各校采用自测自报的方式，在 2018年9月1日至 2019 年 1 月 31 日之间自行组织测试。本报告中的数据来源于上海市学生体质健康监测中心。

学生体质健康指数分为 9 级，指数越高，表示学生体质健康情况越好。

\mylist

- 9级：表示体质健康系数\footnote{将体质健康综合评价及格率经过标准化等一系列转化后得到的数值，转化后的数据具有可加性和可比性，用于划分体质健康指数的等级。}在0.9及以上（含0.9）
- 8级：表示体质健康系数在0.8-0.9之间（含0.8）
- 7级：表示体质健康系数在0.7-0.8之间（含0.7）
- 6级：表示体质健康系数在0.6-0.7之间（含0.6）
- 5级：表示体质健康系数在0.5-0.6之间（含0.5）
- 4级：表示体质健康系数在0.4-0.5之间（含0.4）
- 3级：表示体质健康系数在0.3-0.4之间（含0.3）
- 2级：表示体质健康系数在0.2-0.3之间（含0.2）
- 1级：表示体质健康系数在0.2以下

\mytext

plot.bar.district.index.physical.health.perspective



## 学生心理健康指数

世界卫生组织宣言明确指出：“健康不仅仅是没有躯体疾病、不体弱,而是一种躯体、心理、社会适应、道德均臻良好的状态。”因此,中学生心理健康不仅是指生理身体方面,而且包括心理方面。心理健康对促进学生的潜能开发、人格完善与终身发展都具有重要的意义。

心理健康指个体能够适应发展变化的环境，具有完善的个性特征，其认知、情绪、意志行为处于积极状态，并能保持正常的调控能力。

研究发现，心理健康影响学生发展的很多方面，如幸福感、外向性、人际关系、学业成绩等，心理健康与这些方面都存在显著的正相关（李艳平，2003）。心理健康对学习成绩影响因素有：关注心悸和脉搏，父母期望过高，思想不集中和觉得别人轻视自己（潘秀丹, 管楠楠，2019）。

本项目中心理健康指标重点对情绪进行测评，主要包含情绪状态、情绪稳定性和情绪管理能力三个方面。其中，“情绪状态”指学生情感方面的心理状态（如高兴、难过）；“情绪稳定性”指学生在周遭事物的影响下，情绪波动的程度；“情绪管理能力”指学生对自身的情绪反应进行监控、评估、修正的能力。

学生心理健康指数是通过采集学生问卷数据，进行数据分析得到的结果。指数分为9级，指数越高，表示学生心理健康情况越好。

\mylist

- 9级：表示90%以上的学生心理健康较好\footnote{我们将得分超过本维度总分60\%界定为心理健康较好。}（含90%）
- 8级：表示80%-90%的学生心理健康较好（含80%）
- 7级：表示70%-80%的学生心理健康较好（含70%）
- 6级：表示60%-70%的学生心理健康较好（含60%）
- 5级：表示50%-60%的学生心理健康较好（含50%）
- 4级：表示40%-50%的学生心理健康较好（含40%）
- 3级：表示30%-40%的学生心理健康较好（含30%）
- 2级：表示20%-30%的学生心理健康较好（含20%）
- 1级：表示20%以下的学生心理健康较好

\mytext

plot.bar.district.index.mental.health.perspective
multiplot.bar.district.index.mental.health.school

plot.bar.district.index.emotion.status.perspective
multiplot.bar.district.index.emotion.status.school

plot.bar.district.index.emotion.stability.perspective
multiplot.bar.district.index.emotion.stability.school

plot.bar.district.index.emotion.management.perspective
multiplot.bar.district.index.emotion.management.school


<!--  end of chapter health  -->
