<!-- chapter identity  -->

# 学生对学校的认同度指数

学生对学校认同指的是学生对学校的认可与接纳，是学生对所在学校的价值观、学校精神及文化传统的承认和接受，主要包括师生关系、同伴关系、学校归属感三个二级指数。

学生对学校的认同度指数分为 9 级，指数越高，表示学生对学校的认同度越高。


\mylist

- 9级：表示对学校的认同度较高\footnote{我们将得分超过本维度总分60\%界定为对学校的认同度较高。}的学生所占比例在90%以上（含90%）
- 8级：表示对学校的认同度较高的学生所占比例在80%-90%之间（含80%）
- 7级：表示对学校的认同度较高的学生所占比例在70%-80%之间（含70%）
- 6级：表示对学校的认同度较高的学生所占比例在60%-70%之间（含60%）
- 5级：表示对学校的认同度较高的学生所占比例在50%-60%之间（含50%）
- 4级：表示对学校的认同度较高的学生所占比例在40%-50%之间（含40%）
- 3级：表示对学校的认同度较高的学生所占比例在30%-40%之间（含30%）
- 2级：表示对学校的认同度较高的学生所占比例在20%-30%之间（含20%）
- 1级：表示对学校的认同度较高的学生所占比例在20%以下

\mytext

plot.bar.district.index.school.identity.perspective
multiplot.bar.district.index.school.identity.school


## 师生关系指数

师生关系是教师和学生在教育教学过程中结成的相互关系，包括彼此所处的地位、作用和相互对待的态度。师生关系主要体现在教师对于学生的尊重，能公正、平等地对待学生，信任学生等方面。

师生关系指数分为 9 级，指数越高，表示师生关系越好。


\mylist

- 9级：表示师生关系指数较好\footnote{我们将得分超过本维度总分60\%界定为师生关系较好。}的学生所占比例在90%以上（含90%）
- 8级：表示师生关系指数较好的学生所占比例在80%-90%之间（含80%）
- 7级：表示师生关系指数较好的学生所占比例在70%-80%之间（含70%）
- 6级：表示师生关系指数较好的学生所占比例在60%-70%之间（含60%）
- 5级：表示师生关系指数较好的学生所占比例在50%-60%之间（含50%）
- 4级：表示师生关系指数较好的学生所占比例在40%-50%之间（含40%）
- 3级：表示师生关系指数较好的学生所占比例在30%-40%之间（含30%）
- 2级：表示师生关系指数较好的学生所占比例在20%-30%之间（含20%）
- 1级：表示师生关系指数较好的学生所占比例在20%以下

\mytext

plot.bar.district.index.teacher.relation.perspective
multiplot.bar.district.index.teacher.relation.school


## 同伴关系指数

同伴关系是指年龄相同或相近的儿童或青少年之间的一种共同活动并相互协作的关系。学校中的同伴关系主要体现在一个班集体中的学生之间是否彼此接纳与包容，是否协作与交流，是否相互理解与尊重。

同伴关系指数分为 9 级，指数越高，表示同伴关系越好。


\mylist

- 9级：表示同伴关系较好\footnote{我们将得分超过本维度总分60\%界定为同伴关系较好。}的学生所占比例在90%以上（含90%）
- 8级：表示同伴关系较好的学生所占比例在80%-90%之间（含80%）
- 7级：表示同伴关系较好的学生所占比例在70%-80%之间（含70%）
- 6级：表示同伴关系较好的学生所占比例在60%-70%之间（含60%）
- 5级：表示同伴关系较好的学生所占比例在50%-60%之间（含50%）
- 4级：表示同伴关系较好的学生所占比例在40%-50%之间（含40%）
- 3级：表示同伴关系较好的学生所占比例在30%-40%之间（含30%）
- 2级：表示同伴关系较好的学生所占比例在20%-30%之间（含20%）
- 1级：表示同伴关系较好的学生所占比例在20%以下

\mytext

plot.bar.district.index.classmate.relation.perspective
multiplot.bar.district.index.classmate.relation.school


## 学校归属感指数

学校归属感是指学生对自己所就读的学校在思想上、感情上和心理上的认可和投入、愿意承担作为学校一员的各项责任和义务以及乐于参与学校集体活动。主要体现在学生是否认同学校的理念、是否积极参加学校集体活动等方面。

学校归属感指数分为 9 级，指数越高，表示学校归属感越强。

\mylist

- 9级：表示学校归属感较强\footnote{我们将得分超过本维度总分60\%界定为学校归属感较强。}的学生所占比例在90%以上（含90%）
- 8级：表示学校归属感较强的学生所占比例在80%-90%之间（含80%）
- 7级：表示学校归属感较强的学生所占比例在70%-80%之间（含70%）
- 6级：表示学校归属感较强的学生所占比例在60%-70%之间（含60%）
- 5级：表示学校归属感较强的学生所占比例在50%-60%之间（含50%）
- 4级：表示学校归属感较强的学生所占比例在40%-50%之间（含40%）
- 3级：表示学校归属感较强的学生所占比例在30%-40%之间（含30%）
- 2级：表示学校归属感较强的学生所占比例在20%-30%之间（含20%）
- 1级：表示学校归属感较强的学生所占比例在20%以下

\mytext

plot.bar.district.index.school.sense.perspective
multiplot.bar.district.index.school.sense.school

<!-- end of chapter identity  -->
