<!-- chapter principal  -->



# 校长课程领导力指数

校长课程领导力是学校为实现办学目标、提升教育质量，在课程设计、开发、实施和评价等课程事务过程中，对课程活动相关人员进行引领和指导的能力，主要包含课程规划、课程实施和课程评价三个二级指数。


校长课程领导力指数分为9级，指数越高，表示教师对校长课程领导力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程领导力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程领导力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程领导力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程领导力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程领导力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程领导力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程领导力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程领导力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程领导力的评价较高

\mytext

plot.bar.district.index.principal.leadership.perspective
multiplot.bar.district.index.principal.leadership.school


## 课程规划指数

课程规划就是学校对本校的课程设计、实施、评价进行全面的规划 ，是教育教学活动的纲领性方案，是学校为学生提供什么样的学习机会的整体回答。学校课程规划方案质量从一定程度上反映了学校的课程领导力。课程规划指标主要考察学校的课程理念与定位，课程体系结构，开设的课程类别与数量，社会实践性学习、社团活动、科技节艺术节的安排等方面 。

课程规划在课程开发中具有重要意义，分析、研究学校的课程规划，指导学校研制科学、有效的课程规划，是提升学校育人价值的前提 。学校课程规划包括课程方案、课程实施和评价、校本课程开发、课程管理机构的运行、教师的专业发展等方面的内容 ，其中任何一个环节都关系着学校的进步、教师的发展和学生需求的满足。学校根据发展实际，研制课程规划，对国家课程、地方课程和校本课程进行整体设计与实施，也是课程改革赋予学校的责任和权力。

通过研究学校的课程规划方案，可以及时找出学校在课程规划中存在的问题，为学校提供有针对性的参考和指导。在学校层面落实国家课程改革的要求，提升学校课程规划的有效性、科学性，促进各级各类课程的合理开设与实施，是完成各学段的课程育人目标的重要保障。

对课程规划的测量，有学者基于中国学校课程教学调查项目”(Investigation of Curriculum and Instruction in China，简称ICIC)数据库，建立了3 个维度 18 项条目的评价工具，对学校课程规划方案进行分析 。有学者采用了对学校的课程规划文本进行定量分析的方式来研究中小学课程规划的现状，通过开发《学校课程建设工作手册（试用）》，编制成了含有9项一级指标、35项二级指标的评价指标体系，从学校背景分析、课程理念、课程目标、课程结构、课程实施、资源选择与使用、评价建议和保障条件等方面对学校的课程整体建设文本进行了分类和定量统计 。


课程规划指数分为9级，指数越高，表示教师对校长课程规划能力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程规划能力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程规划能力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程规划能力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程规划能力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程规划能力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程规划能力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程规划能力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程规划能力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程规划能力的评价较高

\mytext
plot.bar.district.index.principal.plan.perspective
multiplot.bar.district.index.principal.plan.school


## 课程实施指数

国际上对于课程实施的研究起步较晚，一直到现在，关于课程实施的本质问题，学者和专家们都有不同的理解。一种观点认为，课程实施问题就是研究一个课程方案的执行情况；另一种观点则认为，课程实施是作为一个动态的过程而存在的 。

课程在教育中的核心地位和对人才培养的有着重要的影响。课程实施作为课程改革的一个组成部分，是决定课程改革成败的一个关键性环节。课程方案和课程标准只有经过学校的实践转化和教师的创造性传递，才能真正释放课程的育人功能。从这个意义上讲，课程实施和研发与修订工作同等重要，直接关系到立德树人根本任务的落实落细落小，是解决好课程育人“最后一公里”的重要政治任务 。

在此背景下，对课程实施策略、课程实施取向、课程实施影响因素和课程实施程度的检测等方面的研究就至关重要。

关于课程实施程度的测量因其较强的技术倾向、历时较长和难以量化等原因而存在一定的困难。目前对课程实施的调查，主要有五种模型，包括使用水平模型LoU(Levels of use)、使用者概况模型UP(User profile)、课程实施调查模型SEC(Surveys of enacted curriculum)、教师多维度指标测量，以及L-CREB教师课程实施程度框架 。以上模型通过个案研究法、访谈、个案观察、问卷调查和行为评估单等方式，覆盖了大规模改革项目、阶段性改革项目、具体学科和整体性课程改革等多方面对象。

本次监测的课程实施指学校根据课程计划，对整体课程进行有效落实的程度，主要包括学校课程的实际实施情况、课程实施的配套保障举措两个方面。其中，学校的课程实际实施情况包括三类课程的师资配置、校本材料的编制和使用、教研组和备课组活动的计划与开展、课堂教学对课程标准的落实程度、音体美等专用教室与场地器材的配置、校外资源的应用等。课程实施的配套保障举措包括教学常规等规章制度的建立与实施、对教师专业发展的支持、家校沟通与家校关系协调等。


课程实施指数分为9级，指数越高，表示教师对校长课程实施能力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程实施能力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程实施能力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程实施能力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程实施能力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程实施能力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程实施能力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程实施能力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程实施能力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程实施能力的评价较高

\mytext
plot.bar.district.index.principal.implement.perspective
multiplot.bar.district.index.principal.implement.school


## 课程评价指数

20世纪30年代以来，课程评价作为一个专门的研究领域开始出现。美国课程学教授泰勒（Ralph W.Tyler）首创课程评价莅临，建立了行为目标的评价模式。考察课程评价的发展历程，关于课程评价的认识主要包括三种倾向：对课程活动进行价值判断的过程、提供评价信息的过程和相互作用的过程 。本次监测的课程评价是指学校为了解课程实施效果、对课程进行完善更新，对整体课程进行的监控，主要考察学校的整体课程评价框架、评价手段和方法、评价结果的分析与应用等 。
    
课程评价模式包括目标评价模式、外观评价模式、CIPP评价模式等，课程评价运用客观的过程、科学的工具解释了教与学的内容和过程，衡量了其有效程度。课程评价能够诊断学校课程，促进师生积极参与课程，能够帮助课程工作者作出合理的教育决策，形成各校个性化的课程等等。课程评价作为修订或调整课程体系时必不可少的重要环节，起着规范、管理、提升课程质量的功能，对课程改革的成效起着至关重要的作用 。
    
在此背景下，对课程评价的研究成为了指导学校课程建设的重要指标，也是考察学校课程发展完善程度的重要途径。对课程评价的研究成为了课程领域研究的焦点之一，它既帮助学校了解课程建设情况，又为学校改进课程与教学提供可指导。

对课程评价指标体系的构建，有学者通过比较不同类型的课程评价模式，从我国国情出发，形成了由课程设计评价、课程实施评价、课程结果评价相互交融的开放的三螺旋结构框架 。有学者以CIPP评价模式（又称为决策导向型模式）为基础，通过梳理评价指标、确定评价内容、确定体系指标的权重及评价标准等过程，制定出针对本学科领域的课程评价指标体系。也有学者从课程评价主体多元化、客体多元化和评价方法多元化三个维度出发，构建出“两层三维”的多元化评价指标体系，从而实现多元化评价的目的 。


课程评价指数分为9级，指数越高，表示教师对校长课程评价能力的评价越好。

\mylist

- 9级：表示90%以上的教师对校长课程评价能力的评价较高\footnote{我们将得分超过本维度总分60\%界定为教师对校长课程领导力评价较高。}（含90%）
- 8级：表示80%-90%的教师对校长课程评价能力的评价较高（含80%）
- 7级：表示70%-80%的教师对校长课程评价能力的评价较高（含70%）
- 6级：表示60%-70%的教师对校长课程评价能力的评价较高（含60%）
- 5级：表示50%-60%的教师对校长课程评价能力的评价较高（含50%）
- 4级：表示40%-50%的教师对校长课程评价能力的评价较高（含40%）
- 3级：表示30%-40%的教师对校长课程评价能力的评价较高（含30%）
- 2级：表示20%-30%的教师对校长课程评价能力的评价较高（含20%）
- 1级：表示20%以下的教师对校长课程评价能力的评价较高

\mytext

plot.bar.district.index.principal.evaluation.perspective
multiplot.bar.district.index.principal.evaluation.school

<!-- end of chapter principal  -->
