<!-- chapter equity  -->


\mytext

# 教育公平指数


## 学生学业成绩均衡指数

教育均衡发展，是指一定教育系统的各构成要素在内在机制和外在制度的作用下彼此协调一致时的一种相对稳定和平衡的发展状态或者发展结果。教育均衡发展既是一个理想目标，也是一个实践过程（姚永强，2014 \cite{cite_017}）。可以说，教育均衡是教育民主化、平等化进程中的重要理念，而学生学业质量的均衡是教育结果高位均衡的标志（倪娟，2012 \cite{cite_009} ）。学生的学业均衡程度是衡量教育公平程度的重要指标之一。

2010年，教育部发布《关于贯彻落实科学发展观进一步推进义务教育均衡发展的意见》，明确提出要按照《义务教育法》要求，将推进均衡发展作为义务教育改革与发展的重要任务，以提高教育质量、促进内涵发展为重点，推进义务教育均衡发展。由此可见，推进区域义务教育均衡发展已成为新时期我国教育改革与发展的一项基本政策。研究学生的学业均衡情况，不仅是促进教育公平、推进义务教育均衡发展政策的相关要求，也是为教育均衡化的实践与探索提供资料。

在本次监测中，学业均衡指数包括学生学业成绩个体间均衡指数、学生学业成绩学校间均衡指数和学生学业成绩各区之间均衡指数三个方面。通过分学科对学生学业成绩均衡系数的分析，得到三个指数的相应结论。


学生学业成绩均衡指数包括个体间均衡指数、学校间均衡指数两个方面。


### 学生学业成绩个体间均衡指数

学生学业成绩个体间均衡指数采用差异系数来描述，是通过对所有参测学生学业成绩的标准差和平均分进行统计分析得到的结果。


按照学生学业成绩的差异大小分为9级，指数越高，表示学生学业成绩差异越小，均衡度越高。

\mylist
-  9级：表示学生学业成绩均衡系数在0.9及以上（含0.9）
-  8级：表示学生学业成绩均衡系数在0.8-0.9之间（含0.8）
-  7级：表示学生学业成绩均衡系数在0.7-0.8之间（含0.7）
-  6级：表示学生学业成绩均衡系数在0.6-0.7之间（含0.6）
-  5级：表示学生学业成绩均衡系数在0.5-0.6之间（含0.5）
-  4级：表示学生学业成绩均衡系数在0.4-0.5之间（含0.4）
-  3级：表示学生学业成绩均衡系数在0.3-0.4之间（含0.3）
-  2级：表示学生学业成绩均衡系数在0.2-0.3之间（含0.2）
-  1级：表示学生学业成绩均衡系数在0.2以下

\mytext

plot.bar.district.index.score.balance.perspective
multiplot.bar.district.index.score.balance.school

plot.bar.district.index.cn.balance.perspective
multiplot.bar.district.index.cn.balance.school

plot.bar.district.index.ma.balance.perspective
multiplot.bar.district.index.ma.balance.school

plot.bar.district.index.en.balance.perspective
multiplot.bar.district.index.en.balance.school

plot.bar.district.index.sc.balance.perspective
multiplot.bar.district.index.sc.balance.school

plot.bar.district.index.ar.balance.perspective
multiplot.bar.district.index.ar.balance.school

### 学生学业成绩学校间均衡指数

学生学业成绩学校间均衡是通过各学校之间学业成绩差异的大小来反映的，是采用多层线性模型统计分析得到的结果。

学业成绩学校间均衡指数分为9级，指数越高，表示学校间学业成绩差异越小，均衡度越高。

\mylist

-  9级：表示学生学业成绩学校间的均衡系数\footnote{将学业成绩学校解释率经过标准化等一系列转化后得到的数值，转化后的数据具有可加性和可比性，用于划分学业成绩校间均衡指数的等级。}在0.9及以上（含0.9）
-  8级：表示学生学业成绩学校间的均衡系数在0.8-0.9之间（含0.8）
-  7级：表示学生学业成绩学校间的均衡系数在0.7-0.8之间（含0.7）
-  6级：表示学生学业成绩学校间的均衡系数在0.6-0.7之间（含0.6）
-  5级：表示学生学业成绩学校间的均衡系数在0.5-0.6之间（含0.5）
-  4级：表示学生学业成绩学校间的均衡系数在0.4-0.5之间（含0.4）
-  3级：表示学生学业成绩学校间的均衡系数在0.3-0.4之间（含0.3）
-  2级：表示学生学业成绩学校间的均衡系数在0.2-0.3之间（含0.2）
-  1级：表示学生学业成绩学校间的均衡系数在0.2以下

\mytext


plot.bar.district.index.score.balance.school.district
plot.bar.district.index.cn.balance.school.district
plot.bar.district.index.ma.balance.school.district
plot.bar.district.index.en.balance.school.district
plot.bar.district.index.sc.balance.school.district


## 学生社会经济背景对学业成绩的影响指数


家庭社会经济地位（socioeconomic status,SES）是个人或群体在社会中依据其所拥有的社会资源而被界定的社会位置（武丽丽等，2018 \cite{cite_014} ）。科尔曼是较早研究相关概念在学生教育中所起作用的学者，其认为社会资本是家长与子女之间、家长与教师之间及家长彼此之间形成的紧密网络（Coleman J S，1988 \cite{cite_022}）。家庭社会经济地位作为一个重要的环境变量一直是教育领域研究的重要主题。

相关研究显示，父母教育水平对学生的学业成绩有重要的预测作用（Melby J N等，2008 \cite{cite_024}），家庭收入与学生的认知成就关系密切（Hartas D，2013 \cite{cite_023} ）。父母职业与学生的学业成绩存在一定的关联，家庭社会经济地位与学生学业成绩总体上呈正相关（庞维国等，2013 \cite{cite_010} ）；但另一方面，家庭社会经济地位与学生学业成就之间的关系受制于诸多中介因素，如父母对孩子学习的介入水平、对孩子的教育期望、学生的学习动机等（Bradley R H & Corwyn R F，2002 \cite{cite_021} ）。虽然受到其他中介因素的影响，家庭社会经济地位对孩子学业成绩的显著影响是不可忽略的。在这种基础上，研究家庭社会经济地位对学生的学业成绩影响有助于有针对性地对学生家长进行指导教育、合理规划家长教育期望。虽然家庭的真实地位和情况难以在短期内得到改善和变化，但深入研究其与学业成绩的关系后，可以有针对性的调整其可变部分，使其向有利于学生提高成绩的方向发展，最大程度上为学生的成长和发展做出有益的调整。

在本监测中，通过调研和测试，将社会经济背景与学生学业成绩进行相关分析，得到学生社会经济背景对学业成绩的影响指数，并分析不同的社会经济背景对学生不同科目之间的影响指数。学生社会经济背景对学业成绩的影响指数分为9 级，指数越高，表示学业成绩受社会经济背景因素的影响越小，同时意味着学校在很大程度上弥补了社会经济背景不利对学生学业的负面影响。


\mylist

- 9级：表示社会经济背景影响系数\footnote{将学生社会经济背景解释率经过标准化等一系列转化后得到的数值，转化后的数据具有可加性和可比性，用于划分学生社会经济背景对学业成绩的影响指数的等级。}为0
- 8级：表示社会经济背景影响系数在0-0.1之间（含0.1）
- 7级：表示社会经济背景影响系数在0.1-0.2之间（含0.2）
- 6级：表示社会经济背景影响系数在0.2-0.3之间（含0.3）
- 5级：表示社会经济背景影响系数在0.3-0.4之间（含0.4）
- 4级：表示社会经济背景影响系数在0.4-0.5之间（含0.5）
- 3级：表示社会经济背景影响系数在0.5-0.6之间（含0.6）
- 2级：表示社会经济背景影响系数在0.6-0.7之间（含0.7）
- 1级：表示社会经济背景影响系数在0.7以上

\mytext

plot.bar.district.index.score.school.effect.district
plot.bar.district.index.cn.school.effect.district
plot.bar.district.index.ma.school.effect.district
plot.bar.district.index.en.school.effect.district
plot.bar.district.index.sc.school.effect.district

\clearpage

<!-- end of chapter equity  -->
