<!-- chapter teacher  -->

# 教师课程领导力指数

教师课程领导力指教师将课程意识与教学实践相融合，有效开展课堂教学活动的素质，主要包括教师教学理念、教师教学方式和教师学业评价能力三个二级指数。

plot.bar.district.index.teacher.leadership.perspective
multiplot.bar.district.index.teacher.leadership.school


## 教师教学理念指数

教学理念是一种关于教学实践的基本认识，一种主观信念，一种教学行为的驱动力量，是教学观念与教学理想的一种融合 。教师教学理念代表着教师对教学的观点和看法，以及在此基础上形成的相对稳定的思想和观念体系，反映了教师对教学实践的价值追求，是影响教师从事课程相关行为的直接因素。教师教学理念主要包括知识观、教学观、学生观等方面 。

教学理念是教师如何看待教学目标、选择教学方法的内在原因，也是教师如何与学生相处、学生能否从教育中受益的影响因素。实证研究表明，不同教学理念的教师，在多个相关指标中均存在显著差异 。同时，教学理念向教学行为转化是一个由外到内、再由内至外的转变过程，大致要经历学习理解—认同内化—创新生成—外化实践等环节。有学者认为，教学理念一旦内化为教师的信念，便可以为教学行为的转化提供理论导向，此外，教学理念还可以为教学行为的转化生成提供动力支持 。

正因为教师的教学理念面向教学实践过程,表达着教师的教育的理想，通过教师的教学活动进行反映，所以对教师教学理念的研究影响着教师的教学行为和专业发展，进而影响着学生的培养。教师教学理念的转变和提高也是提升教育质量的重要任务之一。
    
对教师教学理念的测量，主要是通过问卷调查的方式。如有学者在研究《全日制义务教育课程标准》（2011年版）中具体教学理念的基础上，通过开放式问卷的方式收集学生对教师的建议与意见，寻找教师教学理念的缺失 。也有学者通过设计基本信息问卷、《教师教学理念问卷》和子问卷《教师教学方法问卷》、《教师合作情况问卷》等，采用问卷调查的方式，调研总结了不同教学理念教师的基本特征、影响教师教学理念形成的主要因素等主题 。


教师教学理念指数分为9级，指数越高，表示该区域学生对教师教学方式的评价越高。

\mylist

- 9级：表示90%以上的教师教学理念指数较好\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的教师教学理念指数较好（含80%）
- 7级：表示70%-80%的教师教学理念指数较好（含70%）
- 6级：表示60%-70%的教师教学理念指数较好（含60%）
- 5级：表示50%-60%的教师教学理念指数较好（含50%）
- 4级：表示40%-50%的教师教学理念指数较好（含40%）
- 3级：表示30%-40%的教师教学理念指数较好（含30%）
- 2级：表示20%-30%的教师教学理念指数较好（含20%）
- 1级：表示20%以下的教师教学理念指数较好

\mytext


plot.bar.district.index.teaching.opinion.perspective
multiplot.bar.district.index.teaching.opinion.school



## 教师教学方式指数

教学方式指教师在教学过程中，为了达成教育目的采用的行为方式，既包括外显的行为，也包括内隐的思维方式。教学方式是教与学的方法和形式，包括观念性的方式和观念性与物质性结合的方式，是教学方法、形式、手段等的综合 。
    
教学方式承担了传递人类文化精粹的功能，科学的、人文的、知识的、技能性的等各种类型的文化都被有计划地组织到教学方式中，通过学科课程、活动课程、显性课程、隐性课程等多种形式、多种渠道再传递给学生,这就创设了各种文化相互碰撞、交流、融合的有利环境,为吸收先进文化提供了良好条件。有学者认为，知识教学方式影响能力发展的结果可能产生正向平衡和不平衡与负向平衡和不平衡四种状态。因此，选择合适的教学方式对学生能力和素养的发展是十分重要的。

学生核心素养的培养离不开教师教学方式的转变，而教师教学方式的转变不仅是外在行为的改变，而且是思维方式、思想观念的转变 。研究教师的教学方式，一方面可以为教师教学观念、教学行为的改进提供建议，另一方面也有助于学生核心素养的发展和培养。因材施教、互动合作、引导探究等多样的教学方式，对激发学生的学习兴趣，帮助学生学会学习、独立思考有所帮助。只有对教师的教学方式进行调研，依据学生的切实需要找出教学方式转变的切入点，才能为教师素质的提高和学生的发展提供支持。
    
目前对教师教学方式的调查以质性研究为主，主要通过问卷调查、课堂观察、开放式访谈与深度访谈等等方法进行，研究工具有调查问卷、访谈提纲、课堂观察记录表等等。调查对象包括教师与学生，针对不同的调查对象制定不同的调查问卷。在本监测中，教师的教学方式指教师为达到课程教学目标，在课堂教学过程中采取的途径、步骤、手段。主要考察教师在课堂上运用自主、合作、探究等方式进行教学的频率与程度。


教师教学方式指数分为9级，指数越高，表示该区域学生对教师教学方式的评价越高。

\mylist

- 9级：表示90%以上的学生对教师教学方式评价较高\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的学生对教师教学方式评价较高（含80%）
- 7级：表示70%-80%的学生对教师教学方式评价较高（含70%）
- 6级：表示60%-70%的学生对教师教学方式评价较高（含60%）
- 5级：表示50%-60%的学生对教师教学方式评价较高（含50%）
- 4级：表示40%-50%的学生对教师教学方式评价较高（含40%）
- 3级：表示30%-40%的学生对教师教学方式评价较高（含30%）
- 2级：表示20%-30%的学生对教师教学方式评价较高（含20%）
- 1级：表示20%以下的学生对教师教学方式评价较高

\mytext

plot.bar.district.index.teaching.method.perspective
multiplot.bar.district.index.teaching.method.school


## 教师学业评价能力指数

教师的学业评价能力是指教师运用测评知识和技能对学生施测，并能够分析测评结果，制定教学计划，作出行之有效的反馈，引导学生学习。教师的测评素养作为教师发展重要的组成部分而备受关注。

实证研究表明，教师评价影响学生的学业自我概念（academic self-concept）、学生的未来学业成就、成功期望（expectancy for success）和抱负水平（level of aspiration）。与知觉到的积极教师对待相比，知觉到的消极教师对待对学生的学业成果有更加广泛的中介效应。也有学者认为，教师在学业评级方面知识的欠缺将导致教育质量的削弱。教师评价素养的缺乏甚至会直接影响到课程改革的成败，影响到国家基础教育的质量。

在这样的背景下，教师的评价素养成为了亟须培育的内容，也是当今世界各国的教师专业标准的重要组成部分。教师的学业评价能力关系着课堂教学、作业布置、命题考试等等环节，关系着教师的教学反思及专业发展。关注教师的学业评价能力，才能完成从“教什么”到“学会什么”的转变。
    
对教师评价能力的测量，早在1990年，AFT、NCME、NEA便发布了“教师的学生教育评价能力标准”，定义了对教师教育评价能力的七个标准及与之对应的评价知识与技能 。在“教师的学生教育评价能力标准”的基础上，陆续形成了TALQ测量工具、ALI测量工具等。我国学者也在TALQ模型的基础上，对教师评价素养的测量工具进行了本土化改编，形成了《教师评价素养问卷》，并进行了相关实证研究。对教师评价素养与学生学业成就之间的联系，有学者进行了长达一年的追踪研究，通过前后分别的标准化测验及动机问卷对两者的相关性进行验证 。 


教师学业评价能力指数分为9级，指数越高，表示教师学业评价能力越强。

\mylist

- 9级：表示90%以上教师学业评价能力较强\footnote{我们将得分超过本维度总分60\%界定为学生对教师教学方式评价较高。}（含90%）
- 8级：表示80%-90%的教师学业评价能力较强（含80%）
- 7级：表示70%-80%的教师学业评价能力较强（含70%）
- 6级：表示60%-70%的教师学业评价能力较强（含60%）
- 5级：表示50%-60%的教师学业评价能力较强（含50%）
- 4级：表示40%-50%的教师学业评价能力较强（含40%）
- 3级：表示30%-40%的教师学业评价能力较强（含30%）
- 2级：表示20%-30%的教师学业评价能力较强（含20%）
- 1级：表示20%以下的教师学业评价能力较强

\mytext

plot.bar.district.index.teaching.evaluation.perspective
multiplot.bar.district.index.teaching.evaluation.school

<!-- end of chapter teacher  -->
